import { StyleSheet } from 'react-native';
import { theme } from './theme';

// App shell, shared layout, transitions, and bottom navigation primitives.
export const appShellStyles = {
  fullScreenRoot: {
    flex: 1,
    backgroundColor: theme.bgApp,
  },
  startupImagePreloadLayer: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0,
    pointerEvents: 'none',
    zIndex: -1,
  },
  startupImagePreload: {
    height: 1,
    width: 1,
  },
  transitionClipRoot: {
    overflow: 'hidden',
  },
  guestSplashTransitionForeground: {
    zIndex: 1,
  },
  guestSplashTransitionRoot: {
    backgroundColor: '#080101',
  },
  onboardingTransitionRoot: {
    flex: 1,
    backgroundColor: theme.bgApp,
    overflow: 'hidden',
  },
  screenTransitionLayer: {
    flex: 1,
    backgroundColor: theme.bgApp,
  },
  screenTransitionLayerAbsolute: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.bgApp,
  },
  bottomNavLoginTransitionLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
  },
  incomingOnboardingOverlay: {
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  safeArea: {
    flex: 1,
    backgroundColor: theme.bgApp,
  },
  safeAreaTransparent: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  screen: {
    flex: 1,
    paddingHorizontal: 18,
    paddingVertical: 14,
    gap: 14,
  },
  screenWithGuestChrome: {
    paddingTop: 70,
  },
  screenLandscape: {
    alignSelf: 'center',
    maxWidth: 1180,
    width: '100%',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  floatingDashboardButton: {
    alignItems: 'center',
    backgroundColor: theme.bgRaised,
    borderColor: theme.borderStrong,
    borderRadius: 18,
    borderWidth: 1,
    bottom: 0,
    justifyContent: 'center',
    minHeight: 48,
    minWidth: 146,
    paddingHorizontal: 16,
    paddingVertical: 12,
    position: 'absolute',
    right: 0,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 10,
    zIndex: 30,
  },
  floatingDashboardButtonMap: {
    zIndex: 40,
  },
  floatingGuestExitButton: {
    borderRadius: 999,
    minHeight: 54,
    minWidth: 54,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  floatingMapNavActionButton: {
    borderRadius: 999,
    minHeight: 54,
    minWidth: 54,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  floatingMapNavActionArrow: {
    color: theme.textPrimary,
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 30,
    marginTop: -1,
  },
  exitIconWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  exitIconDoor: {
    backgroundColor: theme.textPrimary,
    borderRadius: 2,
    height: 22,
    transform: [{ skewY: '-12deg' }],
    width: 8,
  },
  exitIconFrame: {
    height: 24,
    marginLeft: 3,
    position: 'relative',
    width: 8,
  },
  exitIconFrameTop: {
    backgroundColor: theme.textPrimary,
    height: 3,
    position: 'absolute',
    right: 0,
    top: 0,
    width: 8,
  },
  exitIconFrameSide: {
    backgroundColor: theme.textPrimary,
    height: 18,
    position: 'absolute',
    right: 0,
    top: 3,
    width: 3,
  },
  exitIconFrameBottom: {
    backgroundColor: theme.textPrimary,
    bottom: 0,
    height: 3,
    position: 'absolute',
    right: 0,
    width: 8,
  },
  exitIconArrowRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: 2,
  },
  exitIconArrowShaft: {
    backgroundColor: theme.textPrimary,
    height: 4,
    width: 7,
  },
  exitIconArrowHead: {
    borderBottomColor: 'transparent',
    borderBottomWidth: 5,
    borderLeftColor: theme.textPrimary,
    borderLeftWidth: 8,
    borderTopColor: 'transparent',
    borderTopWidth: 5,
  },
  floatingDashboardButtonText: {
    color: theme.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  bottomNavOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 70,
  },
  bottomNavNativeBackdrop: {
    backgroundColor: 'transparent',
    borderTopColor: 'transparent',
    borderTopWidth: 0,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    shadowColor: '#1c130d',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0,
    shadowRadius: 18,
  },
  bottomNavShell: {
    alignItems: 'center',
    backgroundColor: theme.bgOverlayHeavy,
    borderTopColor: theme.borderStrong,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    overflow: 'hidden',
    paddingHorizontal: 2,
    paddingTop: 40,
    height: 40,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    width: '100%',
  },
  bottomNavGlassHighlight: {
    backgroundColor: theme.borderStrong,
    height: 1,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  bottomNavItem: {
    alignItems: 'center',
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minHeight: 32,
    zIndex: 1,
  },
  bottomNavItemIconWrap: {
    alignItems: 'center',
    borderRadius: 14,
    height: 42,
    justifyContent: 'center',
    width: 46,
  },
  bottomNavItemIconWrapActive: {
    backgroundColor: theme.accentSoft,
  },
  bottomNavItemLabel: {
    color: theme.textMuted,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  bottomNavItemLabelActive: {
    color: theme.textPrimary,
  },
  bottomNavFeedIcon: {
    alignItems: 'center',
    height: 18,
    justifyContent: 'center',
    width: 20,
  },
  bottomNavFeedFrame: {
    borderColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 4,
    borderWidth: 1.8,
    height: 15,
    width: 16,
  },
  bottomNavFeedFrameActive: {
    borderColor: '#fff8f1',
  },
  bottomNavFeedLine: {
    backgroundColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 999,
    height: 1.8,
    position: 'absolute',
    width: 8,
  },
  bottomNavFeedLineTop: {
    top: 5,
  },
  bottomNavFeedLineBottom: {
    top: 9,
  },
  bottomNavMapIcon: {
    alignItems: 'center',
    height: 18,
    justifyContent: 'center',
    width: 20,
  },
  bottomNavMapPanel: {
    borderColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 1.5,
    borderWidth: 2,
    height: 13,
    position: 'absolute',
    transform: [{ rotate: '45deg' }],
    width: 13,
  },
  bottomNavMapPanelMiddle: {
    backgroundColor: 'rgba(255, 248, 241, 0.68)',
    borderWidth: 0,
    height: 6,
    transform: [{ rotate: '45deg' }],
    width: 6,
  },
  bottomNavMapPanelActive: {
    backgroundColor: '#fff8f1',
    borderColor: '#fff8f1',
  },
  bottomNavProfileIcon: {
    alignItems: 'center',
    height: 19,
    justifyContent: 'center',
    width: 20,
  },
  bottomNavProfileHead: {
    backgroundColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 999,
    height: 7,
    width: 7,
  },
  bottomNavProfileBody: {
    borderColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 999,
    borderWidth: 1.8,
    height: 9,
    marginTop: 3,
    width: 15,
  },
  bottomNavMoreIcon: {
    alignItems: 'center',
    gap: 2.5,
    height: 16,
    justifyContent: 'center',
    width: 18,
  },
  bottomNavMoreLine: {
    backgroundColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 999,
    height: 2,
    width: 14,
  },
  bottomNavPlusIcon: {
    alignItems: 'center',
    height: 18,
    justifyContent: 'center',
    width: 18,
  },
  bottomNavPlusLineHorizontal: {
    backgroundColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 999,
    height: 2.2,
    width: 14,
  },
  bottomNavPlusLineVertical: {
    backgroundColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 999,
    height: 14,
    position: 'absolute',
    width: 2.2,
  },
  bottomNavBusinessIcon: {
    alignItems: 'center',
    height: 19,
    justifyContent: 'center',
    width: 20,
  },
  bottomNavBusinessHandle: {
    borderColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 4,
    borderWidth: 1.6,
    height: 5,
    width: 9,
  },
  bottomNavBusinessBody: {
    borderColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 4,
    borderWidth: 1.8,
    height: 10,
    marginTop: 2,
    width: 16,
  },
  bottomNavIconFillActive: {
    backgroundColor: '#fff8f1',
  },
  bottomNavIconStrokeActive: {
    backgroundColor: '#fff8f1',
    borderColor: '#fff8f1',
  },
  screenHeaderBar: {
    alignSelf: 'stretch',
    backgroundColor: theme.bgOverlayHeavy,
    borderBottomColor: theme.borderStrong,
    borderBottomWidth: 1,
    borderLeftWidth: 0,
    borderRadius: 0,
    borderRightWidth: 0,
    borderTopColor: theme.borderStrong,
    borderTopWidth: 1,
    marginHorizontal: -18,
    marginBottom: 14,
    marginTop: 0,
    minHeight: 96,
    paddingHorizontal: 0,
    paddingTop: 40,
    paddingBottom: 12,
  },
  screenHeaderBarSingle: {
    alignItems: 'flex-start',
    paddingHorizontal: 16,
  },
  screenHeaderBarRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 40,
    paddingHorizontal: 16,
  },
  guestShellChrome: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 80,
  },
  keyboardAvoidingFill: {
    flex: 1,
  },
  createProfileScrollContent: {
    paddingBottom: 140,
  },
} as const;

