// Authentication, profile flow, and business-claim form styles.
export const authStyles = {
  authPortalButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  authPortalButtonActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#9e5b49',
  },
  authPortalButtonText: {
    color: '#5d4637',
    fontSize: 15,
    fontWeight: '700',
  },
  authPortalButtonTextActive: {
    color: '#f4fffe',
  },
  authScreen: {
    flex: 1,
  },
  authScrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 20,
  },
  authFormStack: {
    alignSelf: 'center',
    gap: 14,
    marginTop: 18,
    maxWidth: 420,
    width: '100%',
  },
  authHero: {
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 8,
    paddingHorizontal: 12,
  },
  authLinkButton: {
    alignSelf: 'center',
    marginTop: 12,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  authRecoveryRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  authRecoveryButton: {
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  authRecoveryButtonText: {
    color: '#9e5b49',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  authRecoveryPanel: {
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  authRecoveryPanelActions: {
    gap: 10,
  },
  authRecoveryDismissButton: {
    alignSelf: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  authRecoveryDismissText: {
    color: '#9e5b49',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  authLinkText: {
    color: '#9e5b49',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  profileScreen: {
    flex: 1,
  },
  profileScreenLandscape: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  profileScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 132,
  },
  profileCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginTop: 12,
    padding: 18,
  },
  profileIntroText: {
    color: '#6c5443',
    fontSize: 14,
    lineHeight: 20,
  },
  profileSuccessBanner: {
    backgroundColor: '#f5ebe2',
    borderColor: '#dfc3af',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  profileSuccessText: {
    color: '#8d6042',
    fontSize: 13,
    fontWeight: '700',
  },
  profileFormSection: {
    gap: 10,
  },
  profileFieldLabel: {
    color: '#402214',
    fontSize: 13,
    fontWeight: '700',
  },
  profileInput: {
    backgroundColor: '#f8efe3',
    borderColor: '#ead6bf',
    borderRadius: 14,
    borderWidth: 1,
    color: '#2d221a',
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  passwordFieldRow: {
    justifyContent: 'center',
    position: 'relative',
  },
  passwordFieldInput: {
    paddingRight: 48,
  },
  passwordToggleButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 40,
    position: 'absolute',
    right: 4,
    top: 4,
  },
  passwordEyeIcon: {
    alignItems: 'center',
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  passwordEyeOutline: {
    alignItems: 'center',
    borderColor: '#9e5b49',
    borderRadius: 999,
    borderWidth: 1.6,
    height: 12,
    justifyContent: 'center',
    width: 18,
  },
  passwordEyePupil: {
    backgroundColor: '#9e5b49',
    borderRadius: 999,
    height: 4,
    width: 4,
  },
  passwordEyeSlash: {
    backgroundColor: '#9e5b49',
    borderRadius: 999,
    height: 1.8,
    position: 'absolute',
    transform: [{ rotate: '-35deg' }],
    width: 20,
  },
  compactDropdownWrap: {
    gap: 6,
  },
  compactDropdownButton: {
    backgroundColor: '#f8efe3',
    borderColor: '#ead6bf',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  compactDropdownButtonOpen: {
    borderColor: '#9e5b49',
  },
  compactDropdownText: {
    color: '#2d221a',
    fontSize: 14,
    lineHeight: 18,
  },
  compactDropdownPlaceholder: {
    color: '#8a705d',
  },
  compactDropdownCaret: {
    color: '#6c5443',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 12,
  },
  compactDropdownMenu: {
    backgroundColor: '#fffaf4',
    borderColor: '#ead6bf',
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  compactDropdownOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  compactDropdownOptionSelected: {
    backgroundColor: '#f5ebe2',
  },
  compactDropdownOptionText: {
    color: '#2d221a',
    fontSize: 14,
    lineHeight: 18,
  },
  compactDropdownOptionTextSelected: {
    color: '#8d6042',
    fontWeight: '700',
  },
  profileSupportText: {
    color: '#7d614f',
    fontSize: 12,
    lineHeight: 18,
    marginTop: -2,
  },
  verificationCodeInput: {
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 8,
    textAlign: 'center',
  },
  verificationCountdownText: {
    color: '#8d6042',
    fontSize: 13,
    fontWeight: '700',
  },
  supportMessageInput: {
    minHeight: 144,
    paddingTop: 12,
  },
  claimResultsList: {
    gap: 12,
    marginTop: 8,
  },
  claimResultCard: {
    backgroundColor: '#fff3e5',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  claimBusinessHint: {
    color: '#6c5443',
    fontSize: 13,
    lineHeight: 18,
  },
  claimLocationList: {
    gap: 8,
    marginTop: 6,
  },
  claimLocationButton: {
    backgroundColor: '#fffaf4',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  claimLocationButtonTitle: {
    color: '#402214',
    fontSize: 13,
    fontWeight: '700',
  },
  claimLocationButtonText: {
    color: '#5f4b3d',
    fontSize: 13,
    lineHeight: 18,
  },
  profileTextarea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
} as const;

