import { StyleSheet } from 'react-native';
import { theme } from './theme';

// Browse and map surfaces, filters, chips, result cards, and marker styles.
export const browseStyles = {
  browseHeaderCard: {
    backgroundColor: 'rgba(20, 20, 24, 0.94)',
    borderColor: theme.borderStrong,
    borderRadius: 28,
    borderWidth: 1,
    gap: 10,
    padding: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.22,
    shadowRadius: 24,
    elevation: 18,
  },
  browseHeaderCardLandscape: {
    alignSelf: 'center',
    gap: 6,
    maxWidth: 620,
    padding: 10,
  },
  toolbarRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
  },
  toolbarRowLeading: {
    justifyContent: 'flex-start',
  },
  toolbarActionsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 4,
    justifyContent: 'flex-start',
  },
  toolbarActionsRowFill: {
    flex: 1,
  },
  toolbarActionsRowWithDashboard: {
    flex: 1,
    minWidth: 0,
  },
  toolbarRowLandscape: {
    minHeight: 36,
  },
  browseModeContentLayer: {
    flex: 1,
  },
  browseContentStage: {
    flex: 1,
    position: 'relative',
  },
  browseContentFill: {
    ...StyleSheet.absoluteFillObject,
  },
  appTitle: {
    color: theme.textPrimary,
    fontSize: 24,
    fontWeight: '800',
  },
  controlsTitleLandscape: {
    fontSize: 20,
  },
  mapScreen: {
    flex: 1,
  },
  mapModeContentLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  mapThemeTransitionLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  mapBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  mapOverlayLayer: {
    ...StyleSheet.absoluteFillObject,
    gap: 12,
    justifyContent: 'flex-start',
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 0,
  },
  mapOverlayContentLayer: {
    gap: 12,
  },
  mapTopPanel: {
    backgroundColor: 'rgba(20, 20, 24, 0.9)',
    borderColor: theme.borderStrong,
    borderRadius: 28,
    borderWidth: 1,
    gap: 10,
    padding: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 16,
  },
  mapTopPanelLight: {
    backgroundColor: 'rgba(248, 251, 247, 0.96)',
    borderColor: 'rgba(38, 53, 44, 0.18)',
    shadowColor: '#233329',
    shadowOpacity: 0.14,
  },
  mapTopPanelLandscape: {
    alignSelf: 'center',
    gap: 6,
    maxWidth: 620,
    padding: 10,
  },
  mapLoadingOverlay: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(18, 22, 30, 0.96)',
    borderRadius: 20,
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  mapPreviewCard: {
    backgroundColor: 'rgba(23, 28, 37, 0.97)',
    borderColor: theme.border,
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  mapPreviewCardLandscape: {
    alignSelf: 'center',
    gap: 10,
    maxWidth: 320,
    padding: 12,
    width: '100%',
  },
  mapResultsCard: {
    backgroundColor: 'rgba(23, 28, 37, 0.97)',
    borderColor: theme.border,
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    minHeight: 0,
    padding: 16,
  },
  mapResultsCardLight: {
    backgroundColor: 'rgba(248, 251, 247, 0.98)',
    borderColor: 'rgba(38, 53, 44, 0.2)',
  },
  mapResultsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mapResultsHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  mapResultsHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginLeft: 12,
  },
  mapResultsTitle: {
    color: theme.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  mapResultsTitleLight: {
    color: '#26352c',
  },
  mapResultsMeta: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  mapResultsMetaLight: {
    color: '#68756b',
  },
  mapResultsList: {
    gap: 10,
    paddingRight: 4,
  },
  mapResultsScroll: {
    minHeight: 0,
  },
  mapResultsMoreButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  mapResultsMoreButtonLoadingContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  mapResultsMoreButtonText: {
    color: theme.accentBlue,
    fontSize: 13,
    fontWeight: '800',
  },
  mapResultsMoreButtonTextLight: {
    color: '#1f5f5b',
  },
  mapResultsCollapseButton: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 12,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  mapResultsCollapseButtonLight: {
    backgroundColor: '#e8eee8',
    borderColor: 'rgba(38, 53, 44, 0.16)',
  },
  mapResultsChevronIcon: {
    height: 14,
    position: 'relative',
    width: 16,
  },
  mapResultsChevronLine: {
    backgroundColor: theme.textPrimary,
    borderRadius: 999,
    height: 2.5,
    position: 'absolute',
    top: 6,
    width: 8,
  },
  mapResultsChevronLineLight: {
    backgroundColor: '#26352c',
  },
  mapResultsChevronLineLeft: {
    left: 0.5,
    transformOrigin: 'right center',
  },
  mapResultsChevronLineRight: {
    right: 0.5,
    transformOrigin: 'left center',
  },
  mapResultsContent: {
    gap: 12,
    minHeight: 0,
    overflow: 'hidden',
  },
  mapResultRow: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  mapResultRowLight: {
    backgroundColor: 'rgba(237, 242, 237, 0.96)',
    borderColor: 'rgba(38, 53, 44, 0.14)',
  },
  mapResultCopy: {
    flex: 1,
    gap: 4,
  },
  mapResultTitle: {
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  mapResultTitleLight: {
    color: '#26352c',
  },
  mapResultMeta: {
    color: theme.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  mapResultMetaLight: {
    color: '#52645a',
  },
  mapResultAction: {
    color: theme.accentBlue,
    fontSize: 12,
    fontWeight: '800',
  },
  mapResultActionLight: {
    color: '#d94f48',
  },
  mapResultEmptyText: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  mapResultEmptyTextLight: {
    color: '#52645a',
  },
  mapPreviewHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mapPreviewCopy: {
    flex: 1,
    gap: 4,
    paddingRight: 12,
  },
  mapPreviewTitle: {
    color: theme.textPrimary,
    fontSize: 19,
    fontWeight: '800',
  },
  mapPreviewTitleLandscape: {
    fontSize: 16,
  },
  mapPreviewMeta: {
    color: theme.textSecondary,
    fontSize: 14,
    fontWeight: '600',
  },
  mapPreviewMetaLandscape: {
    fontSize: 12,
  },
  mapPreviewActions: {
    flexDirection: 'row',
    gap: 8,
  },
  mapPreviewDetails: {
    gap: 4,
    marginTop: -2,
  },
  mapPreviewDetailText: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  mapPreviewDetailTextLandscape: {
    fontSize: 12,
    lineHeight: 16,
  },
  mapPreviewIconButton: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  mapPreviewIconButtonLandscape: {
    height: 30,
    width: 30,
  },
  mapPreviewIconText: {
    color: theme.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  mapPreviewIconTextLandscape: {
    fontSize: 15,
  },
  mapPreviewGallery: {
    gap: 12,
  },
  mapPreviewGalleryLandscape: {
    gap: 8,
  },
  mapPreviewImage: {
    backgroundColor: theme.bgMuted,
    borderRadius: 18,
    height: 180,
    width: 250,
  },
  mapPreviewImageLandscape: {
    borderRadius: 14,
    height: 110,
    width: 180,
  },
  mapPreviewEmptyState: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderWidth: 1,
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 140,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  mapPreviewEmptyStateLandscape: {
    minHeight: 92,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  mapPreviewEmptyText: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  mapPreviewEmptyTextLandscape: {
    fontSize: 12,
    lineHeight: 16,
  },
  mapAppTitle: {
    color: theme.textPrimary,
    fontSize: 24,
    fontWeight: '800',
  },
  mapOverlayText: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  currentHappyHoursLayer: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 60,
  },
  currentHappyHoursSheetFrame: {
    width: '100%',
  },
  currentHappyHoursSheet: {
    alignSelf: 'stretch',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    width: '100%',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 18,
  },
  currentHappyHoursSheetDark: {
    backgroundColor: '#11161b',
    borderColor: '#303840',
  },
  currentHappyHoursSheetLight: {
    backgroundColor: '#f7f7f4',
    borderColor: '#d7d7d2',
  },
  currentHappyHoursSheetExpanded: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomWidth: 0,
    marginHorizontal: 0,
    width: '100%',
  },
  currentHappyHoursSheetHeader: {
    minHeight: 86,
    paddingHorizontal: 14,
    paddingTop: 6,
  },
  currentHappyHoursSheetHandle: {
    alignItems: 'center',
    height: 20,
    justifyContent: 'center',
  },
  currentHappyHoursSheetHandleBar: {
    backgroundColor: '#c7c9c5',
    borderRadius: 999,
    height: 5,
    width: 42,
  },
  currentHappyHoursSheetHandleBarDark: {
    backgroundColor: '#69727b',
  },
  currentHappyHoursSheetHeadingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 56,
    paddingBottom: 8,
  },
  currentHappyHoursSheetHeadingCopy: {
    flex: 1,
    paddingRight: 12,
  },
  currentHappyHoursSheetTitle: {
    color: '#222622',
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
  },
  currentHappyHoursSheetTitleDark: {
    color: '#f6f7f3',
  },
  currentHappyHoursSheetMeta: {
    color: '#70756f',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 2,
  },
  currentHappyHoursSheetMetaDark: {
    color: '#aeb7bb',
  },
  currentHappyHoursSheetClose: {
    alignItems: 'center',
    backgroundColor: '#e8e9e5',
    borderRadius: 999,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  currentHappyHoursSheetCloseDark: {
    backgroundColor: '#2b333b',
  },
  currentHappyHoursTriggerFrame: {
    alignItems: 'stretch',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  currentHappyHoursTrigger: {
    alignItems: 'stretch',
    alignSelf: 'stretch',
    backgroundColor: '#f7f7f4',
    borderColor: '#d7d7d2',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 1,
    borderBottomWidth: 0,
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 10,
    width: '100%',
  },
  currentHappyHoursTriggerDark: {
    backgroundColor: '#11161b',
    borderColor: '#303840',
  },
  currentHappyHoursTriggerLight: {
    backgroundColor: '#f7f7f4',
    borderColor: '#d7d7d2',
  },
  currentHappyHoursTriggerDot: {
    backgroundColor: '#ff5e59',
    borderRadius: 999,
    height: 7,
    width: 7,
  },
  currentHappyHoursTriggerHeadingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    minHeight: 48,
    paddingHorizontal: 16,
  },
  currentHappyHoursTriggerTitle: {
    color: '#222622',
    fontSize: 14,
    fontWeight: '800',
  },
  currentHappyHoursTriggerTitleDark: {
    color: '#f6f7f3',
  },
  currentHappyHoursSheetContent: {
    flex: 1,
    minHeight: 0,
  },
  currentHappyHoursSheetList: {
    gap: 12,
    paddingBottom: 30,
    paddingHorizontal: 14,
  },
  currentHappyHoursDealCard: {
    backgroundColor: '#ffffff',
    borderColor: '#deded9',
    borderRadius: 15,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
  },
  currentHappyHoursDealCardContent: {
    alignSelf: 'stretch',
    width: '100%',
  },
  currentHappyHoursDealCardDark: {
    backgroundColor: '#20272e',
    borderColor: '#39434c',
  },
  currentHappyHoursDealImageFrame: {
    backgroundColor: '#d8e3d3',
    height: 132,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  currentHappyHoursDealImage: {
    height: '100%',
    width: '100%',
  },
  currentHappyHoursDealImagePlaceholder: {
    alignItems: 'center',
    backgroundColor: '#dfe9db',
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  currentHappyHoursDealImagePlaceholderDark: {
    backgroundColor: '#45524c',
  },
  currentHappyHoursDealImageShade: {
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
    bottom: 0,
    height: 72,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  currentHappyHoursDealImageCopy: {
    bottom: 10,
    left: 12,
    position: 'absolute',
    right: 68,
  },
  currentHappyHoursDealName: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  currentHappyHoursDealMeta: {
    color: 'rgba(255, 255, 255, 0.84)',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  currentHappyHoursDealDistance: {
    backgroundColor: 'rgba(23, 25, 24, 0.72)',
    borderRadius: 999,
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 4,
    position: 'absolute',
    left: 10,
    top: 10,
  },
  currentHappyHoursDealFavorite: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 10,
    top: 9,
    width: 28,
  },
  currentHappyHoursDealCalendar: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 78,
    top: 9,
    width: 28,
  },
  currentHappyHoursDealCalendarWithoutFavorite: {
    right: 44,
  },
  currentHappyHoursDealShare: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 44,
    top: 9,
    width: 28,
  },
  currentHappyHoursDealShareWithoutFavorite: {
    right: 10,
  },
  currentHappyHoursDealBody: {
    alignItems: 'flex-start',
    paddingHorizontal: 13,
    paddingVertical: 12,
    width: '100%',
  },
  currentHappyHoursDealLineBlock: {
    marginBottom: 2,
    width: '100%',
  },
  currentHappyHoursDealLine: {
    color: '#252725',
    fontSize: 15,
    lineHeight: 20,
    textAlign: 'left',
  },
  currentHappyHoursDealLineDark: {
    color: '#f1f3ef',
  },
  currentHappyHoursDealFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 10,
    width: '100%',
  },
  currentHappyHoursDealTimeChip: {
    borderColor: '#ff5e59',
    borderRadius: 5,
    borderWidth: 1,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  currentHappyHoursDealTimeText: {
    color: '#ff514c',
    fontSize: 11,
    fontWeight: '600',
  },
  mapOfflineBanner: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(35, 31, 22, 0.94)',
    borderColor: 'rgba(247, 200, 115, 0.45)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  mapOfflineBannerText: {
    color: '#f7c873',
    fontSize: 12,
    fontWeight: '700',
  },
  mapLastKnownLocationText: {
    color: '#f7c873',
    fontSize: 13,
    fontWeight: '700',
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  searchRowLandscape: {
    alignItems: 'stretch',
    gap: 6,
  },
  searchInputShell: {
    alignItems: 'center',
    backgroundColor: '#1b1d23',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    borderWidth: 1,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 10,
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 54,
    paddingHorizontal: 12,
  },
  searchInputShellLandscape: {
    minHeight: 46,
    paddingHorizontal: 10,
  },
  searchInputShellOverlay: {
    backgroundColor: 'rgba(24, 25, 31, 0.94)',
  },
  searchInputShellOverlayLight: {
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    borderColor: 'rgba(38, 53, 44, 0.14)',
    shadowColor: '#233329',
    shadowOpacity: 0.12,
  },
  searchInputShellCurtain: {
    minHeight: 54,
  },
  searchCurtainToggleInline: {
    alignItems: 'center',
    bottom: -4,
    height: 20,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -16,
    position: 'absolute',
    width: 32,
    zIndex: 12,
  },
  searchCurtainChevronIcon: {
    height: 16,
  },
  searchCurtainChevronLine: {
    backgroundColor: '#f5f7fb',
  },
  searchCurtainChevronLineLight: {
    backgroundColor: '#26352c',
  },
  searchInputIconBadge: {
    alignItems: 'center',
    backgroundColor: '#2a2d36',
    borderColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  searchInputIconBadgeLight: {
    backgroundColor: '#e9efe9',
    borderColor: 'rgba(38, 53, 44, 0.12)',
  },
  searchInput: {
    color: '#f5f7fb',
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
    letterSpacing: 0,
    paddingVertical: 0,
  },
  searchInputLight: {
    color: '#26352c',
  },
  searchClearButton: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  filtersToggleButton: {
    alignItems: 'center',
    backgroundColor: '#1f2026',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  filtersToggleButtonInline: {
    minHeight: 44,
    paddingHorizontal: 12,
  },
  filtersToggleButtonPressable: {
    borderRadius: 18,
  },
  filtersToggleButtonLandscape: {
    minHeight: 44,
    paddingHorizontal: 12,
  },
  filtersToggleButtonActive: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.borderStrong,
  },
  filtersToggleText: {
    color: '#f5f7fb',
    fontSize: 14,
    fontWeight: '600',
  },
  filtersToggleTextInline: {
    fontSize: 14,
  },
  filtersToggleTextActive: {
    color: '#ffffff',
  },
  filtersToggleIconWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  browseStatsRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    paddingTop: 2,
    justifyContent: 'space-between',
  },
  browseStatsRowLandscape: {
    gap: 6,
  },
  browseStatsText: {
    color: '#f5f7fb',
    fontSize: 13,
    fontWeight: '800',
  },
  browseStatsSubtleText: {
    color: '#8c92a3',
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'right',
  },
  browseStatsTextLight: {
    color: '#26352c',
  },
  browseStatsSubtleTextLight: {
    color: '#68756b',
  },
  filtersPanel: {
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    borderTopWidth: 1,
    gap: 12,
    marginTop: 6,
    minHeight: 0,
  },
  filtersPanelLight: {
    borderTopColor: 'rgba(38, 53, 44, 0.14)',
  },
  filtersPanelLandscape: {
    gap: 8,
    paddingTop: 8,
  },
  filtersPanelScrollContent: {
    gap: 12,
    paddingTop: 5,
    paddingBottom: 4,
    paddingRight: 4,
  },
  browseSectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  browseSectionTitle: {
    color: '#b7bdca',
    fontSize: 14,
    fontWeight: '800',
  },
  browseSectionMeta: {
    color: '#7f8597',
    fontSize: 12,
    fontWeight: '600',
  },
  browseSectionTitleLight: {
    color: '#3d4c42',
  },
  browseSectionMetaLight: {
    color: '#68756b',
  },
  browseSectionAction: {
    color: '#ff7a68',
    fontSize: 12,
    fontWeight: '700',
  },
  reloadButton: {
    alignItems: 'center',
    backgroundColor: '#2a2d36',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  reloadButtonLight: {
    backgroundColor: '#edf2ed',
    borderColor: 'rgba(38, 53, 44, 0.14)',
  },
  secondaryToolbarButton: {
    backgroundColor: '#1f2026',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  mapResultsMoreButtonLight: {
    backgroundColor: '#edf2ed',
    borderColor: 'rgba(38, 53, 44, 0.16)',
  },
  secondaryToolbarButtonLight: {
    backgroundColor: '#edf2ed',
    borderColor: 'rgba(38, 53, 44, 0.14)',
  },
  secondaryToolbarButtonText: {
    color: '#f5f7fb',
    fontSize: 13,
    fontWeight: '700',
  },
  secondaryToolbarButtonTextLight: {
    color: '#26352c',
  },
  toolbarArrowButton: {
    alignItems: 'center',
    backgroundColor: '#1f2026',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  toolbarArrowButtonLight: {
    backgroundColor: '#edf2ed',
    borderColor: 'rgba(38, 53, 44, 0.14)',
  },
  toolbarArrowButtonText: {
    color: '#f5f7fb',
    fontSize: 22,
    fontWeight: '700',
  },
  toolbarArrowButtonTextLight: {
    color: '#26352c',
  },
  reloadButtonText: {
    color: '#f4fffe',
    fontSize: 22,
    fontWeight: '700',
  },
  mapThemeToggleButton: {
    alignItems: 'center',
    borderRadius: 16,
    justifyContent: 'center',
    height: 44,
    overflow: 'hidden',
    width: 44,
  },
  mapThemeToggleButtonFill: {
    alignItems: 'center',
    backgroundColor: '#1f2026',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    borderWidth: 1,
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  mapThemeToggleButtonActive: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.borderStrong,
  },
  mapThemeToggleButtonText: {
    color: '#d3d8e3',
    fontSize: 18,
    fontWeight: '800',
  },
  mapThemeToggleButtonTextLayer: {
    position: 'absolute',
  },
  mapThemeToggleButtonTextActive: {
    color: '#f5f7fb',
  },
  filterRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  modeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  modeSwitcherDock: {
    alignItems: 'flex-start',
    marginTop: 10,
  },
  modeSwitcherDockOverlay: {
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  modeSwitcherTrack: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.borderStrong,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    height: 44,
    overflow: 'hidden',
    padding: 4,
    position: 'relative',
  },
  modeSwitcherTrackOverlay: {
    backgroundColor: 'rgba(22, 26, 34, 0.98)',
  },
  modeSwitcherTrackOverlayLight: {
    backgroundColor: '#e8eee8',
    borderColor: 'rgba(38, 53, 44, 0.16)',
  },
  modeLockBadge: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 116,
    paddingHorizontal: 16,
  },
  modeLockBadgeText: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  modeSwitcherThumb: {
    backgroundColor: theme.accent,
    borderRadius: 999,
    bottom: 4,
    left: 4,
    position: 'absolute',
    top: 4,
  },
  modeSwitchOption: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  modeSwitchOptionText: {
    color: theme.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  modeSwitchOptionTextActive: {
    color: '#f4fffe',
  },
  filterChip: {
    alignSelf: 'flex-start',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1.5,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  filterChipActive: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.borderStrong,
  },
  filterChipText: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: theme.textPrimary,
  },
  overlayChip: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(22, 26, 34, 0.98)',
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1.5,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  overlayChipActive: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.borderStrong,
  },
  overlayChipLight: {
    alignSelf: 'flex-start',
    backgroundColor: '#edf2ed',
    borderColor: 'rgba(38, 53, 44, 0.14)',
    borderRadius: 999,
    borderWidth: 1.5,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  overlayChipActiveLight: {
    alignSelf: 'flex-start',
    backgroundColor: '#ff695c',
    borderColor: '#ff695c',
    borderRadius: 999,
    borderWidth: 1.5,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  overlayChipText: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  overlayChipTextLight: {
    color: '#26352c',
    fontSize: 13,
    fontWeight: '600',
  },
  overlayChipTextActive: {
    color: theme.textPrimary,
  },
  overlayChipTextActiveLight: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  venueFilterRow: {
    alignItems: 'center',
    gap: 8,
    paddingRight: 16,
  },
  venueFilterChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 8,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  venueFilterChipActive: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.borderStrong,
  },
  venueFilterChipLight: {
    backgroundColor: '#edf2ed',
    borderColor: 'rgba(38, 53, 44, 0.14)',
  },
  venueFilterChipActiveLight: {
    backgroundColor: '#ff695c',
    borderColor: '#ff695c',
  },
  mapMarkerMotion: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 32,
  },
  mapMarker: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 32,
  },
  mapMarkerLayer: {
    left: 0,
    position: 'absolute',
    top: 0,
  },
  mapMarkerCore: {
    borderRadius: 999,
    borderWidth: 1.5,
    position: 'absolute',
  },
  mapMarkerActive: {
    elevation: 6,
    shadowColor: '#1f160f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.32,
    shadowRadius: 5,
  },
  mapMarkerIcon: {
    alignItems: 'center',
    height: 16,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    top: 5,
    width: 32,
  },
  mapMarkerIconGlyph: {
    includeFontPadding: false,
    textAlign: 'center',
  },
  mapMarkerHighlight: {
    backgroundColor: 'rgba(255, 250, 244, 0.78)',
    borderRadius: 999,
    height: 2,
    left: 9,
    position: 'absolute',
    top: 8,
    transform: [{ rotate: '-28deg' }],
    width: 6,
  },
  listContent: {
    gap: 12,
    paddingBottom: 142,
  },
  listContentLandscape: {
    paddingBottom: 148,
  },
  placeCardColumn: {
    gap: 12,
  },
  placeCard: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 22,
    borderWidth: 1,
    padding: 18,
  },
  placeCardImage: {
    borderRadius: 16,
    height: 168,
    marginBottom: 14,
    width: '100%',
  },
  placeCardLandscape: {
    flex: 1,
  },
  placeCity: {
    color: theme.accentStrong,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  placeTitle: {
    color: theme.textPrimary,
    fontSize: 20,
    fontWeight: '800',
    marginTop: 4,
  },
  placeMeta: {
    color: theme.textSecondary,
    fontSize: 14,
    marginTop: 4,
  },
  placeAddress: {
    color: theme.textMuted,
    fontSize: 13,
    marginTop: 8,
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 40,
  },
  centerStateText: {
    color: '#6f5947',
    marginTop: 10,
  },
} as const;

