import { StyleSheet } from 'react-native';

// Browse and map surfaces, filters, chips, result cards, and marker styles.
export const browseStyles = {
  browseHeaderCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  browseHeaderCardLandscape: {
    alignSelf: 'center',
    gap: 8,
    maxWidth: 620,
    padding: 12,
  },
  toolbarRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
  },
  toolbarRowLeading: {
    justifyContent: 'flex-start',
  },
  toolbarActionsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 4,
    justifyContent: 'flex-start',
  },
  toolbarActionsRowFill: {
    flex: 1,
  },
  toolbarActionsRowWithDashboard: {
    flex: 1,
    minWidth: 0,
  },
  toolbarRowLandscape: {
    minHeight: 36,
  },
  browseModeContentLayer: {
    flex: 1,
  },
  browseContentStage: {
    flex: 1,
    position: 'relative',
  },
  browseContentFill: {
    ...StyleSheet.absoluteFillObject,
  },
  appTitle: {
    color: '#2d221a',
    fontSize: 24,
    fontWeight: '800',
  },
  controlsTitleLandscape: {
    fontSize: 20,
  },
  mapScreen: {
    flex: 1,
  },
  mapModeContentLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  mapThemeTransitionLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  mapBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  mapOverlayLayer: {
    ...StyleSheet.absoluteFillObject,
    gap: 12,
    justifyContent: 'flex-start',
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 0,
  },
  mapOverlayContentLayer: {
    gap: 12,
  },
  mapTopPanel: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  mapTopPanelLandscape: {
    alignSelf: 'center',
    gap: 8,
    maxWidth: 620,
    padding: 12,
  },
  mapLoadingOverlay: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 250, 244, 0.94)',
    borderRadius: 20,
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  mapPreviewCard: {
    backgroundColor: 'rgba(255, 250, 244, 0.97)',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  mapPreviewCardLandscape: {
    alignSelf: 'center',
    gap: 10,
    maxWidth: 320,
    padding: 12,
    width: '100%',
  },
  mapResultsCard: {
    backgroundColor: 'rgba(255, 250, 244, 0.97)',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    minHeight: 0,
    padding: 16,
  },
  mapResultsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mapResultsHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  mapResultsHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginLeft: 12,
  },
  mapResultsTitle: {
    color: '#2d221a',
    fontSize: 18,
    fontWeight: '800',
  },
  mapResultsMeta: {
    color: '#7b6350',
    fontSize: 12,
    fontWeight: '700',
  },
  mapResultsList: {
    gap: 10,
    paddingRight: 4,
  },
  mapResultsScroll: {
    minHeight: 0,
  },
  mapResultsMoreButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  mapResultsMoreButtonLoadingContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  mapResultsMoreButtonText: {
    color: '#1f5f5b',
    fontSize: 13,
    fontWeight: '800',
  },
  mapResultsCollapseButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 12,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  mapResultsChevronIcon: {
    height: 14,
    position: 'relative',
    width: 16,
  },
  mapResultsChevronLine: {
    backgroundColor: '#5d4637',
    borderRadius: 999,
    height: 2.5,
    position: 'absolute',
    top: 6,
    width: 8,
  },
  mapResultsChevronLineLeft: {
    left: 0.5,
    transformOrigin: 'right center',
  },
  mapResultsChevronLineRight: {
    right: 0.5,
    transformOrigin: 'left center',
  },
  mapResultsContent: {
    gap: 12,
    minHeight: 0,
    overflow: 'hidden',
  },
  mapResultRow: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  mapResultCopy: {
    flex: 1,
    gap: 4,
  },
  mapResultTitle: {
    color: '#2d221a',
    fontSize: 15,
    fontWeight: '800',
  },
  mapResultMeta: {
    color: '#725947',
    fontSize: 12,
    lineHeight: 17,
  },
  mapResultAction: {
    color: '#1f5f5b',
    fontSize: 12,
    fontWeight: '800',
  },
  mapResultEmptyText: {
    color: '#725947',
    fontSize: 13,
    lineHeight: 18,
  },
  mapPreviewHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mapPreviewCopy: {
    flex: 1,
    gap: 4,
    paddingRight: 12,
  },
  mapPreviewTitle: {
    color: '#2d221a',
    fontSize: 19,
    fontWeight: '800',
  },
  mapPreviewTitleLandscape: {
    fontSize: 16,
  },
  mapPreviewMeta: {
    color: '#6c5443',
    fontSize: 14,
    fontWeight: '600',
  },
  mapPreviewMetaLandscape: {
    fontSize: 12,
  },
  mapPreviewActions: {
    flexDirection: 'row',
    gap: 8,
  },
  mapPreviewDetails: {
    gap: 4,
    marginTop: -2,
  },
  mapPreviewDetailText: {
    color: '#725947',
    fontSize: 13,
    lineHeight: 18,
  },
  mapPreviewDetailTextLandscape: {
    fontSize: 12,
    lineHeight: 16,
  },
  mapPreviewIconButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  mapPreviewIconButtonLandscape: {
    height: 30,
    width: 30,
  },
  mapPreviewIconText: {
    color: '#402214',
    fontSize: 18,
    fontWeight: '800',
  },
  mapPreviewIconTextLandscape: {
    fontSize: 15,
  },
  mapPreviewGallery: {
    gap: 12,
  },
  mapPreviewGalleryLandscape: {
    gap: 8,
  },
  mapPreviewImage: {
    backgroundColor: '#ecdac7',
    borderRadius: 18,
    height: 180,
    width: 250,
  },
  mapPreviewImageLandscape: {
    borderRadius: 14,
    height: 110,
    width: 180,
  },
  mapPreviewEmptyState: {
    alignItems: 'center',
    backgroundColor: '#f6eee4',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 140,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  mapPreviewEmptyStateLandscape: {
    minHeight: 92,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  mapPreviewEmptyText: {
    color: '#7d614f',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  mapPreviewEmptyTextLandscape: {
    fontSize: 12,
    lineHeight: 16,
  },
  mapAppTitle: {
    color: '#2d221a',
    fontSize: 24,
    fontWeight: '800',
  },
  mapOverlayText: {
    color: '#6c5443',
    fontSize: 13,
    lineHeight: 18,
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  searchRowLandscape: {
    alignItems: 'stretch',
    gap: 6,
  },
  searchInputShell: {
    alignItems: 'center',
    backgroundColor: '#f8efe3',
    borderColor: '#ead6bf',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  searchInputShellLandscape: {
    minHeight: 42,
    paddingHorizontal: 10,
  },
  searchInputShellOverlay: {
    backgroundColor: '#f8efe3',
  },
  searchInputShellCurtain: {
    minHeight: 52,
  },
  searchCurtainToggleInline: {
    alignItems: 'center',
    bottom: 4,
    height: 20,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -16,
    position: 'absolute',
    width: 32,
    zIndex: 12,
  },
  searchInputIcon: {
    color: '#9a6440',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  searchInput: {
    color: '#2d221a',
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    paddingVertical: 0,
  },
  searchClearButton: {
    paddingVertical: 6,
  },
  searchClearButtonText: {
    color: '#9e5b49',
    fontSize: 13,
    fontWeight: '700',
  },
  filtersToggleButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 14,
  },
  filtersToggleButtonInline: {
    minHeight: 44,
    paddingHorizontal: 10,
  },
  filtersToggleButtonPressable: {
    borderRadius: 16,
  },
  filtersToggleButtonLandscape: {
    minHeight: 42,
    paddingHorizontal: 10,
  },
  filtersToggleButtonActive: {
    backgroundColor: '#402214',
    borderColor: '#402214',
  },
  filtersToggleText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '700',
  },
  filtersToggleTextInline: {
    fontSize: 12,
  },
  filtersToggleTextActive: {
    color: '#fff7ef',
  },
  browseStatsRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    paddingTop: 5,
    justifyContent: 'space-between',
  },
  browseStatsRowLandscape: {
    gap: 6,
  },
  browseStatsText: {
    color: '#2d221a',
    fontSize: 14,
    fontWeight: '800',
  },
  browseStatsSubtleText: {
    color: '#7b6350',
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
  },
  filtersPanel: {
    borderTopColor: '#efd8bd',
    borderTopWidth: 1,
    gap: 12,
    marginTop: 8,    
    minHeight: 0,
  },
  filtersPanelLandscape: {
    gap: 8,    
    paddingTop: 8,
  },
  filtersPanelScrollContent: {
    gap: 12,
    paddingTop: 5,
    paddingBottom: 4,
    paddingRight: 4,
  },
  browseSectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  browseSectionTitle: {
    color: '#8f6438',
    fontSize: 14,
    fontWeight: '800',
  },
  browseSectionMeta: {
    color: '#8f725d',
    fontSize: 12,
    fontWeight: '600',
  },
  browseSectionAction: {
    color: '#9e5b49',
    fontSize: 12,
    fontWeight: '700',
  },
  reloadButton: {
    alignItems: 'center',
    backgroundColor: '#9e5b49',
    borderRadius: 14,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  secondaryToolbarButton: {
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  secondaryToolbarButtonText: {
    color: '#5d4637',
    fontSize: 14,
    fontWeight: '700',
  },
  toolbarArrowButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  toolbarArrowButtonText: {
    color: '#5d4637',
    fontSize: 22,
    fontWeight: '700',
  },
  reloadButtonText: {
    color: '#f4fffe',
    fontSize: 22,
    fontWeight: '700',
  },
  mapThemeToggleButton: {
    alignItems: 'center',
    borderRadius: 14,
    justifyContent: 'center',
    height: 44,
    overflow: 'hidden',
    width: 44,
  },
  mapThemeToggleButtonFill: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  mapThemeToggleButtonActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#9e5b49',
  },
  mapThemeToggleButtonText: {
    color: '#5d4637',
    fontSize: 18,
    fontWeight: '800',
  },
  mapThemeToggleButtonTextLayer: {
    position: 'absolute',
  },
  mapThemeToggleButtonTextActive: {
    color: '#f4fffe',
  },
  filterRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  modeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  modeSwitcherDock: {
    alignItems: 'flex-start',
    marginTop: 10,
  },
  modeSwitcherDockOverlay: {
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  modeSwitcherTrack: {
    backgroundColor: 'rgba(255, 250, 244, 0.96)',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    height: 44,
    overflow: 'hidden',
    padding: 4,
    position: 'relative',
  },
  modeSwitcherTrackOverlay: {
    backgroundColor: 'rgba(255, 247, 239, 0.98)',
  },
  modeLockBadge: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 116,
    paddingHorizontal: 16,
  },
  modeLockBadgeText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '800',
  },
  modeSwitcherThumb: {
    backgroundColor: '#9e5b49',
    borderRadius: 999,
    bottom: 4,
    left: 4,
    position: 'absolute',
    top: 4,
  },
  modeSwitchOption: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  modeSwitchOptionText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '700',
  },
  modeSwitchOptionTextActive: {
    color: '#f4fffe',
  },
  filterChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#cda883',
    borderRadius: 999,
    borderWidth: 1.5,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  filterChipActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#744030',
  },
  filterChipText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: '#fff7ef',
  },
  overlayChip: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 250, 244, 0.96)',
    borderColor: '#cda883',
    borderRadius: 999,
    borderWidth: 1.5,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  overlayChipActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#744030',
  },
  overlayChipText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '600',
  },
  overlayChipTextActive: {
    color: '#fff7ef',
  },
  venueFilterRow: {
    alignItems: 'center',
    gap: 8,
    paddingRight: 16,
  },
  venueFilterChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#cda883',
    borderRadius: 999,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 8,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  venueFilterChipActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#744030',
  },
  venueFilterBadge: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 2,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  venueFilterBadgeText: {
    color: '#fffaf4',
    fontSize: 11,
    fontWeight: '800',
  },
  mapMarker: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 2,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  mapMarkerActive: {
    borderWidth: 3,
    elevation: 4,
    shadowColor: '#1f160f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  mapMarkerText: {
    color: '#fffaf4',
    fontSize: 12,
    fontWeight: '900',
  },
  listContent: {
    gap: 12,
    paddingBottom: 142,
  },
  listContentLandscape: {
    paddingBottom: 148,
  },
  placeCardColumn: {
    gap: 12,
  },
  placeCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 22,
    borderWidth: 1,
    padding: 18,
  },
  placeCardImage: {
    borderRadius: 16,
    height: 168,
    marginBottom: 14,
    width: '100%',
  },
  placeCardLandscape: {
    flex: 1,
  },
  placeCity: {
    color: '#b07a3f',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  placeTitle: {
    color: '#2d221a',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 4,
  },
  placeMeta: {
    color: '#5c5043',
    fontSize: 14,
    marginTop: 4,
  },
  placeAddress: {
    color: '#7d614f',
    fontSize: 13,
    marginTop: 8,
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 40,
  },
  centerStateText: {
    color: '#6f5947',
    marginTop: 10,
  },
} as const;

