import { theme } from './theme';

// Dashboard, settings, notifications, campaigns, and 2FA management styles.
export const dashboardStyles = {
  dashboardMultilineInput: {
    minHeight: 112,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  dashboardScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 132,
  },
  dashboardCard: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginTop: 8,
    padding: 18,
  },
  dashboardShell: {
    gap: 18,
    marginTop: 8,
    paddingBottom: 12,
  },
  dashboardCalloutCard: {
    backgroundColor: theme.bgSoft,
    borderColor: theme.borderStrong,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    marginTop: 18,
    padding: 14,
  },
  dashboardVerifiedCard: {
    backgroundColor: theme.successSoft,
    borderColor: theme.success,
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  dashboardVerifiedTitle: {
    color: theme.success,
    fontSize: 16,
    fontWeight: '800',
  },
  dashboardVerifiedText: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  dashboardStatusBanner: {
    gap: 10,
  },
  dashboardSectionCard: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  dashboardSection: {
    gap: 10,
  },
  dashboardSectionTitle: {
    color: theme.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  dashboardSupportText: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 18,
  },
  dashboardDetailRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'space-between',
  },
  dashboardFieldGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  dashboardFieldColumn: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 220,
  },
  dashboardDetailItem: {
    flexGrow: 1,
    flexShrink: 1,
    gap: 4,
    minWidth: 160,
  },
  dashboardFavoriteBusinessCard: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
  },
  dashboardNotificationCard: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
  },
  dashboardNotificationCardSelected: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.accent,
  },
  blockedCustomerSelectableCard: {
    paddingVertical: 14,
  },
  blockedCustomerSelectableContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  blockedCustomerListScroller: {
    maxHeight: 430,
  },
  blockedCustomerModalListScroller: {
    maxHeight: 300,
  },
  blockedCustomerSelectionIndicator: {
    alignItems: 'center',
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 2,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  blockedCustomerSelectionIndicatorActive: {
    borderColor: theme.accent,
  },
  blockedCustomerSelectionIndicatorDot: {
    backgroundColor: theme.accent,
    borderRadius: 999,
    height: 10,
    width: 10,
  },
  blockedCustomerConfirmModalCard: {
    gap: 14,
    maxHeight: '84%',
  },
  blockedCustomerConfirmationRow: {
    paddingVertical: 14,
  },
  dashboardNotificationCardSingle: {
    alignSelf: 'stretch',
    width: '100%',
  },
  dashboardNotificationList: {
    gap: 10,
  },
  dashboardNotificationListScroller: {
    maxHeight: 620,
  },
  dashboardNotificationSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  dashboardNotificationClearButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: theme.bgElevated,
    borderColor: theme.accent,
    borderRadius: 12,
    borderWidth: 1,
    flexShrink: 0,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  dashboardNotificationClearButtonText: {
    color: theme.accent,
    fontSize: 13,
    fontWeight: '700',
  },
  dashboardNotificationHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  dashboardNotificationHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  dashboardNotificationTitle: {
    color: theme.textPrimary,
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 18,
  },
  dashboardNotificationTimestamp: {
    color: theme.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'left',
  },
  dashboardNotificationDismissButton: {
    backgroundColor: theme.dangerSoft,
    borderColor: theme.danger,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  dashboardNotificationDismissButtonText: {
    color: theme.danger,
    fontSize: 11,
    fontWeight: '800',
  },
  dashboardFavoriteBusinessAction: {
    color: theme.accent,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  dashboardCampaignCard: {
    gap: 10,
    minWidth: 220,
  },
  dashboardCampaignHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  dashboardCampaignHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  dashboardCampaignStatusBadge: {
    backgroundColor: theme.warningSoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  dashboardCampaignStatusBadgeActive: {
    backgroundColor: theme.successSoft,
  },
  dashboardCampaignStatusBadgeText: {
    color: theme.warning,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  dashboardCampaignStatusBadgeTextActive: {
    color: theme.success,
  },
  dashboardDetailLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  dashboardDetailValue: {
    color: theme.textPrimary,
    fontSize: 15,
    lineHeight: 20,
  },
  dashboardInlineActions: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  dashboardInlineButton: {
    alignSelf: 'flex-start',
    marginTop: 0,
    minWidth: 220,
  },
  settingsItemRow: {
    alignItems: 'flex-start',
    gap: 10,
  },
  settingsItemBody: {
    gap: 8,
    width: '100%',
  },
  settingsItemActions: {
    alignItems: 'stretch',
    gap: 10,
    width: '100%',
  },
  settingsInlineButton: {
    alignSelf: 'stretch',
    marginTop: 0,
    maxWidth: '100%',
    width: '100%',
  },
  settingsSwitchCluster: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    width: '100%',
  },
  settingsSwitchLabelGroup: {
    alignItems: 'flex-start',
    gap: 2,
  },
  dashboardCodeCard: {
    backgroundColor: theme.bgSoft,
    borderColor: theme.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dashboardCodeLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  dashboardCodeValue: {
    color: theme.textPrimary,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  dashboardCodeActionButton: {
    alignSelf: 'flex-start',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  dashboardCodeActionText: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  dashboardCodeHelpText: {
    color: theme.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 10,
  },
  dashboardQrCard: {
    alignItems: 'center',
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  dashboardQrImage: {
    alignItems: 'center',
    borderRadius: 12,
    height: 180,
    justifyContent: 'center',
    width: 180,
  },
  dashboardQrMatrix: {
    alignItems: 'stretch',
    backgroundColor: theme.bgRaised,
    padding: 8,
  },
  dashboardQrMatrixRow: {
    flexDirection: 'row',
  },
  dashboardQrMatrixCell: {
    backgroundColor: theme.bgRaised,
  },
  dashboardQrLoadingState: {
    alignItems: 'center',
    height: 180,
    justifyContent: 'center',
    paddingHorizontal: 12,
    width: 180,
  },
  dashboardQrMeta: {
    alignItems: 'center',
    gap: 4,
  },
  dashboardQrTitle: {
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  dashboardQrSubtitle: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  dashboardFooterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  dashboardHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  dashboardHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: 10,
  },
  settingsIconButton: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  settingsGearIcon: {
    alignItems: 'center',
    height: 20,
    justifyContent: 'center',
    position: 'relative',
    width: 20,
  },
  settingsGearTooth: {
    backgroundColor: theme.textPrimary,
    borderRadius: 1,
    height: 4,
    position: 'absolute',
    width: 3,
  },
  settingsGearToothTop: {
    top: 0,
  },
  settingsGearToothTopRight: {
    right: 3,
    top: 2,
    transform: [{ rotate: '45deg' }],
  },
  settingsGearToothRight: {
    right: 0,
    transform: [{ rotate: '90deg' }],
  },
  settingsGearToothBottomRight: {
    bottom: 2,
    right: 3,
    transform: [{ rotate: '135deg' }],
  },
  settingsGearToothBottom: {
    bottom: 0,
  },
  settingsGearToothBottomLeft: {
    bottom: 2,
    left: 3,
    transform: [{ rotate: '45deg' }],
  },
  settingsGearToothLeft: {
    left: 0,
    transform: [{ rotate: '90deg' }],
  },
  settingsGearToothTopLeft: {
    left: 3,
    top: 2,
    transform: [{ rotate: '135deg' }],
  },
  settingsGearOuterRing: {
    alignItems: 'center',
    borderColor: theme.textPrimary,
    borderRadius: 999,
    borderWidth: 2,
    height: 14,
    justifyContent: 'center',
    width: 14,
  },
  settingsGearInnerHole: {
    backgroundColor: theme.bgElevated,
    borderRadius: 999,
    borderColor: theme.textPrimary,
    borderWidth: 1.5,
    height: 5,
    width: 5,
  },
  legalSectionCard: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  destructiveButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: theme.dangerSoft,
    borderColor: theme.danger,
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  destructiveButtonText: {
    color: theme.danger,
    fontWeight: '700',
  },
  toggleChip: {
    alignSelf: 'flex-start',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  toggleChipActive: {
    backgroundColor: theme.accent,
    borderColor: theme.accent,
  },
  toggleChipText: {
    color: theme.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  toggleChipTextActive: {
    color: theme.textOnAccent,
  },
} as const;

