// Place detail, reviews, media lightbox, social action cards, and shared error states.
export const detailStyles = {
  sectionTitle: {
    color: '#402214',
    fontSize: 18,
    fontWeight: '700',
  },
  detailSectionTitle: {
    marginTop: 22,
  },
  locationsSectionTitle: {
    paddingTop: 6,
    paddingBottom: 6,
  },
  detailScreenRoot: {
    flex: 1,
    backgroundColor: '#f7efe2',
  },
  detailScreenLandscape: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  detailScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 10,
    paddingTop: 0,
    paddingBottom: 20,
  },
  detailScrollContentLandscape: {
    paddingTop: 0,
  },
  backButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  backButtonText: {
    color: '#402214',
    fontWeight: '700',
  },
  linkButtonDisabled: {
    opacity: 0.7,
  },
  detailCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 12,
    padding: 18,
    
    width: '100%',
  },
  detailCardLandscape: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  detailHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  detailHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  detailHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  detailCity: {
    color: '#b07a3f',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  detailTitle: {
    color: '#2d221a',
    fontSize: 26,
    fontWeight: '800',
    marginTop: 6,
  },
  detailMeta: {
    color: '#5f4b3d',
    fontSize: 14,
    marginTop: 6,
  },
  photoGalleryScroll: {
    marginTop: 10,
  },
  photoGalleryRow: {
    gap: 10,
    paddingRight: 4,
  },
  photoGalleryCard: {
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    width: 176,
  },
  photoGalleryImage: {
    backgroundColor: '#ecdac7',
    height: 132,
    width: '100%',
  },
  photoGalleryDismissButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(64, 34, 20, 0.86)',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 8,
    top: 8,
    width: 28,
    zIndex: 1,
  },
  photoGalleryDismissButtonText: {
    color: '#fff7ef',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 14,
    textAlign: 'center',
  },
  photoGalleryMeta: {
    gap: 2,
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  photoLightboxOverlay: {
    backgroundColor: 'rgba(17, 12, 8, 0.96)',
    flex: 1,
  },
  photoLightboxHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingBottom: 10,
  },
  photoLightboxCounter: {
    color: '#fff7ef',
    fontSize: 15,
    fontWeight: '700',
  },
  photoLightboxCloseButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 247, 239, 0.14)',
    borderColor: 'rgba(255, 247, 239, 0.28)',
    borderRadius: 999,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  photoLightboxCloseButtonText: {
    color: '#fff7ef',
    fontSize: 14,
    fontWeight: '800',
  },
  photoLightboxSlide: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 18,
  },
  photoLightboxImage: {
    flex: 1,
    maxHeight: '100%',
    width: '100%',
  },
  favoriteStarButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    marginTop: 4,
    width: 48,
  },
  favoriteStarButtonActive: {
    backgroundColor: '#fff1d1',
    borderColor: '#d9a441',
  },
  favoriteStarIcon: {
    color: '#8f725d',
    fontSize: 26,
    lineHeight: 28,
    textAlign: 'center',
  },
  favoriteStarIconActive: {
    color: '#d08b00',
  },
  verifiedStatusBadge: {
    alignItems: 'center',
    backgroundColor: '#e7f7ef',
    borderColor: '#3f8f62',
    borderRadius: 999,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  verifiedStatusBadgeIcon: {
    color: '#23734a',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 26,
    textAlign: 'center',
  },
  detailAddress: {
    color: '#7c6252',
    fontSize: 14,
    marginTop: 4,
  },
  addressButton: {
    alignSelf: 'flex-start',
  },
  detailLinkText: {
    color: '#9e5b49',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
    textDecorationLine: 'underline',
  },
  detailMapCard: {
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 12,
    overflow: 'hidden',
  },
  detailMap: {
    height: 170,
    width: '100%',
  },
  detailMapCaption: {
    backgroundColor: '#fff7ef',
    borderTopColor: '#efd8bd',
    borderTopWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  detailMapCaptionText: {
    color: '#5f4b3d',
    fontSize: 13,
    fontWeight: '600',
  },
  reviewSummaryCard: {
    backgroundColor: '#fff3e5',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  reviewSummaryRating: {
    color: '#2d221a',
    fontSize: 18,
    fontWeight: '800',
  },
  reviewSummaryMeta: {
    color: '#6c5443',
    fontSize: 13,
    marginTop: 4,
  },
  reviewList: {
    gap: 12,
    marginTop: 12,
  },
  reviewCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  reviewQuote: {
    color: '#4d3a2f',
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 21,
  },
  linkButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#9e5b49',
    borderRadius: 14,
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  linkButtonText: {
    color: '#effffd',
    fontWeight: '700',
  },
  loadingButtonContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
  },
  linkButtonSecondary: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#9e5b49',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  linkButtonSecondaryText: {
    color: '#9e5b49',
    fontWeight: '700',
    
  },
  socialButtonsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  socialButtonCard: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minWidth: 150,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  socialButtonIconWrap: {
    alignItems: 'center',
    backgroundColor: '#f4e5d3',
    borderRadius: 999,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  socialButtonTextWrap: {
    flex: 1,
    gap: 2,
  },
  socialButtonLabel: {
    color: '#6f5647',
    fontSize: 12,
    fontWeight: '700',
  },
  socialButtonHandle: {
    color: '#2d221a',
    fontSize: 14,
    fontWeight: '800',
  },
  structuredEditorSection: {
    gap: 10,
    marginTop: 8,
  },
  structuredEditorCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#e6cfbb',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    marginTop: 8,
    padding: 12,
  },
  structuredNestedCard: {
    backgroundColor: '#fff4e8',
    borderColor: '#edd5bc',
    borderRadius: 14,
    borderWidth: 1,
    gap: 8,
    marginTop: 10,
    padding: 10,
  },
  structuredWeekdayRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  structuredDealTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  structuredWeekdayChip: {
    borderColor: '#d6b291',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  structuredWeekdayChipActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#9e5b49',
  },
  structuredWeekdayChipText: {
    color: '#9e5b49',
    fontSize: 12,
    fontWeight: '700',
  },
  structuredWeekdayChipTextActive: {
    color: '#fffaf4',
  },
  structuredTimeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  structuredTimeInput: {
    flex: 1,
  },
  structuredRemoveButton: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
  },
  structuredRemoveButtonText: {
    color: '#9e5b49',
    fontSize: 12,
    fontWeight: '700',
  },
  dealCard: {
    backgroundColor: '#fff3e5',
    borderRadius: 18,
    marginTop: 14,
    padding: 14,
  },
  dealPreviewLabel: {
    color: '#7d614f',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
    marginTop: 14,
    textTransform: 'uppercase',
  },
  dealAttachmentImageFrame: {
    overflow: 'hidden',
    position: 'relative',
  },
  dealAttachmentImageButton: {
    borderRadius: 14,
    marginBottom: 12,
    overflow: 'hidden',
  },
  dealAttachmentImage: {
    backgroundColor: '#f4e2d0',
    height: 176,
    width: '100%',
  },
  dealAttachmentPdfCard: {
    marginTop: 10,
  },
  dealHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  dealTitle: {
    color: '#2f241b',
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
  },
  pill: {
    backgroundColor: '#f8d8bf',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  pillText: {
    color: '#9a6a34',
    fontSize: 12,
    fontWeight: '700',
  },
  dealPrice: {
    color: '#b07a3f',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 10,
  },
  dealDescription: {
    color: '#5b4c41',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  dealTerms: {
    color: '#7a6658',
    fontSize: 13,
    marginTop: 8,
  },
  hourList: {
    gap: 10,
    marginTop: 10,
  },
  hourGroupCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd9c5',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  hourGroupDays: {
    color: '#9a6a34',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  hourRow: {
    color: '#43352c',
    fontSize: 13,
  },
  emptyStateText: {
    color: '#735e4c',
    fontSize: 14,
    lineHeight: 20,
    paddingVertical: 20,
  },
  errorBanner: {
    backgroundColor: '#ffe0d6',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  errorText: {
    color: '#8d2500',
    fontSize: 13,
    lineHeight: 18,
  },
  mapErrorBanner: {
    alignSelf: 'stretch',
  },
  linkButtonSecondaryWide: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#fff7ef',
    borderColor: '#9e5b49',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    width: '100%',
  },
} as const;

