import { theme } from './theme';

// Place detail, reviews, media lightbox, social action cards, and shared error states.
export const detailStyles = {
  sectionTitle: {
    color: theme.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  detailSectionTitle: {
    marginTop: 22,
  },
  locationsSectionTitle: {
    paddingTop: 6,
    paddingBottom: 6,
  },
  detailScreenRoot: {
    flex: 1,
    backgroundColor: theme.bgApp,
  },
  detailScreenLandscape: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  detailScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 10,
    paddingTop: 0,
    paddingBottom: 20,
  },
  detailScrollContentLandscape: {
    paddingTop: 0,
  },
  backButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: theme.bgElevated,
    borderColor: theme.borderStrong,
    borderWidth: 1,
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  backButtonText: {
    color: theme.textPrimary,
    fontWeight: '700',
    textAlign: 'center',
  },
  linkButtonDisabled: {
    opacity: 0.7,
  },
  detailCard: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 12,
    padding: 18,
    
    width: '100%',
  },
  detailCardLandscape: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  detailHeaderRow: {
    alignItems: 'stretch',
    flexDirection: 'column',
    gap: 4,
    width: '100%',
  },
  detailHeaderActions: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
    marginTop: 4,
    width: '100%',
  },
  detailHeaderCopy: {
    minWidth: 0,
    width: '100%',
  },
  detailCity: {
    color: theme.accentStrong,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  detailTitle: {
    color: theme.textPrimary,
    fontSize: 26,
    fontWeight: '800',
    marginTop: 6,
  },
  detailMeta: {
    color: theme.textSecondary,
    fontSize: 14,
    marginTop: 6,
  },
  photoGalleryScroll: {
    marginTop: 10,
  },
  photoGalleryRow: {
    gap: 10,
    paddingRight: 4,
  },
  photoGalleryCard: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    width: 176,
  },
  photoGalleryImage: {
    backgroundColor: theme.bgMuted,
    height: 132,
    width: '100%',
  },
  photoGalleryDismissButton: {
    alignItems: 'center',
    backgroundColor: theme.bgOverlayHeavy,
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 8,
    top: 8,
    width: 28,
    zIndex: 1,
  },
  photoGalleryDismissButtonText: {
    color: theme.textPrimary,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 14,
    textAlign: 'center',
  },
  photoGalleryMeta: {
    gap: 2,
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  photoLightboxOverlay: {
    backgroundColor: 'rgba(17, 12, 8, 0.96)',
    flex: 1,
  },
  photoLightboxHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingBottom: 10,
  },
  photoLightboxCounter: {
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  photoLightboxCloseButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: theme.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  photoLightboxCloseButtonText: {
    color: theme.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  photoLightboxSlide: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 18,
  },
  photoLightboxImage: {
    flex: 1,
    maxHeight: '100%',
    width: '100%',
  },
  favoriteHeartButton: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    marginTop: 4,
    flexShrink: 0,
    width: 48,
  },
  favoriteHeartButtonActive: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.accent,
  },
  contentReportButton: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    marginTop: 4,
    flexShrink: 0,
    width: 48,
  },
  favoriteHeartIcon: {
    color: theme.textMuted,
    fontSize: 26,
    lineHeight: 28,
    textAlign: 'center',
  },
  favoriteHeartIconActive: {
    color: theme.accent,
  },
  starredBusinessBadge: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#d9aa32',
    borderRadius: 999,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    flexShrink: 0,
    width: 48,
  },
  starredBusinessBadgeIcon: {
    color: '#d9aa32',
    fontSize: 26,
    lineHeight: 28,
    textAlign: 'center',
  },
  verifiedStatusBadge: {
    alignItems: 'center',
    backgroundColor: '#e7f7ef',
    borderColor: '#3f8f62',
    borderRadius: 999,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    flexShrink: 0,
    width: 48,
  },
  verifiedStatusBadgeIcon: {
    color: '#23734a',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 26,
    textAlign: 'center',
  },
  detailAddress: {
    color: theme.textSecondary,
    fontSize: 14,
    marginTop: 4,
  },
  addressButton: {
    alignSelf: 'flex-start',
  },
  detailLinkText: {
    color: theme.accent,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
    textDecorationLine: 'underline',
  },
  detailMapCard: {
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 12,
    overflow: 'hidden',
  },
  detailMap: {
    height: 170,
    width: '100%',
  },
  detailMapCaption: {
    backgroundColor: theme.bgElevated,
    borderTopColor: theme.border,
    borderTopWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  detailMapCaptionText: {
    color: theme.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  reviewSummaryCard: {
    backgroundColor: theme.bgSoft,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  reviewSummaryRating: {
    color: theme.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  reviewSummaryMeta: {
    color: theme.textSecondary,
    fontSize: 13,
    marginTop: 4,
  },
  reviewList: {
    gap: 12,
    marginTop: 12,
  },
  reviewCard: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  reviewQuote: {
    color: theme.textSecondary,
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 21,
  },
  linkButton: {
    alignSelf: 'flex-start',
    backgroundColor: theme.accent,
    borderRadius: 14,
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  linkButtonText: {
    color: theme.textOnAccent,
    fontWeight: '700',
  },
  loadingButtonContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
  },
  linkButtonSecondary: {
    alignSelf: 'flex-start',
    backgroundColor: theme.bgElevated,
    borderColor: theme.accent,
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  linkButtonSecondaryText: {
    color: theme.accent,
    fontWeight: '700',
    
  },
  socialButtonsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  socialButtonCard: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minWidth: 150,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  socialButtonIconWrap: {
    alignItems: 'center',
    backgroundColor: theme.bgMuted,
    borderRadius: 999,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  socialButtonTextWrap: {
    flex: 1,
    gap: 2,
  },
  socialButtonLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  socialButtonHandle: {
    color: theme.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  structuredEditorSection: {
    gap: 10,
    marginTop: 8,
  },
  structuredEditorCard: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    marginTop: 8,
    padding: 12,
  },
  structuredNestedCard: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    gap: 8,
    marginTop: 10,
    padding: 10,
  },
  structuredWeekdayRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  structuredDealTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  structuredWeekdayChip: {
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  structuredWeekdayChipActive: {
    backgroundColor: theme.accent,
    borderColor: theme.accent,
  },
  structuredWeekdayChipText: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  structuredWeekdayChipTextActive: {
    color: theme.textOnAccent,
  },
  structuredTimeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  structuredTimeInput: {
    flex: 1,
  },
  dealEditorCard: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 8,
    padding: 16,
    gap: 18,
  },
  dealEditorEyebrow: {
    color: theme.accentStrong,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  dealEditorSection: {
    borderTopColor: theme.border,
    borderTopWidth: 1,
    paddingTop: 18,
    gap: 14,
  },
  dealEditorSectionHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  dealEditorStep: {
    color: theme.accentStrong,
    fontSize: 13,
    fontWeight: '800',
    minWidth: 18,
  },
  dealEditorSectionTitle: {
    color: theme.textPrimary,
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 23,
    letterSpacing: -0.15,
  },
  dealEditorHelp: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  dealEditorField: {
    gap: 8,
  },
  dealEditorFieldLabel: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  dealEditorInput: {
    backgroundColor: theme.bgInput,
    borderColor: theme.border,
    borderRadius: 10,
    borderWidth: 1,
    color: theme.textPrimary,
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  dealEditorInputFocused: {
    borderColor: theme.accent,
  },
  dealEditorMultilineInput: {
    minHeight: 96,
  },
  dealEditorDisclosure: {
    borderTopColor: theme.border,
    borderTopWidth: 1,
  },
  dealEditorDisclosureButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 52,
    paddingVertical: 12,
  },
  dealEditorDisclosureCopy: {
    flex: 1,
    gap: 4,
  },
  dealEditorDisclosureTitle: {
    color: theme.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  dealEditorDisclosureIndicator: {
    color: theme.accentStrong,
    fontSize: 22,
    width: 20,
    textAlign: 'center',
  },
  dealEditorDisclosureContent: {
    gap: 16,
    paddingBottom: 4,
  },
  dealEditorEntry: {
    borderTopColor: theme.border,
    borderTopWidth: 1,
    gap: 14,
    paddingTop: 12,
    paddingBottom: 6,
  },
  dealEditorItemHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  dealEditorTextButton: {
    alignSelf: 'flex-start',
    justifyContent: 'center',
    minHeight: 44,
    paddingVertical: 10,
  },
  dealEditorTextButtonLabel: {
    color: theme.accentStrong,
    fontSize: 13,
    fontWeight: '700',
  },
  dealEditorAddButton: {
    alignSelf: 'flex-start',
    borderColor: theme.borderStrong,
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dealEditorAddButtonLabel: {
    color: theme.accentStrong,
    fontSize: 14,
    fontWeight: '700',
  },
  dealEditorDisabled: {
    opacity: 0.5,
  },
  dealEditorAllDayButton: {
    alignSelf: 'flex-start',
    justifyContent: 'center',
    minHeight: 44,
  },
  dealEditorChoice: {
    justifyContent: 'center',
    minHeight: 44,
    paddingVertical: 10,
  },
  dealEditorChoiceActive: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.accentStrong,
  },
  dealEditorChoiceTextActive: {
    color: theme.accentStrong,
  },
  dealEditorPreview: {
    marginTop: 0,
  },
  dealEditorPreviewTypeRow: {
    alignItems: 'flex-end',
    marginBottom: 8,
  },
  structuredRemoveButton: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
  },
  structuredRemoveButtonText: {
    color: theme.accent,
    fontSize: 12,
    fontWeight: '700',
  },
  dealCard: {
    backgroundColor: theme.bgSoft,
    borderRadius: 18,
    marginTop: 14,
    padding: 14,
  },
  dealPreviewLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
    marginTop: 14,
    textTransform: 'uppercase',
  },
  dealAttachmentImageFrame: {
    overflow: 'hidden',
    position: 'relative',
  },
  dealAttachmentImageButton: {
    borderRadius: 14,
    marginBottom: 12,
    overflow: 'hidden',
  },
  dealAttachmentImage: {
    backgroundColor: theme.bgMuted,
    height: 176,
    width: '100%',
  },
  dealAttachmentPdfCard: {
    marginTop: 10,
  },
  dealHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  dealHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: 6,
  },
  dealActionButton: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  dealTitle: {
    color: theme.textPrimary,
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
  },
  pill: {
    backgroundColor: theme.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  pillText: {
    color: theme.accentStrong,
    fontSize: 12,
    fontWeight: '700',
  },
  dealPrice: {
    color: theme.accentStrong,
    fontSize: 15,
    fontWeight: '700',
    marginTop: 10,
  },
  dealDescriptionBlock: {
    gap: 8,
    marginTop: 8,
  },
  dealDescriptionOffer: {
    gap: 8,
  },
  dealDescriptionRow: {
    alignItems: 'flex-start',
    gap: 3,
  },
  dealDescriptionMenuItem: {
    alignSelf: 'stretch',
    gap: 2,
    width: '100%',
  },
  dealDescriptionMenuHeadingRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  dealDescriptionMenuName: {
    flex: 1,
  },
  dealDescriptionMenuNameWithDetail: {
    color: theme.textPrimary,
    fontWeight: '600',
  },
  dealDescriptionMenuDetail: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 4,
  },
  dealDescriptionDay: {
    color: theme.accentStrong,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  dealDescriptionText: {
    color: theme.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  dealDescriptionOfferText: {
    color: theme.textPrimary,
    fontSize: 13,
    lineHeight: 19,
  },
  dealDescriptionToggle: {
    alignSelf: 'flex-start',
    minHeight: 44,
    justifyContent: 'center',
  },
  dealDescriptionToggleText: {
    color: theme.accentStrong,
    fontSize: 13,
    fontWeight: '700',
  },
  dealTerms: {
    color: theme.textMuted,
    fontSize: 13,
    marginTop: 8,
  },
  hourList: {
    gap: 10,
    marginTop: 10,
  },
  hourGroupCard: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  hourGroupDays: {
    color: theme.accentStrong,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  hourRow: {
    color: theme.textPrimary,
    fontSize: 13,
  },
  emptyStateText: {
    color: theme.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    paddingVertical: 20,
  },
  errorBanner: {
    backgroundColor: theme.dangerSoft,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  errorText: {
    color: theme.danger,
    fontSize: 13,
    lineHeight: 18,
  },
  mapErrorBanner: {
    alignSelf: 'stretch',
  },
  linkButtonSecondaryWide: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: theme.bgElevated,
    borderColor: theme.accent,
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    width: '100%',
  },
  publicProfileScrollContent: {
    paddingHorizontal: 0,
  },
  publicProfileNavigationBar: {
    backgroundColor: theme.bgApp,
    borderBottomColor: theme.border,
    borderTopWidth: 0,
    marginBottom: 0,
    marginHorizontal: 0,
    minHeight: 0,
    paddingBottom: 8,
    paddingHorizontal: 16,
  },
  publicProfileMessageControl: {
    marginRight: 0,
  },
  publicProfileCard: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    elevation: 0,
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 0,
    shadowOpacity: 0,
  },
  publicProfileHeaderActions: {
    alignSelf: 'flex-start',
    flex: 1,
    justifyContent: 'space-evenly',
    marginTop: 0,
    marginBottom: 4,
    width: 'auto',
  },
  publicProfileHeaderTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    width: '100%',
  },
  publicProfileCityCategoryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
    width: '100%',
  },
  publicProfileCityCategoryLabel: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  publicProfileMultiLocationLabel: {
    flex: 0,
    maxWidth: '100%',
  },
  publicProfileHeaderControl: {
    backgroundColor: 'transparent',
    borderColor: theme.border,
    height: 44,
    marginTop: 0,
    width: 44,
  },
  publicProfileStatusBadge: {
    height: 44,
    width: 44,
  },
  publicProfileCity: {
    fontSize: 11,
    letterSpacing: 1.1,
    lineHeight: 16,
  },
  publicProfileName: {
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.45,
    lineHeight: 33,
    marginTop: 4,
  },
  publicProfileCategory: {
    alignSelf: 'flex-start',
    backgroundColor: theme.bgElevated,
    borderColor: 'rgba(255, 122, 112, 0.22)',
    borderRadius: 999,
    borderWidth: 1,
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 9,
    overflow: 'hidden',
    paddingHorizontal: 11,
    paddingVertical: 5,
  },
  publicProfileCategoryBesideCity: {
    alignSelf: 'center',
    flexShrink: 1,
    marginTop: 0,
    maxWidth: '55%',
  },
  publicProfileFavoriteHelper: {
    color: theme.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
  },
  publicProfileSectionHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 2,
    marginTop: 20,
    width: '100%',
  },
  publicProfileSectionAccent: {
    backgroundColor: theme.accent,
    borderRadius: 3,
    height: 14,
    width: 2,
  },
  publicProfileSectionTitle: {
    color: theme.textPrimary,
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 21,
    letterSpacing: 0.1,
  },
  publicProfileSectionRule: {
    backgroundColor: theme.border,
    flex: 1,
    height: 1,
    minWidth: 12,
  },
  publicProfilePhotoGalleryScroll: {
    marginTop: 10,
  },
  publicProfilePhotoGalleryRow: {
    gap: 0,
    paddingRight: 0,
  },
  publicProfilePhotoCard: {
    backgroundColor: theme.bgElevated,
    borderRadius: 14,
    borderWidth: 0,
    elevation: 0,
    overflow: 'hidden',
  },
  publicProfilePhotoImage: {
    backgroundColor: theme.bgElevated,
    width: '100%',
  },
  publicProfilePhotoPagination: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 26,
  },
  publicProfilePhotoPaginationText: {
    color: theme.textMuted,
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
  },
  publicProfileDealCard: {
    backgroundColor: theme.bgElevated,
    borderRadius: 14,
    borderWidth: 0,
    elevation: 0,
    marginTop: 10,
    padding: 12,
    shadowOpacity: 0,
  },
  publicProfileDealImageButton: {
    borderRadius: 10,
    marginBottom: 10,
  },
  publicProfileDealImage: {
    height: 190,
  },
  publicProfileDealHeaderRow: {
    alignItems: 'center',
    gap: 10,
    justifyContent: 'space-between',
  },
  publicProfileDealHeaderActions: {
    justifyContent: 'flex-start',
  },
  publicProfileDealTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
    letterSpacing: -0.15,
    marginTop: 0,
  },
  publicProfileDealTitlePriceRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  publicProfileDealActionButton: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    height: 44,
    width: 44,
  },
  publicProfileDealType: {
    backgroundColor: theme.accentSoft,
    borderColor: 'rgba(255, 95, 104, 0.2)',
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  publicProfileDealTypeText: {
    color: theme.accentStrong,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.25,
  },
  publicProfilePriceBadge: {
    alignSelf: 'flex-start',
    flexShrink: 1,
    maxWidth: '48%',
  },
  publicProfileDealPrice: {
    color: theme.accentStrong,
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
    marginTop: 0,
    textAlign: 'right',
  },
  publicProfileDealDescriptionBlock: {
    gap: 4,
    marginTop: 6,
  },
  publicProfileDealDescriptionRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  publicProfileDealDescriptionDay: {
    flexShrink: 1,
    lineHeight: 20,
    width: '26%',
  },
  publicProfileDealDescriptionText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  publicProfileMenuPrice: {
    color: theme.textPrimary,
    flexShrink: 0,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    maxWidth: '35%',
    textAlign: 'right',
  },
  publicProfileDealTerms: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 6,
  },
  publicProfileScheduleList: {
    gap: 0,
    marginTop: 6,
  },
  publicProfileDealScheduleList: {
    borderTopColor: theme.border,
    borderTopWidth: 1,
    marginTop: 8,
    paddingTop: 2,
  },
  publicProfileScheduleCard: {
    alignItems: 'baseline',
    backgroundColor: 'transparent',
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    borderRadius: 0,
    borderWidth: 0,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    paddingVertical: 8,
  },
  publicProfileDealScheduleCard: {
    borderBottomWidth: 0,
    paddingVertical: 5,
  },
  publicProfileScheduleDays: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.7,
    flexShrink: 1,
    lineHeight: 18,
    marginBottom: 0,
    maxWidth: '38%',
  },
  publicProfileScheduleTime: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    textAlign: 'right',
  },
  publicProfileTextRow: {
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    paddingVertical: 8,
  },
  publicProfileTextRowText: {
    color: theme.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  publicProfileEmptyState: {
    lineHeight: 20,
    marginTop: 6,
    paddingVertical: 8,
  },
  publicProfileLocationFilterRow: {
    gap: 8,
    marginTop: 8,
  },
  publicProfileLocationChip: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 10,
    minHeight: 44,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  publicProfileLocationChipActive: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.accent,
  },
  publicProfileLocationChipText: {
    color: theme.textSecondary,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  publicProfileLocationChipTextActive: {
    color: theme.textPrimary,
    fontWeight: '800',
  },
  publicProfileLocationPanel: {
    gap: 4,
    marginTop: 10,
  },
  publicProfileAddressButton: {
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    flexDirection: 'row',
    gap: 8,
    minHeight: 44,
    paddingVertical: 4,
  },
  publicProfileAddressIcon: {
    marginTop: 2,
  },
  publicProfileAddressText: {
    color: theme.textPrimary,
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 0,
    textDecorationLine: 'none',
  },
  publicProfileContactRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 12,
    justifyContent: 'space-between',
    rowGap: 4,
  },
  publicProfileLocationMeta: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 0,
  },
  publicProfileMapCard: {
    borderRadius: 14,
    borderWidth: 0,
    marginTop: 10,
  },
  publicProfileMap: {
    height: 188,
  },
  publicProfileMapCaption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  publicProfileSocialList: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 10,
    rowGap: 2,
    gap: 0,
    justifyContent: 'space-between',
    marginTop: 6,
    width: '100%',
  },
  publicProfileSocialCard: {
    alignItems: 'stretch',
    backgroundColor: 'transparent',
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    borderRadius: 0,
    borderWidth: 0,
    flexBasis: '47%',
    flexDirection: 'column',
    gap: 2,
    minHeight: 54,
    minWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 8,
    width: '47%',
  },
  publicProfileSocialIconWrap: {
    backgroundColor: 'transparent',
    height: 20,
    width: 20,
  },
  publicProfileSocialHeadingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  publicProfileSocialLabel: {
    color: theme.textMuted,
    fontSize: 11,
    letterSpacing: 0.3,
  },
  publicProfileSocialHandle: {
    color: theme.textPrimary,
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 17,
  },
  publicProfileSecondaryAction: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: 'transparent',
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    borderRadius: 0,
    borderWidth: 0,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginTop: 6,
    minHeight: 46,
    paddingHorizontal: 0,
    paddingVertical: 10,
  },
  publicProfileWideAction: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    borderRadius: 0,
    borderWidth: 0,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginTop: 4,
    minHeight: 48,
    paddingHorizontal: 0,
    paddingVertical: 10,
  },
  publicProfileActionText: {
    color: theme.accentStrong,
    fontSize: 14,
    flex: 1,
    fontWeight: '700',
    lineHeight: 20,
    textAlign: 'left',
  },
  publicProfileSupportingDetailsCard: {
    marginTop: 8,
  },
  publicProfileSupportingDetails: {
    color: theme.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 0,
  },
  publicProfileReportCard: {
    backgroundColor: 'transparent',
    borderColor: theme.border,
    borderRadius: 0,
    borderTopWidth: 1,
    borderWidth: 0,
    gap: 4,
    marginTop: 20,
    paddingHorizontal: 0,
    paddingVertical: 12,
  },
  publicProfileReportText: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  publicProfilePressed: {
    opacity: 0.65,
  },
} as const;

