// Direct messages inbox, thread, composer, and header action styles.
export const messagingStyles = {
  directMessageScreenHeaderBar: {
    marginHorizontal: 0,
  },
  directMessageHeaderTitle: {
    color: '#fff7ef',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 12,
  },
  directMessageHeaderActionButton: {
    alignItems: 'center',
    backgroundColor: '#fff8f0',
    borderColor: '#d9c0a4',
    borderRadius: 16,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  directMessagePlaneIcon: {
    height: 19,
    position: 'relative',
    width: 19,
  },
  directMessagePlaneLineBase: {
    backgroundColor: '#4b4139',
    borderRadius: 2,
    height: 3,
    left: 0,
    position: 'absolute',
    top: 8,
    width: 18,
  },
  directMessagePlaneLineWing: {
    backgroundColor: '#4b4139',
    borderRadius: 2,
    height: 3,
    left: 6,
    position: 'absolute',
    top: 3,
    transform: [{ rotate: '-40deg' }],
    width: 12,
  },
  directMessagePlaneLineTail: {
    backgroundColor: '#4b4139',
    borderRadius: 2,
    height: 3,
    left: 5,
    position: 'absolute',
    top: 10,
    transform: [{ rotate: '58deg' }],
    width: 9,
  },
  directMessageScreenRoot: {
    backgroundColor: '#f3eadf',
  },
  directMessageFeed: {
    flexGrow: 1,
    paddingHorizontal: 2,
    paddingTop: 6,
  },
  directMessageFeedLandscape: {
    paddingHorizontal: 8,
  },
  directMessageConversationTitleBar: {
    backgroundColor: '#f3eadf',
    borderBottomColor: '#dfc5ab',
    borderBottomWidth: 1,
    paddingHorizontal: 12,
    paddingBottom: 10,
    paddingTop: 8,
  },
  directMessageInboxHeaderBar: {
    borderBottomColor: '#dfc5ab',
    borderBottomWidth: 1,
    marginBottom: 8,
    paddingBottom: 8,
    paddingHorizontal: 4,
  },
  directMessageInboxTitle: {
    color: '#2d221a',
    fontSize: 22,
    fontWeight: '800',
  },
  directMessageInboxList: {
    gap: 2,
  },
  directMessageInboxRow: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderBottomColor: '#e3ccb1',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 68,
    paddingHorizontal: 2,
    paddingVertical: 10,
  },
  directMessageInboxActionTray: {
    alignItems: 'stretch',
    flexDirection: 'row',
    minHeight: 68,
  },
  directMessageInboxActionButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 68,
    paddingHorizontal: 14,
    width: 112,
  },
  directMessageInboxActionButtonBlock: {
    backgroundColor: '#5674ff',
  },
  directMessageInboxActionButtonUnblock: {
    backgroundColor: '#3fa56c',
  },
  directMessageInboxActionButtonDelete: {
    backgroundColor: '#ff5f5f',
  },
  directMessageInboxActionButtonText: {
    color: '#fffaf4',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  directMessageInboxAvatar: {
    alignItems: 'center',
    backgroundColor: '#d1b596',
    borderRadius: 999,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  directMessageInboxAvatarText: {
    color: '#2d221a',
    fontSize: 13,
    fontWeight: '700',
  },
  directMessageInboxCopy: {
    flex: 1,
    minWidth: 0,
  },
  directMessageInboxName: {
    color: '#2d221a',
    fontSize: 16,
    fontWeight: '700',
  },
  directMessageInboxPreview: {
    color: '#4f3d31',
    fontSize: 14,
    marginTop: 1,
  },
  directMessageInboxMeta: {
    color: '#6d5544',
    fontSize: 12,
    marginTop: 2,
  },
  directMessageTopSection: {
    marginBottom: 18,
  },
  directMessageSectionLabel: {
    color: '#2d221a',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  directMessageThreadRowInline: {
    borderBottomColor: '#e6cdb0',
    borderBottomWidth: 1,
    paddingVertical: 10,
  },
  directMessageThreadRowInlineActive: {
    backgroundColor: '#f8ead5',
    borderBottomColor: '#d9af81',
  },
  directMessageThreadInlineHeadingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  directMessageConversationSection: {
    gap: 10,
    paddingTop: 6,
  },
  directMessageConversationTitle: {
    color: '#2d221a',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 0,
    textAlign: 'center',
  },
  directMessageThreadTitle: {
    color: '#2d221a',
    fontSize: 15,
    fontWeight: '700',
    
  },
  directMessageThreadPreview: {
    color: '#6a5444',
    fontSize: 13,
    marginTop: 2,
  },
  directMessageThreadMeta: {
    color: '#7f6453',
    fontSize: 11,
    marginTop: 4,
  },
  directMessageUnreadBadge: {
    backgroundColor: '#8c5b48',
    borderRadius: 999,
    color: '#fffaf4',
    fontSize: 11,
    fontWeight: '700',
    minWidth: 22,
    paddingHorizontal: 7,
    paddingVertical: 2,
    textAlign: 'center',
  },
  directMessageMessageList: {
    paddingBottom: 8,
    paddingTop: 4,
  },
  directMessageBubbleWrap: {
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  directMessageBubbleWrapMine: {
    alignItems: 'flex-end',
  },
  directMessageBubble: {
    backgroundColor: '#2f2f2f',
    borderColor: '#2f2f2f',
    borderRadius: 18,
    borderWidth: 0,
    maxWidth: '84%',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 8,
  },
  directMessageBubbleMine: {
    backgroundColor: '#2a84ff',
    borderColor: '#2a84ff',
  },
  directMessageBubbleText: {
    color: '#fffaf4',
    fontSize: 15,
    lineHeight: 20,
  },
  directMessageBubbleTextMine: {
    color: '#fffaf4',
  },
  directMessageBubbleMeta: {
    color: '#c7c7c7',
    fontSize: 10,
    marginTop: 6,
  },
  directMessageBubbleMetaMine: {
    color: '#dceeff',
  },
  directMessageImage: {
    backgroundColor: '#e7d6c4',
    borderRadius: 12,
    height: 190,
    width: 220,
  },
  directMessageImageWrap: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  directMessageImageWrapMine: {
    alignSelf: 'flex-end',
  },
  directMessageComposerRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 6,
  },
  directMessageComposerInput: {
    flex: 1,
    lineHeight: 20,
    maxHeight: 124,
    marginBottom: 0,
    minHeight: 48,
    textAlignVertical: 'top',
  },
  directMessageComposerSendButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#fff7ef',
    borderColor: '#9e5b49',
    borderRadius: 14,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    marginTop: 0,
    paddingHorizontal: 16,
    width: 86,
  },
  directMessageComposerDock: {
    backgroundColor: '#f3eadf',
    borderTopColor: '#dfc5ab',
    borderTopWidth: 1,
    gap: 6,
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  directMessageComposerIconButton: {
    alignItems: 'center',
    backgroundColor: '#fff8f0',
    borderColor: '#d9c0a4',
    borderRadius: 999,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  directMessageComposerIconButtonText: {
    color: '#6b4a3a',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 26,
  },
  directMessageComposerImageDraftRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  directMessageComposerImageDraft: {
    borderRadius: 10,
    height: 64,
    width: 64,
  },
  directMessageComposerImageRemoveButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#cfb39a',
    borderRadius: 10,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  directMessageComposerImageRemoveButtonText: {
    color: '#7a4a34',
    fontSize: 13,
    fontWeight: '700',
  },
  directMessageComposerHint: {
    color: '#6d5446',
    fontSize: 12,
    paddingBottom: 2,
  },
  directMessageSpinner: {
    marginVertical: 12,
  },
  directMessageHeaderGlyphIcon: {
    height: 20,
    position: 'relative',
    width: 20,
  },
  directMessageHeaderGlyphEdgeTop: {
    backgroundColor: '#402214',
    borderRadius: 2,
    height: 2.6,
    left: 2,
    position: 'absolute',
    top: 2,
    width: 16,
  },
  directMessageHeaderGlyphEdgeLeft: {
    backgroundColor: '#402214',
    borderRadius: 2,
    height: 2.6,
    left: 0,
    position: 'absolute',
    top: 9,
    transform: [{ rotate: '47deg' }],
    width: 14,
  },
  directMessageHeaderGlyphEdgeRight: {
    backgroundColor: '#402214',
    borderRadius: 2,
    height: 2.6,
    left: 8,
    position: 'absolute',
    top: 9,
    transform: [{ rotate: '-47deg' }],
    width: 14,
  },
  directMessageHeaderGlyphSeam: {
    backgroundColor: '#402214',
    borderRadius: 2,
    height: 2.6,
    left: 9,
    position: 'absolute',
    top: 8,
    transform: [{ rotate: '84deg' }],
    width: 10,
  },
  directMessageActionModalHandle: {
    color: '#2d221a',
    fontSize: 15,
    fontWeight: '800',
    marginTop: 12,
  },
} as const;

