import { StyleSheet } from 'react-native';

// Attachment previews, guest prompts, and bottom-sheet surfaces.
export const modalStyles = {
  attachmentLightboxHeader: {
    paddingBottom: 10,
  },
  attachmentLightboxTitle: {
    color: '#fff7ef',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  attachmentLightboxBody: {
    flex: 1,
  },
  attachmentLightboxImageStage: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 18,
  },
  attachmentLightboxLoadingText: {
    color: '#fff7ef',
    fontSize: 13,
    textAlign: 'center',
  },
  attachmentSection: {
    marginTop: 2,
  },
  attachmentPickerButton: {
    marginTop: 0,
  },
  attachmentGalleryLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    marginTop: 12,
  },
  attachmentGalleryLabel: {
    color: '#5f4b3d',
    fontSize: 13,
    fontWeight: '700',
  },
  attachmentGalleryCount: {
    color: '#7d614f',
    fontSize: 12,
    fontWeight: '700',
  },
  attachmentSupportText: {
    marginTop: 4,
  },
  attachmentList: {
    gap: 8,
    marginTop: 10,
  },
  attachmentCard: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  attachmentMeta: {
    flex: 1,
    gap: 2,
  },
  attachmentPreviewButton: {
    flex: 1,
  },
  attachmentName: {
    color: '#3b2a1f',
    fontSize: 13,
    fontWeight: '700',
  },
  attachmentDetail: {
    color: '#7d614f',
    fontSize: 12,
  },
  attachmentRemoveButton: {
    backgroundColor: '#fde7dd',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  attachmentRemoveButtonText: {
    color: '#8d2500',
    fontSize: 12,
    fontWeight: '700',
  },
  attachmentPreviewOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(45, 34, 26, 0.62)',
    flex: 1,
    justifyContent: 'center',
    padding: 16,
  },
  attachmentPreviewSheet: {
    backgroundColor: '#f7efe2',
    borderColor: '#ddc4a7',
    borderRadius: 22,
    borderWidth: 1,
    flex: 1,
    maxHeight: '92%',
    maxWidth: 920,
    overflow: 'hidden',
    width: '100%',
  },
  attachmentPreviewHeader: {
    alignItems: 'center',
    borderBottomColor: '#ead6bf',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  attachmentPreviewTitle: {
    color: '#402214',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  attachmentPreviewCloseButton: {
    backgroundColor: '#fff7ef',
    borderColor: '#caa98d',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  attachmentPreviewCloseButtonText: {
    color: '#7a4d2f',
    fontSize: 13,
    fontWeight: '700',
  },
  attachmentPreviewBody: {
    backgroundColor: '#f3e7d8',
    flex: 1,
  },
  attachmentPreviewLoadingState: {
    alignItems: 'center',
    flex: 1,
    gap: 12,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  attachmentPreviewLoadingText: {
    color: '#7d614f',
    fontSize: 13,
    textAlign: 'center',
  },
  attachmentPreviewImage: {
    flex: 1,
    width: '100%',
  },
  guestFavoriteModalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(45, 34, 26, 0.58)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  guestFavoriteModalCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    maxWidth: 420,
    padding: 22,
    width: '100%',
  },
  guestBottomNavCloseButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    marginBottom: 2,
    width: 32,
  },
  guestBottomNavCloseButtonText: {
    color: '#5d4637',
    fontSize: 14,
    fontWeight: '800',
  },
  guestFavoriteModalTitle: {
    color: '#402214',
    fontSize: 20,
    fontWeight: '800',
  },
  guestFavoriteModalText: {
    color: '#6c5443',
    fontSize: 14,
    lineHeight: 21,
  },
  guestFavoriteModalActions: {
    gap: 10,
    marginTop: 4,
  },
  guestFavoriteModalSecondaryButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  guestFavoriteModalSecondaryText: {
    color: '#5d4637',
    fontSize: 14,
    fontWeight: '700',
  },
  guestFavoriteModalPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#9e5b49',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  guestFavoriteModalPrimaryText: {
    color: '#fffaf4',
    fontSize: 14,
    fontWeight: '800',
  },
  bottomSheetBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  bottomSheetBackdropOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(45, 34, 26, 0.22)',
  },
  bottomSheetBackdropPressable: {
    flex: 1,
  },
  bottomSheetCard: {
    backgroundColor: '#fffaf4',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: '#ead6bf',
    gap: 10,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 34,
    shadowColor: '#2d221a',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
  },
  bottomSheetDragZone: {
    marginHorizontal: -20,
    marginTop: -14,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 6,
  },
  bottomSheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#d5c1ad',
    borderRadius: 999,
    height: 5,
    marginBottom: 6,
    width: 46,
  },
  bottomSheetTitle: {
    color: '#402214',
    fontSize: 19,
    fontWeight: '800',
    marginBottom: 4,
  },
  bottomSheetActionButton: {
    backgroundColor: 'rgba(255, 247, 239, 0.88)',
    borderColor: '#e5d0b9',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  bottomSheetActionButtonDestructive: {
    backgroundColor: '#fff1ed',
    borderColor: '#efb1a7',
    marginTop: 4,
  },
  bottomSheetActionText: {
    color: '#402214',
    fontSize: 15,
    fontWeight: '700',
  },
  bottomSheetActionTextDestructive: {
    color: '#a34a3c',
  },
  attachmentPreviewWebView: {
    backgroundColor: '#f3e7d8',
    flex: 1,
  },
} as const;

