import { StyleSheet } from 'react-native';
import { theme } from './theme';

// Attachment previews, guest prompts, and bottom-sheet surfaces.
export const modalStyles = {
  attachmentLightboxHeader: {
    paddingBottom: 10,
  },
  attachmentLightboxTitle: {
    color: theme.textPrimary,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  attachmentLightboxBody: {
    flex: 1,
  },
  attachmentLightboxImageStage: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 18,
  },
  attachmentLightboxLoadingText: {
    color: theme.textPrimary,
    fontSize: 13,
    textAlign: 'center',
  },
  attachmentSection: {
    marginTop: 2,
  },
  attachmentPickerButton: {
    marginTop: 0,
  },
  attachmentGalleryLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    marginTop: 12,
  },
  attachmentGalleryLabel: {
    color: theme.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  attachmentGalleryCount: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  attachmentSupportText: {
    marginTop: 4,
  },
  attachmentList: {
    gap: 8,
    marginTop: 10,
  },
  attachmentCard: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  attachmentMeta: {
    flex: 1,
    gap: 2,
  },
  attachmentPreviewButton: {
    flex: 1,
  },
  attachmentName: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  attachmentDetail: {
    color: theme.textMuted,
    fontSize: 12,
  },
  attachmentRemoveButton: {
    backgroundColor: theme.dangerSoft,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  attachmentRemoveButtonText: {
    color: theme.danger,
    fontSize: 12,
    fontWeight: '700',
  },
  attachmentPreviewOverlay: {
    alignItems: 'center',
    backgroundColor: theme.bgOverlay,
    flex: 1,
    justifyContent: 'center',
    padding: 16,
  },
  attachmentPreviewSheet: {
    backgroundColor: theme.bgCanvas,
    borderColor: theme.borderStrong,
    borderRadius: 22,
    borderWidth: 1,
    flex: 1,
    maxHeight: '92%',
    maxWidth: 920,
    overflow: 'hidden',
    width: '100%',
  },
  attachmentPreviewHeader: {
    alignItems: 'center',
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  attachmentPreviewTitle: {
    color: theme.textPrimary,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  attachmentPreviewCloseButton: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  attachmentPreviewCloseButtonText: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  attachmentPreviewBody: {
    backgroundColor: theme.bgApp,
    flex: 1,
  },
  attachmentPreviewLoadingState: {
    alignItems: 'center',
    flex: 1,
    gap: 12,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  attachmentPreviewLoadingText: {
    color: theme.textMuted,
    fontSize: 13,
    textAlign: 'center',
  },
  attachmentPreviewImage: {
    flex: 1,
    width: '100%',
  },
  guestFavoriteModalBackdrop: {
    alignItems: 'center',
    backgroundColor: theme.bgOverlay,
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  guestFavoriteModalCard: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.borderStrong,
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    maxWidth: 420,
    padding: 22,
    width: '100%',
  },
  guestBottomNavCloseButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    marginBottom: 2,
    width: 32,
  },
  guestBottomNavCloseButtonText: {
    color: theme.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  guestFavoriteModalTitle: {
    color: theme.textPrimary,
    fontSize: 20,
    fontWeight: '800',
  },
  guestFavoriteModalText: {
    color: theme.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  guestFavoriteModalActions: {
    gap: 10,
    marginTop: 4,
  },
  guestFavoriteModalSecondaryButton: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  guestFavoriteModalSecondaryText: {
    color: theme.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  guestFavoriteModalPrimaryButton: {
    alignItems: 'center',
    backgroundColor: theme.accent,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  guestFavoriteModalPrimaryText: {
    color: theme.textOnAccent,
    fontSize: 14,
    fontWeight: '800',
  },
  bottomSheetBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  bottomSheetBackdropOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.bgOverlay,
  },
  bottomSheetBackdropPressable: {
    flex: 1,
  },
  bottomSheetCard: {
    backgroundColor: theme.bgCanvas,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: theme.borderStrong,
    gap: 10,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 34,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
  },
  bottomSheetDragZone: {
    marginHorizontal: -20,
    marginTop: -14,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 6,
  },
  bottomSheetHandle: {
    alignSelf: 'center',
    backgroundColor: theme.textDim,
    borderRadius: 999,
    height: 5,
    marginBottom: 6,
    width: 46,
  },
  bottomSheetTitle: {
    color: theme.textPrimary,
    fontSize: 19,
    fontWeight: '800',
    marginBottom: 4,
  },
  bottomSheetActionButton: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  bottomSheetActionButtonDestructive: {
    backgroundColor: theme.dangerSoft,
    borderColor: theme.danger,
    marginTop: 4,
  },
  bottomSheetActionText: {
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  bottomSheetActionTextDestructive: {
    color: theme.danger,
  },
  attachmentPreviewWebView: {
    backgroundColor: theme.bgApp,
    flex: 1,
  },
} as const;

