import { theme } from './theme';

export const preferenceStyles = {
  preferenceScrollContent: {
    flexGrow: 1,
    paddingBottom: 56,
  },
  preferenceShell: {
    alignSelf: 'center',
    maxWidth: 760,
    paddingHorizontal: 18,
    paddingVertical: 18,
    width: '100%',
  },
  preferenceProgressHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  preferenceEyebrow: {
    color: theme.accentStrong,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  preferenceProgressText: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  preferenceProgressTrack: {
    backgroundColor: theme.bgMuted,
    borderRadius: 999,
    height: 7,
    marginTop: 10,
    overflow: 'hidden',
  },
  preferenceProgressFill: {
    backgroundColor: theme.accent,
    borderRadius: 999,
    height: '100%',
  },
  preferenceTitle: {
    color: theme.textPrimary,
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 36,
    marginTop: 24,
  },
  preferenceIntro: {
    color: theme.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    marginTop: 10,
  },
  preferenceWelcomeBlock: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 20,
    borderWidth: 1,
    gap: 12,
    marginTop: 28,
    padding: 20,
  },
  preferenceWelcomeTitle: {
    color: theme.textPrimary,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 26,
  },
  preferenceLoading: {
    alignItems: 'center',
    gap: 10,
    paddingVertical: 24,
  },
  preferenceSection: {
    gap: 14,
    marginTop: 26,
  },
  preferenceSectionTitle: {
    color: theme.textPrimary,
    fontSize: 22,
    fontWeight: '800',
  },
  preferenceSupportText: {
    color: theme.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  preferenceLabel: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 6,
    textTransform: 'uppercase',
  },
  preferenceChipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  preferenceChip: {
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  preferenceChipActive: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.accent,
  },
  preferenceChipText: {
    color: theme.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  preferenceChipTextActive: {
    color: theme.textPrimary,
  },
  preferenceSearchInput: {
    backgroundColor: theme.bgInput,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    color: theme.textPrimary,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  preferenceEmptyText: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    color: theme.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    padding: 16,
  },
  preferenceBusinessList: {
    gap: 10,
  },
  preferenceBusinessCard: {
    alignItems: 'center',
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 16,
  },
  preferenceBusinessCardActive: {
    backgroundColor: theme.accentSoft,
    borderColor: theme.accent,
  },
  preferenceBusinessCopy: {
    flex: 1,
    gap: 4,
  },
  preferenceBusinessName: {
    color: theme.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  preferenceBusinessMeta: {
    color: theme.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  preferenceBusinessDeal: {
    color: theme.success,
    fontSize: 12,
    fontWeight: '800',
  },
  preferenceSelectionMark: {
    alignItems: 'center',
    borderColor: theme.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  preferenceSelectionMarkActive: {
    backgroundColor: theme.accent,
    borderColor: theme.accent,
  },
  preferenceSelectionMarkText: {
    color: theme.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  preferenceSelectionCount: {
    color: theme.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
  preferenceNotificationCard: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  preferencePauseRow: {
    alignItems: 'center',
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 14,
  },
  preferenceSelectAllButton: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
  },
  preferenceSelectAllText: {
    color: theme.accentStrong,
    fontSize: 12,
    fontWeight: '800',
  },
  preferenceToggleRow: {
    alignItems: 'center',
    borderTopColor: theme.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  preferenceToggleLabel: {
    color: theme.textSecondary,
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
  },
  preferenceToggle: {
    alignItems: 'center',
    backgroundColor: theme.bgMuted,
    borderRadius: 999,
    minWidth: 52,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  preferenceToggleActive: {
    backgroundColor: theme.success,
  },
  preferenceToggleText: {
    color: theme.textPrimary,
    fontSize: 12,
    fontWeight: '800',
  },
  preferenceReviewBlock: {
    backgroundColor: theme.bgRaised,
    borderColor: theme.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 5,
    padding: 14,
  },
  preferenceReviewLabel: {
    color: theme.accentStrong,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  preferenceReviewValue: {
    color: theme.textPrimary,
    fontSize: 14,
    lineHeight: 20,
  },
  preferenceActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 30,
  },
  preferencePrimaryButton: {
    alignItems: 'center',
    backgroundColor: theme.accent,
    borderRadius: 15,
    flex: 1,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 16,
  },
  preferencePrimaryText: {
    color: theme.textOnAccent,
    fontSize: 15,
    fontWeight: '800',
  },
  preferenceSecondaryButton: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 15,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 20,
  },
  preferenceSecondaryText: {
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  preferenceSkipButton: {
    alignSelf: 'center',
    marginTop: 16,
    padding: 10,
  },
  preferenceSkipText: {
    color: theme.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
} as const;
