import { StyleSheet } from 'react-native';
import { theme } from './theme';

// Splash and landing experience surfaces.
export const splashStyles = {
  splashScreen: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  splashBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#080101',
  },
  splashHeaderBar: {
    marginBottom: 0,
    minHeight: 96,
    paddingBottom: 10,
    paddingTop: 34,
    zIndex: 3,
  },
  splashHeaderRow: {
    paddingHorizontal: 34,
  },
  splashHeaderBackButton: {
    minHeight: 44,
    marginTop: 8,
  },
  splashHeaderPillButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(21, 23, 29, 0.94)',
    borderColor: theme.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 44,
    minWidth: 104,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  splashHeaderIconButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(21, 23, 29, 0.94)',
    borderColor: theme.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    marginTop: 8,
    width: 44,
  },
  splashHeaderPillContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
  },
  splashHeaderPillText: {
    color: '#f3f6fb',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  splashHeaderCenterSlot: {
    width: 64,
  },
  splashHeaderSignInButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(21, 23, 29, 0.94)',
    borderColor: theme.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 44,
    minWidth: 96,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  splashHeaderSignInText: {
    color: '#f3f6fb',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  splashBody: {
    alignItems: 'stretch',
    flex: 1,
    paddingHorizontal: 10,
    paddingBottom: 22,
  },
  splashScrollHeaderContent: {
    width: '100%',
  },
  splashScrollHeroSpacer: {
    height: 40,
  },
  splashIntroContent: {
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: 16,
    width: '100%',
  },
  splashFloatingLogo: {
    alignItems: 'center',
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 18,
    zIndex: 5,
  },
  splashLogoImage: {
    height: 196,
    width: 196,
  },
  splashLogoRevealMask: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.bgApp,
  },
  splashSloganBlock: {
    alignItems: 'center',
    gap: 12,
    marginBottom: 24,
    marginTop: 0,
  },
  splashSloganRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 8,
    justifyContent: 'center',
  },
  splashSloganWord: {
    color: '#fff9f3',
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
  },
  splashActionGroup: {
    alignSelf: 'stretch',
    gap: 14,
    marginTop: 8,
    maxWidth: 420,
    paddingHorizontal: 4,
    width: '100%',
  },
  splashFeedSection: {
    alignSelf: 'stretch',
    flex: 1,
    marginTop: 24,
    minHeight: 220,
    width: '100%',
  },
  splashPortalButton: {
    alignItems: 'center',
    backgroundColor: theme.bgRaised,
    borderColor: theme.borderStrong,
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 58,
    paddingHorizontal: 18,
    paddingVertical: 14,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 6,
  },
  splashPortalButtonText: {
    color: theme.textPrimary,
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  splashCreateAccountLink: {
    alignSelf: 'center',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  splashCreateAccountText: {
    color: theme.accent,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  splashSignInOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    zIndex: 40,
  },
  splashSignInModalBackdropPressable: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.bgOverlay,
  },
  splashSignInModalCardWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  splashSignInModalCard: {
    backgroundColor: theme.bgCanvas,
    borderColor: theme.borderStrong,
    borderRadius: 28,
    borderWidth: 1,
    gap: 14,
    maxWidth: 360,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 18,
    width: '100%',
  },
  splashSignInModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 34,
  },
  splashSignInModalHeaderSpacer: {
    height: 32,
    width: 32,
  },
  splashSignInModalCloseButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  splashSignInModalCloseButtonText: {
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  splashSignInModalTitle: {
    color: theme.textPrimary,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  splashSignInModalText: {
    color: theme.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  splashSignInModalActions: {
    gap: 10,
    marginTop: 4,
  },
  splashSignInPrimaryButton: {
    alignItems: 'center',
    backgroundColor: theme.accent,
    borderRadius: 14,
    minHeight: 54,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  splashSignInPrimaryButtonText: {
    color: theme.textOnAccent,
    fontSize: 15,
    fontWeight: '800',
  },
  splashSignInSecondaryButton: {
    alignItems: 'center',
    backgroundColor: theme.bgElevated,
    borderColor: theme.border,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 54,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  splashSignInSecondaryButtonText: {
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  splashSignInTertiaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  splashSignInTertiaryButtonText: {
    color: theme.accent,
    fontSize: 14,
    fontWeight: '800',
    textDecorationLine: 'underline',
  },
} as const;

