"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from .business_sources import BUSINESS_SOURCE_PAGES
from .env import get_bool_env, get_env, get_int_env, load_env_file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_VALUES = load_env_file(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h#v2wxzl1*2%#w*yz=%y0r=x*n+y-_s6i9p!kbosj0_jhige^l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'places.apps.PlacesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


CACHES = {
	'default': {
		'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
		'LOCATION': 'happyhourapp-default-cache',
    },
    'source_fetch': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': str(BASE_DIR / '.django_cache' / 'source_fetch'),
    },
}

SOURCE_FETCH_CACHE_ALIAS = 'source_fetch'
SOURCE_FETCH_CACHE_TIMEOUT = 43200
DISCOVERY_WEBSITE_ENRICHMENT_CACHE_TIMEOUT = 21600
DISCOVERY_WEBSITE_MAX_PROMO_LINKS = 4
DISCOVERY_WEBSITE_LOG_SKIPS = False
DISCOVERY_WEBSITE_FALLBACK_PATHS = (
    '/happy-hour',
    '/happyhour',
    '/specials',
    '/deals',
    '/offers',
    '/promotions',
    '/menu',
    '/menus',
    '/drink-menu',
    '/food-menu',
    '/happy-hour.pdf',
    '/menu.pdf',
)
DISCOVERY_WEBSITE_BLOCKED_HOST_SUFFIXES = (
    'facebook.com',
    'fb.com',
    'instagram.com',
    'x.com',
    'twitter.com',
    'yelp.com',
    'business.site',
    'tripadvisor.com',
    'doordash.com',
    'ubereats.com',
    'grubhub.com',
)
DISCOVERY_WEBSITE_BLOCKED_HOST_PREFIXES = (
    'api.',
    'm.',
)
PLACE_GEOCODE_CACHE_TIMEOUT = 86400
PLACE_GEOCODE_TIMEOUT = 5
PLACE_GEOCODE_URL = 'https://nominatim.openstreetmap.org/search'
PLACE_GEOCODE_USER_AGENT = 'HappyHourApp/1.0'
LISTING_SOURCE_NAME = 'curated_json_places'
DISCOVERY_JSON_PATH = BASE_DIR / 'config' / 'discovered_places.json'
BUSINESS_SOURCE_STRICT_ERRORS = False
BUSINESS_SOURCE_ALLOWED_CITIES = ('ventura', 'oxnard', 'camarillo')
OSM_PLACE_DISCOVERY_URL = 'https://overpass-api.de/api/interpreter'
OSM_PLACE_DISCOVERY_TIMEOUT = 45
OSM_PLACE_DISCOVERY_CACHE_TIMEOUT = 3600
OSM_PLACE_DISCOVERY_USER_AGENT = 'HappyHourApp/1.0'
OSM_PLACE_MIN_METADATA_SCORE = 2
OSM_PLACE_EXCLUDED_BUSINESSES = (
    ('ventura', 'Barrelhouse 101'),
)
OSM_PLACE_EXCLUDED_EXTERNAL_IDS = (
    'osm:way:410595933',
)
HERE_DISCOVERY_URL = 'https://discover.search.hereapi.com/v1/discover'
HERE_API_KEY = get_env('HERE_API_KEY', ENV_VALUES, '')
HERE_TIMEOUT = 20
HERE_CACHE_TIMEOUT = 3600
HERE_PAGE_SIZE = 100
HERE_MAX_RESULTS = 600
HERE_USER_AGENT = 'HappyHourApp/1.0'
HERE_PLACE_EXCLUDED_BUSINESSES = (
    ('camarillo', 'Institution Ale Company'),
)
HERE_PLACE_EXCLUDED_EXTERNAL_IDS = ()
HERE_MONTHLY_LIMIT = get_int_env('HERE_MONTHLY_LIMIT', ENV_VALUES, 250000)
HERE_MONTHLY_RESERVE = get_int_env('HERE_MONTHLY_RESERVE', ENV_VALUES, 1000)
TOMTOM_CATEGORY_SEARCH_URL = 'https://api.tomtom.com/search/2/categorySearch/{query}.json'
TOMTOM_API_KEY = get_env('TOMTOM_API_KEY', ENV_VALUES, '')
TOMTOM_TIMEOUT = 20
TOMTOM_CACHE_TIMEOUT = 3600
TOMTOM_PAGE_SIZE = 100
TOMTOM_MAX_RESULTS = 200
TOMTOM_USER_AGENT = 'HappyHourApp/1.0'
TOMTOM_DAILY_LIMIT = get_int_env('TOMTOM_DAILY_LIMIT', ENV_VALUES, 50000)
TOMTOM_DAILY_RESERVE = get_int_env('TOMTOM_DAILY_RESERVE', ENV_VALUES, 250)
YELP_FUSION_API_URL = 'https://api.yelp.com/v3/businesses/search'
YELP_FUSION_API_KEY = get_env('YELP_FUSION_API_KEY', ENV_VALUES, '')
YELP_FUSION_TIMEOUT = 20
YELP_FUSION_CACHE_TIMEOUT = 3600
YELP_FUSION_PAGE_SIZE = 50
YELP_FUSION_MAX_RESULTS = 150


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        'http://127.0.0.1:3000',
        'http://localhost:3000',
        'http://127.0.0.1:8081',
        'http://localhost:8081',
    ]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

EMAIL_BACKEND = get_env('EMAIL_BACKEND', ENV_VALUES, 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = get_env('EMAIL_HOST', ENV_VALUES, get_env('BREVO_SMTP_HOST', ENV_VALUES, 'localhost'))
EMAIL_PORT = get_int_env('EMAIL_PORT', ENV_VALUES, get_int_env('BREVO_SMTP_PORT', ENV_VALUES, 25))
EMAIL_HOST_USER = get_env('EMAIL_HOST_USER', ENV_VALUES, get_env('BREVO_SMTP_USER', ENV_VALUES, ''))
EMAIL_HOST_PASSWORD = get_env('EMAIL_HOST_PASSWORD', ENV_VALUES, get_env('BREVO_SMTP_KEY', ENV_VALUES, ''))
EMAIL_USE_TLS = get_bool_env('EMAIL_USE_TLS', ENV_VALUES, False)
EMAIL_USE_SSL = get_bool_env('EMAIL_USE_SSL', ENV_VALUES, False)
EMAIL_TIMEOUT = get_int_env('EMAIL_TIMEOUT', ENV_VALUES, 20)
DEFAULT_FROM_EMAIL = get_env('DEFAULT_FROM_EMAIL', ENV_VALUES, 'noreply@happyhourapp.local')
SERVER_EMAIL = get_env('SERVER_EMAIL', ENV_VALUES, DEFAULT_FROM_EMAIL)

PROFILE_EMAIL_VERIFICATION_URL_BASE = get_env('PROFILE_EMAIL_VERIFICATION_URL_BASE', ENV_VALUES, 'http://127.0.0.1:8000/api/profiles/verify-email')
PROFILE_EMAIL_VERIFICATION_SUCCESS_URL = get_env('PROFILE_EMAIL_VERIFICATION_SUCCESS_URL', ENV_VALUES, '')
PROFILE_EMAIL_VERIFICATION_FAILURE_URL = get_env('PROFILE_EMAIL_VERIFICATION_FAILURE_URL', ENV_VALUES, '')
PROFILE_EMAIL_VERIFICATION_RETURN_URL = get_env('PROFILE_EMAIL_VERIFICATION_RETURN_URL', ENV_VALUES, '')
PROFILE_APP_LINK_URL = get_env('PROFILE_APP_LINK_URL', ENV_VALUES, PROFILE_EMAIL_VERIFICATION_RETURN_URL)
PROFILE_EMAIL_VERIFICATION_CODE_TTL_SECONDS = get_int_env('PROFILE_EMAIL_VERIFICATION_CODE_TTL_SECONDS', ENV_VALUES, 60)
PROFILE_PASSWORD_RESET_URL_BASE = get_env('PROFILE_PASSWORD_RESET_URL_BASE', ENV_VALUES, 'http://127.0.0.1:8000/api/profiles/reset-password')
PROFILE_TWO_FACTOR_ISSUER = get_env('PROFILE_TWO_FACTOR_ISSUER', ENV_VALUES, 'DiningDealz')
PROFILE_BILLING_PORTAL_URL = get_env('PROFILE_BILLING_PORTAL_URL', ENV_VALUES, 'https://example.com/billing')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
