"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse

from django.urls import reverse_lazy
from django.templatetags.static import static

from .business_sources import BUSINESS_SOURCE_PAGES
from .env import get_bool_env, get_env, get_int_env, get_list_env, load_env_file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_VALUES = load_env_file(BASE_DIR)


def _is_truthy_env(name):
    value = str(get_env(name, ENV_VALUES, '')).strip().lower()
    return value in {'1', 'true', 'yes', 'on'}


IS_RENDER = _is_truthy_env('RENDER') or bool(get_env('RENDER_EXTERNAL_HOSTNAME', ENV_VALUES, '').strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('DJANGO_SECRET_KEY', ENV_VALUES, 'django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env('DJANGO_DEBUG', ENV_VALUES, not IS_RENDER)


def _append_unique(items, value):
    if value and value not in items:
        items.append(value)


def _build_allowed_hosts(debug):
    configured_hosts = get_list_env('DJANGO_ALLOWED_HOSTS', ENV_VALUES, '')
    allowed_hosts = configured_hosts or (['*'] if debug else ['127.0.0.1', 'localhost'])

    render_hostname = get_env('RENDER_EXTERNAL_HOSTNAME', ENV_VALUES, '').strip()
    _append_unique(allowed_hosts, render_hostname)
    return allowed_hosts


def _build_csrf_trusted_origins():
    trusted_origins = get_list_env('DJANGO_CSRF_TRUSTED_ORIGINS', ENV_VALUES, '')
    render_hostname = get_env('RENDER_EXTERNAL_HOSTNAME', ENV_VALUES, '').strip()
    if render_hostname:
        _append_unique(trusted_origins, f'https://{render_hostname}')
    return trusted_origins


def _build_cors_allowed_origins(debug):
    configured_origins = get_list_env('CORS_ALLOWED_ORIGINS', ENV_VALUES, '')
    if configured_origins:
        return configured_origins

    if debug:
        return []

    return [
        'http://127.0.0.1:3000',
        'http://localhost:3000',
        'http://127.0.0.1:8081',
        'http://localhost:8081',
    ]


ALLOWED_HOSTS = _build_allowed_hosts(DEBUG)
CSRF_TRUSTED_ORIGINS = _build_csrf_trusted_origins()
ADMIN_URL_PATH = get_env('ADMIN_URL_PATH', ENV_VALUES, 'admin').strip().strip('/') or 'admin'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = get_bool_env('DJANGO_SECURE_SSL_REDIRECT', ENV_VALUES, IS_RENDER)
SESSION_COOKIE_SECURE = get_bool_env('DJANGO_SESSION_COOKIE_SECURE', ENV_VALUES, IS_RENDER)
CSRF_COOKIE_SECURE = get_bool_env('DJANGO_CSRF_COOKIE_SECURE', ENV_VALUES, IS_RENDER)
SECURE_HSTS_SECONDS = get_int_env('DJANGO_SECURE_HSTS_SECONDS', ENV_VALUES, 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_bool_env('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', ENV_VALUES, False)
SECURE_HSTS_PRELOAD = get_bool_env('DJANGO_SECURE_HSTS_PRELOAD', ENV_VALUES, False)


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'places.apps.PlacesConfig',
]

UNFOLD = {
    'SITE_TITLE': 'DiningDealz Admin',
    'SITE_HEADER': 'DiningDealz',
    'SITE_SUBHEADER': 'Discover - Eat - Save',
    'SITE_URL': 'https://www.diningdealz.com',
    'SITE_SYMBOL': 'restaurant',
    'THEME': 'dark',
    'BORDER_RADIUS': '6px',
    'COLORS': {
        'base': {
            '50': '#f4f4f4',
            '100': '#e5e5e5',
            '200': '#c9c9c9',
            '300': '#a3a3a3',
            '400': '#737373',
            '500': '#525252',
            '600': '#333333',
            '700': '#202020',
            '800': '#111111',
            '900': '#050505',
            '950': '#000000',
        },
        'primary': {
            '50': '#fff0f1',
            '100': '#ffd9dd',
            '200': '#ffb1b9',
            '300': '#ff7a87',
            '400': '#ff4658',
            '500': '#f21f36',
            '600': '#d80f29',
            '700': '#b10d23',
            '800': '#8d1021',
            '900': '#681321',
            '950': '#400a15',
        },
        'font': {
            'subtle-light': '#7d6254',
            'subtle-dark': '#d8b7a0',
            'default-light': '#4a2a20',
            'default-dark': '#fceede',
            'important-light': '#24120e',
            'important-dark': '#fff8ef',
        },
    },
    'STYLES': [
        lambda request: static('places/admin/unfold_brand.css'),
    ],
    'DASHBOARD_CALLBACK': 'places.services.admin_operations.dashboard_callback',
    'COMMAND': {
        'search_models': True,
        'search_callback': 'places.services.admin_operations.command_search',
    },
    'SIDEBAR': {
        'show_search': True,
        'navigation': [
            {
                'title': 'Operations',
                'items': [
                    {
                        'title': 'Operations Dashboard',
                        'icon': 'dashboard',
                        'link': reverse_lazy('happyhour_admin:index'),
                    },
                    {
                        'title': 'Claim Review',
                        'icon': 'rate_review',
                        'link': reverse_lazy('happyhour_admin:operations_review_queue'),
                        'badge': 'places.services.admin_operations.overdue_claim_badge',
                        'badge_variant': 'danger',
                        'badge_style': 'solid',
                    },
                    {
                        'title': 'Content Reports',
                        'icon': 'flag',
                        'link': reverse_lazy('happyhour_admin:operations_report_queue'),
                        'badge': 'places.services.admin_operations.open_report_badge',
                        'badge_variant': 'danger',
                        'badge_style': 'solid',
                    },
                    {
                        'title': 'Catalog Health',
                        'icon': 'health_and_safety',
                        'link': reverse_lazy('happyhour_admin:operations_catalog_health'),
                        'badge': 'places.services.admin_operations.catalog_attention_badge',
                        'badge_variant': 'warning',
                        'badge_style': 'solid',
                    },
                    {
                        'title': 'Analytics',
                        'icon': 'query_stats',
                        'link': reverse_lazy('happyhour_admin:operations_analytics'),
                    },
                    {
                        'title': 'Audit Timeline',
                        'icon': 'history',
                        'link': reverse_lazy('happyhour_admin:operations_audit_timeline'),
                    },
                ],
            },
            {
                'title': 'Accounts and Claims',
                'separator': True,
                'items': [
                    {
                        'title': 'Customer Accounts',
                        'icon': 'person',
                        'link': reverse_lazy('happyhour_admin:places_customeraccount_changelist'),
                    },
                    {
                        'title': 'Business Accounts',
                        'icon': 'storefront',
                        'link': reverse_lazy('happyhour_admin:places_businessaccount_changelist'),
                    },
                    {
                        'title': 'Business Claims',
                        'icon': 'assignment_ind',
                        'link': reverse_lazy('happyhour_admin:places_businessclaim_changelist'),
                        'badge': 'places.services.admin_operations.pending_claim_badge',
                        'badge_variant': 'warning',
                        'badge_style': 'solid',
                    },
                    {
                        'title': 'Business Memberships',
                        'icon': 'workspace_premium',
                        'link': reverse_lazy('happyhour_admin:places_businessmembership_changelist'),
                        'badge': 'places.services.admin_operations.active_membership_badge',
                        'badge_variant': 'success',
                        'badge_style': 'solid',
                    },
                ],
            },
            {
                'title': 'Businesses and Growth',
                'separator': True,
                'items': [
                    {
                        'title': 'List of Businesses',
                        'icon': 'store',
                        'link': reverse_lazy('happyhour_admin:places_listingsnapshot_changelist'),
                        'badge': 'places.services.admin_operations.catalog_attention_badge',
                        'badge_variant': 'warning',
                        'badge_style': 'solid',
                    },
                    {
                        'title': 'Deleted Businesses',
                        'icon': 'delete',
                        'link': reverse_lazy('happyhour_admin:places_deletedbusiness_changelist'),
                    },
                    {
                        'title': 'Business Posts',
                        'icon': 'post_add',
                        'link': reverse_lazy('happyhour_admin:places_businesspost_changelist'),
                    },
                    {
                        'title': 'Sponsored Campaigns',
                        'icon': 'campaign',
                        'link': reverse_lazy('happyhour_admin:places_sponsoredcampaign_changelist'),
                        'badge': 'places.services.admin_operations.active_campaign_badge',
                        'badge_variant': 'success',
                        'badge_style': 'solid',
                    },
                    {
                        'title': 'Feed Impressions',
                        'icon': 'visibility',
                        'link': reverse_lazy('happyhour_admin:places_feedimpression_changelist'),
                    },
                    {
                        'title': 'Feed Engagements',
                        'icon': 'touch_app',
                        'link': reverse_lazy('happyhour_admin:places_feedengagement_changelist'),
                    },
                    {
                        'title': 'Favorite Businesses',
                        'icon': 'bookmark',
                        'link': reverse_lazy('happyhour_admin:places_favoritebusiness_changelist'),
                    },
                    {
                        'title': 'Business Notifications',
                        'icon': 'notifications',
                        'link': reverse_lazy('happyhour_admin:places_favoritebusinessnotification_changelist'),
                    },
                    {
                        'title': 'Direct Message Threads',
                        'icon': 'forum',
                        'link': reverse_lazy('happyhour_admin:places_businessdirectmessagethread_changelist'),
                    },
                    {
                        'title': 'Direct Messages',
                        'icon': 'chat',
                        'link': reverse_lazy('happyhour_admin:places_businessdirectmessage_changelist'),
                    },
                ],
            },
            {
                'title': 'Administration',
                'separator': True,
                'items': [
                    {
                        'title': 'Staff Users',
                        'icon': 'manage_accounts',
                        'link': reverse_lazy('happyhour_admin:auth_user_changelist'),
                    },
                    {
                        'title': 'Groups',
                        'icon': 'group',
                        'link': reverse_lazy('happyhour_admin:auth_group_changelist'),
                    },
                ],
            },
        ],
    },
}

# Claims are highlighted as overdue in the operations queue after this window.
BUSINESS_CLAIM_REVIEW_SLA_HOURS = get_int_env('BUSINESS_CLAIM_REVIEW_SLA_HOURS', ENV_VALUES, 48)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if IS_RENDER:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


def _build_sqlite_database_config(base_dir):
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': base_dir / 'db.sqlite3',
    }


def _postgres_database_config_from_url(database_url):
    parsed = urlparse(database_url)
    if parsed.scheme.lower() not in {'postgres', 'postgresql'}:
        raise ValueError('DATABASE_URL must use a postgres:// or postgresql:// scheme.')

    database_name = unquote(parsed.path.lstrip('/'))
    if not database_name:
        raise ValueError('DATABASE_URL must include a database name.')

    options = {
        key: value
        for key, value in parse_qsl(parsed.query, keep_blank_values=False)
        if value != ''
    }
    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': database_name,
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
        'CONN_MAX_AGE': get_int_env('DATABASE_CONN_MAX_AGE', ENV_VALUES, 600),
    }
    if options:
        config['OPTIONS'] = options
    return config


def _build_postgres_database_config_from_env():
    database_name = get_env('PGDATABASE', ENV_VALUES, get_env('POSTGRES_DB', ENV_VALUES, '')).strip()
    if not database_name:
        return None

    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': database_name,
        'USER': get_env('PGUSER', ENV_VALUES, get_env('POSTGRES_USER', ENV_VALUES, '')).strip(),
        'PASSWORD': get_env('PGPASSWORD', ENV_VALUES, get_env('POSTGRES_PASSWORD', ENV_VALUES, '')).strip(),
        'HOST': get_env('PGHOST', ENV_VALUES, get_env('POSTGRES_HOST', ENV_VALUES, '')).strip(),
        'PORT': get_env('PGPORT', ENV_VALUES, get_env('POSTGRES_PORT', ENV_VALUES, '5432')).strip(),
        'CONN_MAX_AGE': get_int_env('DATABASE_CONN_MAX_AGE', ENV_VALUES, 600),
    }
    ssl_mode = get_env('PGSSLMODE', ENV_VALUES, get_env('POSTGRES_SSLMODE', ENV_VALUES, '')).strip()
    if ssl_mode:
        config['OPTIONS'] = {'sslmode': ssl_mode}
    return config


def _build_default_database_config(base_dir):
    database_url = get_env('DATABASE_URL', ENV_VALUES, '').strip()
    if database_url:
        return _postgres_database_config_from_url(database_url)

    postgres_config = _build_postgres_database_config_from_env()
    if postgres_config is not None:
        return postgres_config

    return _build_sqlite_database_config(base_dir)

DATABASES = {
    'default': _build_default_database_config(BASE_DIR)
}


def _build_discovery_json_path(base_dir, database_config):
    configured_path = get_env('DISCOVERY_JSON_PATH', ENV_VALUES, '').strip()
    if configured_path:
        return Path(configured_path)

    if database_config.get('ENGINE') == 'django.db.backends.postgresql':
        return base_dir / '.runtime' / 'discovered_places.json'

    return base_dir / 'config' / 'discovered_places.json'


REDIS_URL = get_env('REDIS_URL', ENV_VALUES, '').strip()
CACHE_KEY_PREFIX = get_env('CACHE_KEY_PREFIX', ENV_VALUES, 'happyhourapp')
SOURCE_CACHE_KEY_PREFIX = get_env('SOURCE_CACHE_KEY_PREFIX', ENV_VALUES, f'{CACHE_KEY_PREFIX}-source')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'happyhourapp-default-cache',
    },
    'source_fetch': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'happyhourapp-source-fetch-cache',
    },
}

if REDIS_URL:
    CACHES['default'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': CACHE_KEY_PREFIX,
    }
    CACHES['source_fetch'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': SOURCE_CACHE_KEY_PREFIX,
    }

SOURCE_FETCH_CACHE_ALIAS = 'source_fetch'
SOURCE_FETCH_CACHE_TIMEOUT = 43200
SOURCE_PLACE_PAYLOAD_CACHE_ALIAS = SOURCE_FETCH_CACHE_ALIAS
SOURCE_PLACE_PAYLOAD_CACHE_TIMEOUT = 300
ADMIN_OPERATIONS_CACHE_TIMEOUT = get_int_env('ADMIN_OPERATIONS_CACHE_TIMEOUT', ENV_VALUES, 30)
ADMIN_BADGE_CACHE_TIMEOUT = get_int_env('ADMIN_BADGE_CACHE_TIMEOUT', ENV_VALUES, 15)
ADMIN_STORAGE_CACHE_TIMEOUT = get_int_env('ADMIN_STORAGE_CACHE_TIMEOUT', ENV_VALUES, 60)
ADMIN_CATALOG_HEALTH_PAGE_SIZE = get_int_env('ADMIN_CATALOG_HEALTH_PAGE_SIZE', ENV_VALUES, 50)
DISCOVERY_WEBSITE_ENRICHMENT_CACHE_TIMEOUT = 21600
DISCOVERY_WEBSITE_MAX_PROMO_LINKS = 4
DISCOVERY_WEBSITE_LOG_SKIPS = False
DISCOVERY_WEBSITE_FALLBACK_PATHS = (
    '/happy-hour',
    '/happyhour',
    '/specials',
    '/deals',
    '/offers',
    '/promotions',
    '/menu',
    '/menus',
    '/drink-menu',
    '/food-menu',
    '/happy-hour.pdf',
    '/menu.pdf',
)
DISCOVERY_WEBSITE_BLOCKED_HOST_SUFFIXES = (
    'facebook.com',
    'fb.com',
    'instagram.com',
    'x.com',
    'twitter.com',
    'yelp.com',
    'business.site',
    'tripadvisor.com',
    'doordash.com',
    'ubereats.com',
    'grubhub.com',
)
DISCOVERY_WEBSITE_BLOCKED_HOST_PREFIXES = (
    'api.',
    'm.',
)
LISTING_SOURCE_NAME = 'curated_json_places'
DISCOVERY_JSON_SEED_PATH = BASE_DIR / 'config' / 'discovered_places.json'
DISCOVERY_JSON_PATH = _build_discovery_json_path(BASE_DIR, DATABASES['default'])
DISCOVERY_JSON_BOOTSTRAP_FROM_SEED = get_bool_env(
    'DISCOVERY_JSON_BOOTSTRAP_FROM_SEED',
    ENV_VALUES,
    DATABASES['default'].get('ENGINE') == 'django.db.backends.postgresql',
)
BUSINESS_SOURCE_STRICT_ERRORS = False
BUSINESS_SOURCE_IMPORT_IMAGES = get_bool_env('BUSINESS_SOURCE_IMPORT_IMAGES', ENV_VALUES, False)
BUSINESS_SOURCE_ALLOWED_CITIES = ('ventura', 'oxnard', 'camarillo')
IMAGE_MODERATION_PROVIDER = get_env(
    'IMAGE_MODERATION_PROVIDER',
    ENV_VALUES,
    'local_nudenet' if IS_RENDER else 'disabled',
).strip().lower()
IMAGE_MODERATION_BLOCK_SCORE_PERCENT = get_int_env('IMAGE_MODERATION_BLOCK_SCORE_PERCENT', ENV_VALUES, 65)
IMAGE_MODERATION_CACHE_ALIAS = get_env('IMAGE_MODERATION_CACHE_ALIAS', ENV_VALUES, 'default').strip() or 'default'
IMAGE_MODERATION_CACHE_TIMEOUT = get_int_env('IMAGE_MODERATION_CACHE_TIMEOUT', ENV_VALUES, 86400)
IMAGE_MODERATION_MAX_UPLOAD_BYTES = get_int_env('IMAGE_MODERATION_MAX_UPLOAD_BYTES', ENV_VALUES, 16 * 1024 * 1024)
IMAGE_MODERATION_FAIL_CLOSED = get_bool_env('IMAGE_MODERATION_FAIL_CLOSED', ENV_VALUES, IS_RENDER)
PDF_UPLOAD_MAX_BYTES = get_int_env('PDF_UPLOAD_MAX_BYTES', ENV_VALUES, 10 * 1024 * 1024)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PRIVATE_MEDIA_URL = '/private-media/'
PRIVATE_MEDIA_ROOT = BASE_DIR / 'private-media'
MEDIA_STORAGE_BACKEND = (
    get_env('MEDIA_STORAGE_BACKEND', ENV_VALUES, 'supabase').strip().lower()
    if IS_RENDER
    else 'local'
)
DIRECT_MESSAGE_MEDIA_STORAGE_BACKEND = (
    get_env('DIRECT_MESSAGE_MEDIA_STORAGE_BACKEND', ENV_VALUES, '').strip().lower()
    if IS_RENDER
    else ''
)
PRIVATE_MEDIA_STORAGE_BACKEND = (
    get_env('PRIVATE_MEDIA_STORAGE_BACKEND', ENV_VALUES, 'supabase').strip().lower()
    if IS_RENDER
    else 'local'
)
SUPABASE_STORAGE_BUCKET = get_env('SUPABASE_STORAGE_BUCKET', ENV_VALUES, '')
SUPABASE_PRIVATE_STORAGE_BUCKET = get_env('SUPABASE_PRIVATE_STORAGE_BUCKET', ENV_VALUES, '')
SUPABASE_STORAGE_ENDPOINT = get_env('SUPABASE_STORAGE_ENDPOINT', ENV_VALUES, '')
SUPABASE_STORAGE_REGION = get_env('SUPABASE_STORAGE_REGION', ENV_VALUES, 'us-east-1')
SUPABASE_STORAGE_ACCESS_KEY = get_env('SUPABASE_STORAGE_ACCESS_KEY', ENV_VALUES, '')
SUPABASE_STORAGE_SECRET_KEY = get_env('SUPABASE_STORAGE_SECRET_KEY', ENV_VALUES, '')
SUPABASE_STORAGE_PUBLIC_URL_BASE = get_env('SUPABASE_STORAGE_PUBLIC_URL_BASE', ENV_VALUES, '').rstrip('/')
SUPABASE_PRIVATE_STORAGE_SIGNED_URL_EXPIRE_SECONDS = get_int_env('SUPABASE_PRIVATE_STORAGE_SIGNED_URL_EXPIRE_SECONDS', ENV_VALUES, 3600)
STATICFILES_STORAGE_BACKEND = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
    if IS_RENDER
    else 'django.contrib.staticfiles.storage.StaticFilesStorage'
)

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'private_media': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': PRIVATE_MEDIA_ROOT,
            'base_url': PRIVATE_MEDIA_URL,
        },
    },
    'direct_messages': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': PRIVATE_MEDIA_ROOT,
            'base_url': PRIVATE_MEDIA_URL,
        },
    },
    'staticfiles': {
        'BACKEND': STATICFILES_STORAGE_BACKEND,
    },
}
MEDIA_PUBLIC_BASE_URL = MEDIA_URL
_direct_message_storage_backend = DIRECT_MESSAGE_MEDIA_STORAGE_BACKEND or PRIVATE_MEDIA_STORAGE_BACKEND

if MEDIA_STORAGE_BACKEND == 'supabase':
    missing_supabase_settings = [
        setting_name
        for setting_name, setting_value in (
            ('SUPABASE_STORAGE_BUCKET', SUPABASE_STORAGE_BUCKET),
            ('SUPABASE_STORAGE_ENDPOINT', SUPABASE_STORAGE_ENDPOINT),
            ('SUPABASE_STORAGE_ACCESS_KEY', SUPABASE_STORAGE_ACCESS_KEY),
            ('SUPABASE_STORAGE_SECRET_KEY', SUPABASE_STORAGE_SECRET_KEY),
            ('SUPABASE_STORAGE_PUBLIC_URL_BASE', SUPABASE_STORAGE_PUBLIC_URL_BASE),
        )
        if not setting_value
    ]
    if missing_supabase_settings:
        missing_list = ', '.join(missing_supabase_settings)
        raise ValueError(f'Supabase media storage is enabled but missing: {missing_list}')

    STORAGES['default'] = {
        'BACKEND': 'config.storage.SupabaseMediaStorage',
        'OPTIONS': {
            'bucket_name': SUPABASE_STORAGE_BUCKET,
            'access_key': SUPABASE_STORAGE_ACCESS_KEY,
            'secret_key': SUPABASE_STORAGE_SECRET_KEY,
            'endpoint_url': SUPABASE_STORAGE_ENDPOINT,
            'region_name': SUPABASE_STORAGE_REGION,
            'default_acl': 'public-read',
            'querystring_auth': False,
            'file_overwrite': False,
        },
    }
    MEDIA_PUBLIC_BASE_URL = SUPABASE_STORAGE_PUBLIC_URL_BASE

if PRIVATE_MEDIA_STORAGE_BACKEND == 'supabase':
    missing_private_supabase_settings = [
        setting_name
        for setting_name, setting_value in (
            ('SUPABASE_PRIVATE_STORAGE_BUCKET', SUPABASE_PRIVATE_STORAGE_BUCKET),
            ('SUPABASE_STORAGE_ENDPOINT', SUPABASE_STORAGE_ENDPOINT),
            ('SUPABASE_STORAGE_ACCESS_KEY', SUPABASE_STORAGE_ACCESS_KEY),
            ('SUPABASE_STORAGE_SECRET_KEY', SUPABASE_STORAGE_SECRET_KEY),
        )
        if not setting_value
    ]
    if missing_private_supabase_settings:
        missing_list = ', '.join(missing_private_supabase_settings)
        raise ValueError(f'Supabase private media storage is enabled but missing: {missing_list}')

    STORAGES['private_media'] = {
        'BACKEND': 'config.storage.SupabasePrivateMediaStorage',
        'OPTIONS': {
            'bucket_name': SUPABASE_PRIVATE_STORAGE_BUCKET,
            'access_key': SUPABASE_STORAGE_ACCESS_KEY,
            'secret_key': SUPABASE_STORAGE_SECRET_KEY,
            'endpoint_url': SUPABASE_STORAGE_ENDPOINT,
            'region_name': SUPABASE_STORAGE_REGION,
            'default_acl': 'private',
            'querystring_auth': True,
            'querystring_expire': SUPABASE_PRIVATE_STORAGE_SIGNED_URL_EXPIRE_SECONDS,
            'file_overwrite': False,
        },
    }

if _direct_message_storage_backend == 'supabase':
    STORAGES['direct_messages'] = STORAGES['private_media']

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = _build_cors_allowed_origins(DEBUG)

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'profile_login': get_env('THROTTLE_PROFILE_LOGIN', ENV_VALUES, '10/minute'),
        'profile_signup': get_env('THROTTLE_PROFILE_SIGNUP', ENV_VALUES, '300/hour'),
        'profile_email_verification': get_env('THROTTLE_PROFILE_EMAIL_VERIFICATION', ENV_VALUES, '10/minute'),
        'profile_email_verification_resend': get_env('THROTTLE_PROFILE_EMAIL_VERIFICATION_RESEND', ENV_VALUES, '3/minute'),
        'profile_password_recovery': get_env('THROTTLE_PROFILE_PASSWORD_RECOVERY', ENV_VALUES, '10/hour'),
        'profile_support_contact': get_env('THROTTLE_PROFILE_SUPPORT_CONTACT', ENV_VALUES, '10/hour'),
        'profile_content_report': get_env('THROTTLE_PROFILE_CONTENT_REPORT', ENV_VALUES, '10/hour'),
        'profile_user_mutation': get_env('THROTTLE_PROFILE_USER_MUTATION', ENV_VALUES, '120/minute'),
        'direct_message_send': get_env('THROTTLE_DIRECT_MESSAGE_SEND', ENV_VALUES, '30/minute'),
    },
}

EMAIL_BACKEND = get_env('EMAIL_BACKEND', ENV_VALUES, 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = get_env('EMAIL_HOST', ENV_VALUES, get_env('BREVO_SMTP_HOST', ENV_VALUES, 'localhost'))
EMAIL_PORT = get_int_env('EMAIL_PORT', ENV_VALUES, get_int_env('BREVO_SMTP_PORT', ENV_VALUES, 25))
EMAIL_HOST_USER = get_env('EMAIL_HOST_USER', ENV_VALUES, get_env('BREVO_SMTP_USER', ENV_VALUES, ''))
EMAIL_HOST_PASSWORD = get_env('EMAIL_HOST_PASSWORD', ENV_VALUES, get_env('BREVO_SMTP_KEY', ENV_VALUES, ''))
_EMAIL_USE_TLS_DEFAULT = EMAIL_PORT == 587 and bool(EMAIL_HOST_USER)
_EMAIL_USE_SSL_DEFAULT = EMAIL_PORT == 465 and bool(EMAIL_HOST_USER)
EMAIL_USE_TLS = get_bool_env('EMAIL_USE_TLS', ENV_VALUES, _EMAIL_USE_TLS_DEFAULT)
EMAIL_USE_SSL = get_bool_env('EMAIL_USE_SSL', ENV_VALUES, _EMAIL_USE_SSL_DEFAULT)
EMAIL_TIMEOUT = get_int_env('EMAIL_TIMEOUT', ENV_VALUES, 20)
DEFAULT_FROM_EMAIL = get_env('DEFAULT_FROM_EMAIL', ENV_VALUES, 'noreply@diningdealz.local')
SERVER_EMAIL = get_env('SERVER_EMAIL', ENV_VALUES, DEFAULT_FROM_EMAIL)

PROFILE_APP_LINK_URL = get_env('PROFILE_APP_LINK_URL', ENV_VALUES, '')
PROFILE_USERNAME_RECOVERY_URL_BASE = get_env('PROFILE_USERNAME_RECOVERY_URL_BASE', ENV_VALUES, 'diningdealz://forgot-username')
PROFILE_EMAIL_VERIFICATION_CODE_TTL_SECONDS = get_int_env('PROFILE_EMAIL_VERIFICATION_CODE_TTL_SECONDS', ENV_VALUES, 60)
PROFILE_PASSWORD_RESET_URL_BASE = get_env('PROFILE_PASSWORD_RESET_URL_BASE', ENV_VALUES, 'diningdealz://forgot-password')
PROFILE_PASSWORD_RESET_TOKEN_TTL_SECONDS = get_int_env('PROFILE_PASSWORD_RESET_TOKEN_TTL_SECONDS', ENV_VALUES, 3600)
PROFILE_TWO_FACTOR_ISSUER = get_env('PROFILE_TWO_FACTOR_ISSUER', ENV_VALUES, 'DiningDealz')
PROFILE_BILLING_PORTAL_URL = get_env('PROFILE_BILLING_PORTAL_URL', ENV_VALUES, 'https://example.com/billing')
EXPO_PUSH_NOTIFICATIONS_ENABLED = get_bool_env('EXPO_PUSH_NOTIFICATIONS_ENABLED', ENV_VALUES, True)
EXPO_PUSH_API_URL = get_env('EXPO_PUSH_API_URL', ENV_VALUES, 'https://exp.host/--/api/v2/push/send')
EXPO_PUSH_TIMEOUT = get_int_env('EXPO_PUSH_TIMEOUT', ENV_VALUES, 10)
HAPPY_HOUR_NOTIFICATION_SECRET = get_env('HAPPY_HOUR_NOTIFICATION_SECRET', ENV_VALUES, '').strip()
HAPPY_HOUR_NOTIFICATION_WINDOW_MINUTES = get_int_env('HAPPY_HOUR_NOTIFICATION_WINDOW_MINUTES', ENV_VALUES, 10)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
