from django.urls import path

from .views import (
    BusinessLocationUpdateView,
    BusinessSignupView,
    CustomerSignupView,
    DealListView,
    DiscoveryEnrichmentStatusView,
    DisableTwoFactorView,
    HealthCheckView,
    LoginView,
    ManualBusinessSignupView,
    PasswordResetRequestView,
    PasswordResetView,
    PlaceDetailView,
    PlaceListView,
    ConfirmTwoFactorView,
    ProfileDashboardView,
    ResendEmailVerificationCodeView,
    ResendVerificationEmailView,
    ToggleTwoFactorView,
    UsernameReminderView,
    VerifyEmailCodeView,
    VerifyEmailView,
)


urlpatterns = [
    path('health/', HealthCheckView.as_view(), name='health-check'),
    path('places/discovery-status/', DiscoveryEnrichmentStatusView.as_view(), name='place-discovery-status'),
    path('places/', PlaceListView.as_view(), name='place-list'),
    path('places/<slug:slug>/', PlaceDetailView.as_view(), name='place-detail'),
    path('deals/', DealListView.as_view(), name='deal-list'),
    path('profiles/login/', LoginView.as_view(), name='profile-login'),
    path('profiles/recover-username/', UsernameReminderView.as_view(), name='profile-recover-username'),
    path('profiles/password-reset-request/', PasswordResetRequestView.as_view(), name='profile-password-reset-request'),
    path('profiles/reset-password/<str:token>/', PasswordResetView.as_view(), name='profile-password-reset'),
    path('profiles/me/', ProfileDashboardView.as_view(), name='profile-dashboard'),
    path('profiles/business-location/', BusinessLocationUpdateView.as_view(), name='profile-business-location'),
    path('profiles/resend-verification-code/', ResendEmailVerificationCodeView.as_view(), name='profile-resend-verification-code'),
    path('profiles/resend-verification/', ResendVerificationEmailView.as_view(), name='profile-resend-verification'),
    path('profiles/two-factor/', ToggleTwoFactorView.as_view(), name='profile-toggle-two-factor'),
    path('profiles/two-factor/confirm/', ConfirmTwoFactorView.as_view(), name='profile-confirm-two-factor'),
    path('profiles/two-factor/disable/', DisableTwoFactorView.as_view(), name='profile-disable-two-factor'),
    path('profiles/verify-email-code/', VerifyEmailCodeView.as_view(), name='profile-verify-email-code'),
    path('profiles/verify-email/<str:token>/', VerifyEmailView.as_view(), name='profile-verify-email'),
    path('profiles/customer-signup/', CustomerSignupView.as_view(), name='customer-signup'),
    path('profiles/business-signup/', BusinessSignupView.as_view(), name='business-signup'),
    path('profiles/manual-business-signup/', ManualBusinessSignupView.as_view(), name='manual-business-signup'),
]