from django.urls import path

from .views import (
    BusinessLocationTrackingPreferenceView,
    BusinessLocationUpdateView,
    BusinessSignupView,
    ContactSupportView,
    CustomerSignupView,
    DeleteAccountView,
    DealListView,
    DirectMessageBlockDetailView,
    DirectMessageBlocksView,
    DirectMessageThreadDetailView,
    DirectMessageThreadsView,
    DiscoveryEnrichmentStatusView,
    DisableTwoFactorView,
    FeedEngagementView,
    FeedImpressionView,
    FavoriteBusinessView,
    FavoriteBusinessNotificationsView,
    HealthCheckView,
    HomeFeedView,
    InformalBusinessSignupView,
    LoginView,
    ManualBusinessSignupView,
    PasswordResetRequestView,
    PasswordResetView,
    PlaceDetailView,
    PlaceListView,
    PushDeviceRegistrationView,
    ConfirmTwoFactorView,
    ProfileDashboardView,
    ResendEmailVerificationCodeView,
    ResendVerificationEmailView,
    ToggleTwoFactorView,
    UsernameReminderView,
    VerifyEmailCodeView,
    VerifyEmailView,
)


urlpatterns = [
    path('health/', HealthCheckView.as_view(), name='health-check'),
    path('places/discovery-status/', DiscoveryEnrichmentStatusView.as_view(), name='place-discovery-status'),
    path('places/', PlaceListView.as_view(), name='place-list'),
    path('places/<slug:slug>/', PlaceDetailView.as_view(), name='place-detail'),
    path('deals/', DealListView.as_view(), name='deal-list'),
    path('feed/', HomeFeedView.as_view(), name='home-feed'),
    path('feed/impressions/', FeedImpressionView.as_view(), name='feed-impressions'),
    path('feed/engagements/', FeedEngagementView.as_view(), name='feed-engagements'),
    path('profiles/login/', LoginView.as_view(), name='profile-login'),
    path('profiles/recover-username/', UsernameReminderView.as_view(), name='profile-recover-username'),
    path('profiles/password-reset-request/', PasswordResetRequestView.as_view(), name='profile-password-reset-request'),
    path('profiles/reset-password/<str:token>/', PasswordResetView.as_view(), name='profile-password-reset'),
    path('profiles/me/', ProfileDashboardView.as_view(), name='profile-dashboard'),
    path('profiles/push-devices/', PushDeviceRegistrationView.as_view(), name='profile-push-devices'),
    path('profiles/contact-support/', ContactSupportView.as_view(), name='profile-contact-support'),
    path('profiles/delete-account/', DeleteAccountView.as_view(), name='profile-delete-account'),
    path('profiles/direct-messages/', DirectMessageThreadsView.as_view(), name='profile-direct-messages'),
    path('profiles/direct-messages/threads/<int:thread_id>/', DirectMessageThreadDetailView.as_view(), name='profile-direct-message-thread-detail'),
    path('profiles/direct-message-blocks/', DirectMessageBlocksView.as_view(), name='profile-direct-message-blocks'),
    path('profiles/direct-message-blocks/<int:block_id>/', DirectMessageBlockDetailView.as_view(), name='profile-direct-message-block-detail'),
    path('profiles/favorites/', FavoriteBusinessView.as_view(), name='profile-favorites'),
    path('profiles/favorite-business-notifications/', FavoriteBusinessNotificationsView.as_view(), name='profile-favorite-business-notifications'),
    path('profiles/favorite-business-notifications/<int:notification_id>/', FavoriteBusinessNotificationsView.as_view(), name='profile-favorite-business-notification-detail'),
    path('profiles/business-location/', BusinessLocationUpdateView.as_view(), name='profile-business-location'),
    path('profiles/business-location-preference/', BusinessLocationTrackingPreferenceView.as_view(), name='profile-business-location-preference'),
    path('profiles/resend-verification-code/', ResendEmailVerificationCodeView.as_view(), name='profile-resend-verification-code'),
    path('profiles/resend-verification/', ResendVerificationEmailView.as_view(), name='profile-resend-verification'),
    path('profiles/two-factor/', ToggleTwoFactorView.as_view(), name='profile-toggle-two-factor'),
    path('profiles/two-factor/confirm/', ConfirmTwoFactorView.as_view(), name='profile-confirm-two-factor'),
    path('profiles/two-factor/disable/', DisableTwoFactorView.as_view(), name='profile-disable-two-factor'),
    path('profiles/verify-email-code/', VerifyEmailCodeView.as_view(), name='profile-verify-email-code'),
    path('profiles/verify-email/<str:token>/', VerifyEmailView.as_view(), name='profile-verify-email'),
    path('profiles/customer-signup/', CustomerSignupView.as_view(), name='customer-signup'),
    path('profiles/business-signup/', BusinessSignupView.as_view(), name='business-signup'),
    path('profiles/manual-business-signup/', ManualBusinessSignupView.as_view(), name='manual-business-signup'),
    path('profiles/informal-business-signup/', InformalBusinessSignupView.as_view(), name='informal-business-signup'),
]