# Generated by Django 6.0.5 on 2026-05-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('deal_type', models.CharField(choices=[('happy_hour', 'Happy Hour'), ('daily_special', 'Daily Special'), ('discount', 'Discount'), ('limited_time', 'Limited Time'), ('other', 'Other')], max_length=20)),
                ('price_text', models.CharField(blank=True, max_length=120)),
                ('terms', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['place__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('city', models.CharField(choices=[('ventura', 'Ventura'), ('oxnard', 'Oxnard'), ('camarillo', 'Camarillo')], max_length=20)),
                ('venue_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('fast_food', 'Fast Food'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('shop', 'Shop'), ('attraction', 'Attraction'), ('other', 'Other')], max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happy_hours', to='places.deal')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='places.place'),
        ),
    ]
