# Generated by Django 6.0.5 on 2026-05-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=80)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('places_seen', models.PositiveIntegerField(default=0)),
                ('places_imported', models.PositiveIntegerField(default=0)),
                ('deals_imported', models.PositiveIntegerField(default=0)),
                ('happy_hours_imported', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='external_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='deal',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='source_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='deal',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='external_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='place',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='source_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='place',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
