# Generated by Django 6.0.5 on 2026-05-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_businessclaim_businessmembership_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessclaim',
            options={'ordering': ['-created_at'], 'verbose_name': 'Business Claim', 'verbose_name_plural': 'Business Claims'},
        ),
        migrations.AlterModelOptions(
            name='businessmembership',
            options={'ordering': ['place__name', 'user__username'], 'verbose_name': 'Business Membership', 'verbose_name_plural': 'Business Memberships'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['place__name', 'title'], 'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.AlterModelOptions(
            name='happyhour',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Happy Hour', 'verbose_name_plural': 'Happy Hours'},
        ),
        migrations.AlterModelOptions(
            name='importrun',
            options={'ordering': ['-started_at'], 'verbose_name': 'Import Run', 'verbose_name_plural': 'Import Runs'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['city', 'name'], 'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
    ]
