# Generated by Django 6.0.5 on 2026-05-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('places', '0004_alter_businessclaim_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Business Account',
                'verbose_name_plural': 'Business Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Customer Account',
                'verbose_name_plural': 'Customer Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
    ]
