# Generated by Django 6.0.5 on 2026-05-23 18:20

from django.db import migrations, models
import django.db.models.deletion


def _copy_place_to_listing_snapshot(apps, schema_editor):
	Place = apps.get_model('places', 'Place')
	ListingSnapshot = apps.get_model('places', 'ListingSnapshot')
	BusinessClaim = apps.get_model('places', 'BusinessClaim')
	BusinessMembership = apps.get_model('places', 'BusinessMembership')

	snapshot_cache = {}
	for place in Place.objects.all():
		cache_key = (place.source_name, place.external_id, place.name, place.city, place.address_line_1)
		snapshot, _ = ListingSnapshot.objects.get_or_create(
			source_name=place.source_name,
			external_id=place.external_id,
			name=place.name,
			city=place.city,
			address_line_1=place.address_line_1,
			defaults={
				'source_url': place.source_url,
				'listing_slug': place.slug,
				'venue_type': place.venue_type,
				'address_line_2': place.address_line_2,
				'neighborhood': place.neighborhood,
				'state': place.state,
				'postal_code': place.postal_code,
				'phone_number': place.phone_number,
				'website_url': place.website_url,
			},
		)
		snapshot_cache[cache_key] = snapshot.pk

	for claim in BusinessClaim.objects.select_related('place'):
		place = claim.place
		cache_key = (place.source_name, place.external_id, place.name, place.city, place.address_line_1)
		claim.listing_snapshot_id = snapshot_cache[cache_key]
		claim.save(update_fields=['listing_snapshot'])

	for membership in BusinessMembership.objects.select_related('place'):
		claim = membership.claim
		if claim_id := getattr(claim, 'id', None):
			membership.claim_id = claim_id
			membership.save(update_fields=['claim'])


class Migration(migrations.Migration):

	dependencies = [
		('places', '0005_businessaccount_customeraccount'),
	]

	operations = [
		migrations.CreateModel(
			name='ListingSnapshot',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('source_name', models.CharField(blank=True, max_length=80)),
				('source_url', models.URLField(blank=True)),
				('external_id', models.CharField(blank=True, max_length=150)),
				('listing_slug', models.SlugField(blank=True, max_length=170)),
				('name', models.CharField(max_length=150)),
				('city', models.CharField(blank=True, choices=[('ventura', 'Ventura'), ('oxnard', 'Oxnard'), ('camarillo', 'Camarillo')], max_length=20)),
				('venue_type', models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('fast_food', 'Fast Food'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('shop', 'Shop'), ('attraction', 'Attraction'), ('other', 'Other')], max_length=20)),
				('address_line_1', models.CharField(max_length=255)),
				('address_line_2', models.CharField(blank=True, max_length=255)),
				('neighborhood', models.CharField(blank=True, max_length=120)),
				('state', models.CharField(default='CA', max_length=2)),
				('postal_code', models.CharField(blank=True, max_length=10)),
				('phone_number', models.CharField(blank=True, max_length=20)),
				('website_url', models.URLField(blank=True)),
				('captured_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
			],
			options={
				'ordering': ['name', '-captured_at'],
				'verbose_name': 'Listing Snapshot',
				'verbose_name_plural': 'Listing Snapshots',
			},
		),
		migrations.AddField(
			model_name='businessclaim',
			name='listing_snapshot',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_claims', to='places.listingsnapshot'),
		),
		migrations.RunPython(_copy_place_to_listing_snapshot, migrations.RunPython.noop),
		migrations.RemoveConstraint(
			model_name='businessclaim',
			name='unique_claimant_place_claim',
		),
		migrations.RemoveField(
			model_name='businessclaim',
			name='place',
		),
		migrations.AlterField(
			model_name='businessclaim',
			name='listing_snapshot',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_claims', to='places.listingsnapshot'),
		),
		migrations.AddConstraint(
			model_name='businessclaim',
			constraint=models.UniqueConstraint(fields=('claimant', 'listing_snapshot'), name='unique_claimant_listing_snapshot_claim'),
		),
		migrations.RemoveConstraint(
			model_name='businessmembership',
			name='unique_business_membership_user_place',
		),
		migrations.RemoveField(
			model_name='businessmembership',
			name='place',
		),
		migrations.AlterField(
			model_name='businessmembership',
			name='claim',
			field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='places.businessclaim'),
		),
		migrations.AlterModelOptions(
			name='businessmembership',
			options={'ordering': ['claim__listing_snapshot__name', 'user__username'], 'verbose_name': 'Business Membership', 'verbose_name_plural': 'Business Memberships'},
		),
	]