# Generated by Django 6.0.5 on 2026-05-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('places', '0006_listingsnapshot_claim_snapshot_refactor'),
	]

	operations = [
		migrations.DeleteModel(
			name='HappyHour',
		),
		migrations.DeleteModel(
			name='ImportRun',
		),
		migrations.DeleteModel(
			name='Deal',
		),
		migrations.DeleteModel(
			name='Place',
		),
	]