# Generated by Django 6.0.5 on 2026-05-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_businessclaimprofileentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedbusiness',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('fast_food', 'Fast Food'), ('mobile', 'On the Move'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('shop', 'Shop'), ('attraction', 'Attraction'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listingsnapshot',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('fast_food', 'Fast Food'), ('mobile', 'On the Move'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('shop', 'Shop'), ('attraction', 'Attraction'), ('other', 'Other')], max_length=20),
        ),
    ]
