# Generated by Django 6.0.5 on 2026-06-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0027_businessclaim_photo_gallery_overridden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedbusiness',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('fast_food', 'Fast Food'), ('mobile', 'Serves Multiple Locations / Service Area Business'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('shop', 'Shop'), ('attraction', 'Attraction'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listingsnapshot',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('fast_food', 'Fast Food'), ('mobile', 'Serves Multiple Locations / Service Area Business'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('shop', 'Shop'), ('attraction', 'Attraction'), ('other', 'Other')], max_length=20),
        ),
    ]
