# Generated by Django 6.0.5 on 2026-06-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0030_businessclaim_structured_profile_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('special', 'Business Special'), ('announcement', 'Announcement'), ('event', 'Event'), ('blog', 'Blog Post')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=190)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('body', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('cta_url', models.URLField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='places.listingsnapshot')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='places.businessmembership')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsoredCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('billing_model', models.CharField(choices=[('weekly_subscription', 'Weekly Subscription'), ('hybrid', 'Hybrid')], default='weekly_subscription', max_length=24)),
                ('weekly_price_cents', models.PositiveIntegerField(default=1500)),
                ('weekly_impression_quota', models.PositiveIntegerField(default=500)),
                ('target_cities', models.JSONField(blank=True, default=list)),
                ('target_venue_types', models.JSONField(blank=True, default=list)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('last_served_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_campaigns', to='places.businessmembership')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_campaigns', to='places.businesspost')),
            ],
            options={
                'ordering': ['status', 'starts_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_type', models.CharField(choices=[('organic', 'Organic'), ('sponsored', 'Sponsored')], max_length=20)),
                ('feed_item_id', models.CharField(max_length=80)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_impressions', to='places.businesspost')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='places.sponsoredcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('open', 'Open'), ('save', 'Save'), ('share', 'Share')], max_length=20)),
                ('feed_item_id', models.CharField(max_length=80)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('destination_url', models.URLField(blank=True)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_engagements', to='places.businesspost')),
                ('impression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='places.feedimpression')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='places.sponsoredcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='businesspost',
            constraint=models.UniqueConstraint(fields=('membership', 'slug'), name='unique_business_post_slug_per_membership'),
        ),
        migrations.AddIndex(
            model_name='feedimpression',
            index=models.Index(fields=['campaign', 'created_at'], name='places_feed_campaig_0c4024_idx'),
        ),
        migrations.AddIndex(
            model_name='feedimpression',
            index=models.Index(fields=['post', 'created_at'], name='places_feed_post_id_bb4e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedengagement',
            index=models.Index(fields=['campaign', 'event_type', 'created_at'], name='places_feed_campaig_bd4ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='feedengagement',
            index=models.Index(fields=['post', 'event_type', 'created_at'], name='places_feed_post_id_b7b8dd_idx'),
        ),
    ]
