# Generated by Django 6.0.5 on 2026-07-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0044_private_sensitive_media_storage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favoritebusinessnotification',
            new_name='places_favo_user_id_4ad135_idx',
            old_name='places_favo_user_id_420724_idx',
        ),
        migrations.RenameIndex(
            model_name='favoritebusinessnotification',
            new_name='places_favo_listing_42bf4f_idx',
            old_name='places_favo_listing_8f7e7d_idx',
        ),
        migrations.RenameIndex(
            model_name='favoritebusinesspushdevice',
            new_name='places_favo_user_id_9b8381_idx',
            old_name='places_favo_user_id_6d8ba3_idx',
        ),
    ]
