# Generated by Django 6.0 on 2026-08-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('places', '0049_accountprofile_notification_preferences'),
	]

	operations = [
		migrations.AddField(
			model_name='businessclaim',
			name='verification_data_consent_at',
			field=models.DateTimeField(blank=True, null=True),
		),
		migrations.AddField(
			model_name='businessclaim',
			name='verification_data_consent_version',
			field=models.CharField(blank=True, max_length=40),
		),
	]