# Generated by Django 6.0 on 2026-08-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('places', '0050_businessclaim_verification_data_consent'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='ContentReport',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('target_type', models.CharField(choices=[('business_profile', 'Business Profile'), ('business_post', 'Business Post'), ('direct_message', 'Direct Message')], max_length=30)),
				('listing_slug', models.SlugField(blank=True, max_length=170)),
				('business_name', models.CharField(blank=True, max_length=160)),
				('reason', models.CharField(choices=[('objectionable_content', 'Objectionable Content'), ('spam_or_scam', 'Spam or Scam'), ('harassment_or_abuse', 'Harassment or Abuse'), ('misleading_information', 'Misleading Information'), ('intellectual_property', 'Intellectual Property'), ('other', 'Other')], max_length=40)),
				('details', models.TextField(blank=True)),
				('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
				('reviewer_notes', models.TextField(blank=True)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('business_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to='places.businesspost')),
				('direct_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to='places.businessdirectmessage')),
				('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
				('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_reports', to=settings.AUTH_USER_MODEL)),
			],
			options={
				'ordering': ['status', '-created_at'],
				'verbose_name': 'Content Report',
				'verbose_name_plural': 'Content Reports',
			},
		),
		migrations.AddIndex(
			model_name='contentreport',
			index=models.Index(fields=['status', '-created_at'], name='places_cont_status_1ef363_idx'),
		),
		migrations.AddIndex(
			model_name='contentreport',
			index=models.Index(fields=['target_type', '-created_at'], name='places_cont_target__3918a9_idx'),
		),
	]