# Generated by Django 6.0 on 2026-08-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('places', '0051_contentreport'),
	]

	operations = [
		migrations.AddField(
			model_name='contentreport',
			name='recipient_email',
			field=models.EmailField(blank=True, max_length=254),
		),
		migrations.AddField(
			model_name='contentreport',
			name='recipient_username',
			field=models.CharField(blank=True, max_length=150),
		),
		migrations.AddField(
			model_name='contentreport',
			name='reported_message',
			field=models.TextField(blank=True),
		),
		migrations.AddField(
			model_name='contentreport',
			name='reported_message_created_at',
			field=models.DateTimeField(blank=True, null=True),
		),
		migrations.AddField(
			model_name='contentreport',
			name='reported_user_email',
			field=models.EmailField(blank=True, max_length=254),
		),
		migrations.AddField(
			model_name='contentreport',
			name='reported_user_role',
			field=models.CharField(blank=True, max_length=30),
		),
		migrations.AddField(
			model_name='contentreport',
			name='reported_user_username',
			field=models.CharField(blank=True, max_length=150),
		),
		migrations.AddField(
			model_name='contentreport',
			name='reporter_email',
			field=models.EmailField(blank=True, max_length=254),
		),
		migrations.AddField(
			model_name='contentreport',
			name='reporter_username',
			field=models.CharField(blank=True, max_length=150),
		),
	]