# Generated by Django 6.0 on 2026-08-16 00:00

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

	dependencies = [
		('places', '0052_contentreport_identity_snapshot'),
	]

	operations = [
		migrations.AddField(
			model_name='contentreport',
			name='screenshot',
			field=models.ImageField(blank=True, null=True, storage=places.models.get_private_media_storage, upload_to=places.models.content_report_screenshot_upload_to),
		),
	]