# Generated by Django 6.0.5 on 2026-08-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0054_remove_providerusagewindow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(default='admin_operation', max_length=80)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_events', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Admin Audit Event',
                'verbose_name_plural': 'Admin Audit Events',
                'ordering': ['-created_at', '-pk'],
                'indexes': [
                    models.Index(fields=['created_at', '-id'], name='places_admi_created_11ff3b_idx'),
                    models.Index(fields=['content_type', 'object_id', '-created_at'], name='places_admi_content_4ef629_idx'),
                ],
            },
        ),
    ]
