# Generated by Django 6.0.5 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0055_adminauditevent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listingsnapshot',
            index=models.Index(fields=['name', '-captured_at'], name='places_list_name_cap_idx'),
        ),
        migrations.AddIndex(
            model_name='listingsnapshot',
            index=models.Index(fields=['city', 'name'], name='places_list_city_name_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclaim',
            index=models.Index(fields=['status', 'submitted_at'], name='places_claim_status_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclaim',
            index=models.Index(fields=['status', 'created_at'], name='places_claim_status_cre_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclaim',
            index=models.Index(fields=['claimant', 'created_at'], name='places_claim_cl_created_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmembership',
            index=models.Index(fields=['is_active'], name='places_member_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsoredcampaign',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='places_camp_status_window_idx'),
        ),
        migrations.AddIndex(
            model_name='feedimpression',
            index=models.Index(fields=['created_at'], name='places_impr_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedengagement',
            index=models.Index(fields=['created_at'], name='places_eng_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedengagement',
            index=models.Index(fields=['event_type', 'created_at'], name='places_eng_event_created_idx'),
        ),
    ]
