# Generated by Django 6.0.5 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('places', '0057_listingsnapshot_is_starred'),
	]

	operations = [
		migrations.AddField(
			model_name='accountprofile',
			name='terms_accepted_at',
			field=models.DateTimeField(blank=True, null=True),
		),
		migrations.AddField(
			model_name='accountprofile',
			name='terms_accepted_version',
			field=models.CharField(blank=True, max_length=40),
		),
	]
