import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  fullScreenRoot: {
    flex: 1,
    backgroundColor: '#f7efe2',
  },
  transitionClipRoot: {
    overflow: 'hidden',
  },
  onboardingTransitionRoot: {
    flex: 1,
    backgroundColor: '#f7efe2',
    overflow: 'hidden',
  },
  screenTransitionLayer: {
    flex: 1,
    backgroundColor: '#f7efe2',
  },
  screenTransitionLayerAbsolute: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#f7efe2',
  },
  incomingOnboardingOverlay: {
    shadowColor: '#2d221a',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
    elevation: 12,
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#f7efe2',
  },
  safeAreaTransparent: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  screen: {
    flex: 1,
    paddingHorizontal: 18,
    paddingVertical: 14,
    gap: 14,
  },
  screenLandscape: {
    alignSelf: 'center',
    maxWidth: 1180,
    width: '100%',
  },
  detailScreen: {
    flex: 1,
    paddingHorizontal: 18,
  },
  detailScreenLandscape: {
    alignSelf: 'center',
    maxWidth: 1180,
    width: '100%',
  },
  browseHeaderCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  browseHeaderCardLandscape: {
    alignSelf: 'center',
    gap: 8,
    maxWidth: 620,
    padding: 12,
  },
  toolbarRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  toolbarRowLeading: {
    justifyContent: 'flex-start',
  },
  toolbarActionsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 6,
    justifyContent: 'flex-start',
  },
  toolbarActionsRowFill: {
    flex: 1,
  },
  toolbarRowLandscape: {
    minHeight: 36,
  },
  browseModeContentLayer: {
    flex: 1,
  },
  browseContentStage: {
    flex: 1,
    position: 'relative',
  },
  browseContentFill: {
    ...StyleSheet.absoluteFillObject,
  },
  appTitle: {
    color: '#2d221a',
    fontSize: 24,
    fontWeight: '800',
  },
  controlsTitleLandscape: {
    fontSize: 20,
  },
  mapScreen: {
    flex: 1,
  },
  mapModeContentLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  mapThemeTransitionLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  floatingDashboardButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 18,
    borderWidth: 1,
    bottom: 0,
    justifyContent: 'center',
    minHeight: 48,
    minWidth: 146,
    paddingHorizontal: 16,
    paddingVertical: 12,
    position: 'absolute',
    right: 0,
    shadowColor: '#2d221a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 10,
    zIndex: 30,
  },
  floatingDashboardButtonMap: {
    zIndex: 40,
  },
  floatingDashboardButtonText: {
    color: '#5d4637',
    fontSize: 14,
    fontWeight: '700',
  },
  mapBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  mapOverlayLayer: {
    ...StyleSheet.absoluteFillObject,
    gap: 12,
    justifyContent: 'flex-start',
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 0,
  },
  mapOverlayContentLayer: {
    gap: 12,
  },
  mapTopPanel: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  mapTopPanelLandscape: {
    alignSelf: 'center',
    gap: 8,
    maxWidth: 620,
    padding: 12,
  },
  mapLoadingOverlay: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 250, 244, 0.94)',
    borderRadius: 20,
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  mapPreviewCard: {
    backgroundColor: 'rgba(255, 250, 244, 0.97)',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  mapPreviewCardLandscape: {
    alignSelf: 'center',
    gap: 10,
    maxWidth: 320,
    padding: 12,
    width: '100%',
  },
  mapResultsCard: {
    backgroundColor: 'rgba(255, 250, 244, 0.97)',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    minHeight: 0,
    padding: 16,
  },
  mapResultsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mapResultsHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  mapResultsHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginLeft: 12,
  },
  mapResultsTitle: {
    color: '#2d221a',
    fontSize: 18,
    fontWeight: '800',
  },
  mapResultsMeta: {
    color: '#7b6350',
    fontSize: 12,
    fontWeight: '700',
  },
  mapResultsList: {
    gap: 10,
    paddingRight: 4,
  },
  mapResultsScroll: {
    minHeight: 0,
  },
  mapResultsMoreButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  mapResultsMoreButtonLoadingContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  mapResultsMoreButtonText: {
    color: '#1f5f5b',
    fontSize: 13,
    fontWeight: '800',
  },
  mapResultsCollapseButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 12,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  mapResultsChevronIcon: {
    height: 14,
    position: 'relative',
    width: 16,
  },
  mapResultsChevronLine: {
    backgroundColor: '#5d4637',
    borderRadius: 999,
    height: 2.5,
    position: 'absolute',
    top: 6,
    width: 8,
  },
  mapResultsChevronLineLeft: {
    left: 0.5,
    transformOrigin: 'right center',
  },
  mapResultsChevronLineRight: {
    right: 0.5,
    transformOrigin: 'left center',
  },
  mapResultsContent: {
    gap: 12,
    minHeight: 0,
    overflow: 'hidden',
  },
  mapResultRow: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  mapResultCopy: {
    flex: 1,
    gap: 4,
  },
  mapResultTitle: {
    color: '#2d221a',
    fontSize: 15,
    fontWeight: '800',
  },
  mapResultMeta: {
    color: '#725947',
    fontSize: 12,
    lineHeight: 17,
  },
  mapResultAction: {
    color: '#1f5f5b',
    fontSize: 12,
    fontWeight: '800',
  },
  mapResultEmptyText: {
    color: '#725947',
    fontSize: 13,
    lineHeight: 18,
  },
  mapPreviewHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mapPreviewCopy: {
    flex: 1,
    gap: 4,
    paddingRight: 12,
  },
  mapPreviewTitle: {
    color: '#2d221a',
    fontSize: 19,
    fontWeight: '800',
  },
  mapPreviewTitleLandscape: {
    fontSize: 16,
  },
  mapPreviewMeta: {
    color: '#6c5443',
    fontSize: 14,
    fontWeight: '600',
  },
  mapPreviewMetaLandscape: {
    fontSize: 12,
  },
  mapPreviewActions: {
    flexDirection: 'row',
    gap: 8,
  },
  mapPreviewDetails: {
    gap: 4,
    marginTop: -2,
  },
  mapPreviewDetailText: {
    color: '#725947',
    fontSize: 13,
    lineHeight: 18,
  },
  mapPreviewDetailTextLandscape: {
    fontSize: 12,
    lineHeight: 16,
  },
  mapPreviewIconButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  mapPreviewIconButtonLandscape: {
    height: 30,
    width: 30,
  },
  mapPreviewIconText: {
    color: '#402214',
    fontSize: 18,
    fontWeight: '800',
  },
  mapPreviewIconTextLandscape: {
    fontSize: 15,
  },
  mapPreviewGallery: {
    gap: 12,
  },
  mapPreviewGalleryLandscape: {
    gap: 8,
  },
  mapPreviewImage: {
    backgroundColor: '#ecdac7',
    borderRadius: 18,
    height: 180,
    width: 250,
  },
  mapPreviewImageLandscape: {
    borderRadius: 14,
    height: 110,
    width: 180,
  },
  mapPreviewEmptyState: {
    alignItems: 'center',
    backgroundColor: '#f6eee4',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 140,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  mapPreviewEmptyStateLandscape: {
    minHeight: 92,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  mapPreviewEmptyText: {
    color: '#7d614f',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  mapPreviewEmptyTextLandscape: {
    fontSize: 12,
    lineHeight: 16,
  },
  mapAppTitle: {
    color: '#2d221a',
    fontSize: 24,
    fontWeight: '800',
  },
  mapOverlayText: {
    color: '#6c5443',
    fontSize: 13,
    lineHeight: 18,
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  searchRowLandscape: {
    alignItems: 'stretch',
    gap: 6,
  },
  searchInputShell: {
    alignItems: 'center',
    backgroundColor: '#f8efe3',
    borderColor: '#ead6bf',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  searchInputShellLandscape: {
    minHeight: 42,
    paddingHorizontal: 10,
  },
  searchInputShellOverlay: {
    backgroundColor: '#f8efe3',
  },
  searchInputIcon: {
    color: '#9a6440',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  searchInput: {
    color: '#2d221a',
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    paddingVertical: 0,
  },
  searchClearButton: {
    paddingVertical: 6,
  },
  searchClearButtonText: {
    color: '#1f5f5b',
    fontSize: 13,
    fontWeight: '700',
  },
  filtersToggleButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 14,
  },
  filtersToggleButtonInline: {
    minHeight: 44,
  },
  filtersToggleButtonLandscape: {
    minHeight: 42,
    paddingHorizontal: 10,
  },
  filtersToggleButtonActive: {
    backgroundColor: '#402214',
    borderColor: '#402214',
  },
  filtersToggleText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '700',
  },
  filtersToggleTextActive: {
    color: '#fff7ef',
  },
  browseStatsRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  browseStatsRowLandscape: {
    gap: 6,
  },
  browseStatsText: {
    color: '#2d221a',
    fontSize: 14,
    fontWeight: '800',
  },
  browseStatsSubtleText: {
    color: '#7b6350',
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
  },
  filtersPanel: {
    borderTopColor: '#efd8bd',
    borderTopWidth: 1,
    gap: 12,
    minHeight: 0,
    paddingTop: 12,
  },
  filtersPanelLandscape: {
    gap: 8,
    paddingTop: 8,
  },
  filtersPanelScrollContent: {
    gap: 12,
    paddingBottom: 4,
    paddingRight: 4,
  },
  browseSectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  browseSectionTitle: {
    color: '#402214',
    fontSize: 14,
    fontWeight: '800',
  },
  browseSectionMeta: {
    color: '#8f725d',
    fontSize: 12,
    fontWeight: '600',
  },
  browseSectionAction: {
    color: '#1f5f5b',
    fontSize: 12,
    fontWeight: '700',
  },
  reloadButton: {
    alignItems: 'center',
    backgroundColor: '#1f5f5b',
    borderRadius: 14,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  secondaryToolbarButton: {
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  secondaryToolbarButtonText: {
    color: '#5d4637',
    fontSize: 14,
    fontWeight: '700',
  },
  toolbarArrowButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  toolbarArrowButtonText: {
    color: '#5d4637',
    fontSize: 22,
    fontWeight: '700',
  },
  reloadButtonText: {
    color: '#f4fffe',
    fontSize: 22,
    fontWeight: '700',
  },
  mapThemeToggleButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    height: 44,
    width: 44,
  },
  mapThemeToggleButtonActive: {
    backgroundColor: '#2d403f',
    borderColor: '#2d403f',
  },
  mapThemeToggleButtonText: {
    color: '#5d4637',
    fontSize: 18,
    fontWeight: '800',
  },
  mapThemeToggleButtonTextActive: {
    color: '#f4fffe',
  },
  sectionTitle: {
    color: '#402214',
    fontSize: 18,
    fontWeight: '700',
  },
  detailSectionTitle: {
    marginTop: 22,
  },
  locationsSectionTitle: {
    paddingTop: 6,
    paddingBottom: 6,
  },
  filterRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  modeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  authPortalButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  authPortalButtonActive: {
    backgroundColor: '#1f5f5b',
    borderColor: '#1f5f5b',
  },
  authPortalButtonText: {
    color: '#5d4637',
    fontSize: 15,
    fontWeight: '700',
  },
  authPortalButtonTextActive: {
    color: '#f4fffe',
  },
  modeSwitcherDock: {
    alignItems: 'flex-start',
    marginTop: 10,
  },
  modeSwitcherDockOverlay: {
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  modeSwitcherTrack: {
    backgroundColor: 'rgba(255, 250, 244, 0.96)',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    height: 44,
    overflow: 'hidden',
    padding: 4,
    position: 'relative',
  },
  modeSwitcherTrackOverlay: {
    backgroundColor: 'rgba(255, 247, 239, 0.98)',
  },
  modeSwitcherThumb: {
    backgroundColor: '#1f5f5b',
    borderRadius: 999,
    bottom: 4,
    left: 4,
    position: 'absolute',
    top: 4,
  },
  modeSwitchOption: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  modeSwitchOptionText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '700',
  },
  modeSwitchOptionTextActive: {
    color: '#f4fffe',
  },
  filterChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  filterChipActive: {
    backgroundColor: '#402214',
    borderColor: '#402214',
  },
  filterChipText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: '#fff7ef',
  },
  overlayChip: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 250, 244, 0.96)',
    borderColor: '#ddc4a7',
    paddingVertical: 10,
  },
  overlayChipActive: {
    backgroundColor: '#402214',
    borderColor: '#402214',
  },
  overlayChipText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '600',
  },
  overlayChipTextActive: {
    color: '#fff7ef',
  },
  venueFilterRow: {
    alignItems: 'center',
    gap: 8,
    paddingRight: 16,
  },
  venueFilterChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  venueFilterChipActive: {
    backgroundColor: '#402214',
    borderColor: '#402214',
  },
  venueFilterBadge: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 2,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  venueFilterBadgeText: {
    color: '#fffaf4',
    fontSize: 11,
    fontWeight: '800',
  },
  mapMarker: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 2,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  mapMarkerActive: {
    borderWidth: 3,
    elevation: 4,
    shadowColor: '#1f160f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  mapMarkerText: {
    color: '#fffaf4',
    fontSize: 12,
    fontWeight: '900',
  },
  listContent: {
    gap: 12,
    paddingBottom: 96,
  },
  listContentLandscape: {
    paddingBottom: 104,
  },
  placeCardColumn: {
    gap: 12,
  },
  placeCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 22,
    borderWidth: 1,
    padding: 18,
  },
  placeCardLandscape: {
    flex: 1,
  },
  placeCity: {
    color: '#c65d1f',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  placeTitle: {
    color: '#2d221a',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 4,
  },
  placeMeta: {
    color: '#5c5043',
    fontSize: 14,
    marginTop: 4,
  },
  placeAddress: {
    color: '#7d614f',
    fontSize: 13,
    marginTop: 8,
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 40,
  },
  centerStateText: {
    color: '#6f5947',
    marginTop: 10,
  },
  detailScrollContent: {
    paddingTop: 45,
    paddingBottom: 20,
  },
  detailScrollContentLandscape: {
    paddingTop: 24,
  },
  backButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  backButtonText: {
    color: '#402214',
    fontWeight: '700',
  },
  linkButtonDisabled: {
    opacity: 0.7,
  },
  detailCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 12,
    padding: 18,
  },
  detailCardLandscape: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  detailCity: {
    color: '#c65d1f',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  detailTitle: {
    color: '#2d221a',
    fontSize: 26,
    fontWeight: '800',
    marginTop: 6,
  },
  detailMeta: {
    color: '#5f4b3d',
    fontSize: 14,
    marginTop: 6,
  },
  detailAddress: {
    color: '#7c6252',
    fontSize: 14,
    marginTop: 4,
  },
  addressButton: {
    alignSelf: 'flex-start',
  },
  detailLinkText: {
    color: '#1f5f5b',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
    textDecorationLine: 'underline',
  },
  detailMapCard: {
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 12,
    overflow: 'hidden',
  },
  detailMap: {
    height: 170,
    width: '100%',
  },
  detailMapCaption: {
    backgroundColor: '#fff7ef',
    borderTopColor: '#efd8bd',
    borderTopWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  detailMapCaptionText: {
    color: '#5f4b3d',
    fontSize: 13,
    fontWeight: '600',
  },
  reviewSummaryCard: {
    backgroundColor: '#fff3e5',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  reviewSummaryRating: {
    color: '#2d221a',
    fontSize: 18,
    fontWeight: '800',
  },
  reviewSummaryMeta: {
    color: '#6c5443',
    fontSize: 13,
    marginTop: 4,
  },
  reviewList: {
    gap: 12,
    marginTop: 12,
  },
  reviewCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  reviewQuote: {
    color: '#4d3a2f',
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 21,
  },
  linkButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#1f5f5b',
    borderRadius: 14,
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  linkButtonText: {
    color: '#effffd',
    fontWeight: '700',
  },
  linkButtonSecondary: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#1f5f5b',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  linkButtonSecondaryText: {
    color: '#1f5f5b',
    fontWeight: '700',
  },
  dealCard: {
    backgroundColor: '#fff3e5',
    borderRadius: 18,
    marginTop: 14,
    padding: 14,
  },
  dealHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  dealTitle: {
    color: '#2f241b',
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
  },
  pill: {
    backgroundColor: '#f8d8bf',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  pillText: {
    color: '#7f461f',
    fontSize: 12,
    fontWeight: '700',
  },
  dealPrice: {
    color: '#bf4d0f',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 10,
  },
  dealDescription: {
    color: '#5b4c41',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  dealTerms: {
    color: '#7a6658',
    fontSize: 13,
    marginTop: 8,
  },
  hourList: {
    gap: 10,
    marginTop: 10,
  },
  hourGroupCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd9c5',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  hourGroupDays: {
    color: '#7f461f',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  hourRow: {
    color: '#43352c',
    fontSize: 13,
  },
  emptyStateText: {
    color: '#735e4c',
    fontSize: 14,
    lineHeight: 20,
    paddingVertical: 20,
  },
  errorBanner: {
    backgroundColor: '#ffe0d6',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  errorText: {
    color: '#8d2500',
    fontSize: 13,
    lineHeight: 18,
  },
  mapErrorBanner: {
    alignSelf: 'stretch',
  },
  splashScreen: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 28,
    backgroundColor: '#f6ead8',
  },
  splashLogoShell: {
    alignItems: 'center',
    backgroundColor: '#1f5f5b',
    borderRadius: 36,
    height: 112,
    justifyContent: 'center',
    shadowColor: '#1b443f',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    width: 112,
  },
  splashLogoText: {
    color: '#effffd',
    fontSize: 38,
    fontWeight: '800',
    letterSpacing: 2,
  },
  splashTitle: {
    color: '#2d221a',
    fontSize: 30,
    fontWeight: '800',
    marginTop: 22,
  },
  splashSubtitle: {
    color: '#6c5443',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 10,
    maxWidth: 320,
    textAlign: 'center',
  },
  authScreen: {
    flex: 1,
    paddingHorizontal: 18,
  },
  keyboardAvoidingFill: {
    flex: 1,
  },
  authScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 32,
  },
  authHero: {
    alignItems: 'center',
    marginBottom: 18,
    paddingHorizontal: 12,
  },
  authLogoShell: {
    alignItems: 'center',
    backgroundColor: '#1f5f5b',
    borderRadius: 28,
    height: 84,
    justifyContent: 'center',
    width: 84,
  },
  authLogoText: {
    color: '#effffd',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  authTitle: {
    color: '#2d221a',
    fontSize: 28,
    fontWeight: '800',
    marginTop: 18,
    textAlign: 'center',
  },
  authSubtitle: {
    color: '#6c5443',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    maxWidth: 320,
    textAlign: 'center',
  },
  authLinkButton: {
    alignSelf: 'center',
    marginTop: 12,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  authLinkText: {
    color: '#1f5f5b',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  profileScreen: {
    flex: 1,
    paddingHorizontal: 18,
  },
  profileScreenLandscape: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  profileScrollContent: {
    flexGrow: 1,
    paddingTop: 24,
    paddingBottom: 32,
  },
  dashboardScrollContent: {
    flexGrow: 1,
    paddingTop: 8,
    paddingBottom: 32,
  },
  profileCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginTop: 12,
    padding: 18,
  },
  dashboardCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginTop: 8,
    padding: 18,
  },
  profileIntroText: {
    color: '#6c5443',
    fontSize: 14,
    lineHeight: 20,
  },
  profileSuccessBanner: {
    backgroundColor: '#e7f6f4',
    borderColor: '#9dcfc9',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  profileSuccessText: {
    color: '#17413e',
    fontSize: 13,
    fontWeight: '700',
  },
  profileFormSection: {
    gap: 10,
  },
  profileFieldLabel: {
    color: '#402214',
    fontSize: 13,
    fontWeight: '700',
  },
  profileInput: {
    backgroundColor: '#f8efe3',
    borderColor: '#ead6bf',
    borderRadius: 14,
    borderWidth: 1,
    color: '#2d221a',
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  compactDropdownWrap: {
    gap: 6,
  },
  compactDropdownButton: {
    backgroundColor: '#f8efe3',
    borderColor: '#ead6bf',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  compactDropdownButtonOpen: {
    borderColor: '#1f5f5b',
  },
  compactDropdownText: {
    color: '#2d221a',
    fontSize: 14,
    lineHeight: 18,
  },
  compactDropdownPlaceholder: {
    color: '#8a705d',
  },
  compactDropdownCaret: {
    color: '#6c5443',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 12,
  },
  compactDropdownMenu: {
    backgroundColor: '#fffaf4',
    borderColor: '#ead6bf',
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  compactDropdownOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  compactDropdownOptionSelected: {
    backgroundColor: '#e7f6f4',
  },
  compactDropdownOptionText: {
    color: '#2d221a',
    fontSize: 14,
    lineHeight: 18,
  },
  compactDropdownOptionTextSelected: {
    color: '#17413e',
    fontWeight: '700',
  },
  profileSupportText: {
    color: '#7d614f',
    fontSize: 12,
    lineHeight: 18,
    marginTop: -2,
  },
  claimResultsList: {
    gap: 12,
    marginTop: 8,
  },
  claimResultCard: {
    backgroundColor: '#fff3e5',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  linkButtonSecondaryWide: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#fff7ef',
    borderColor: '#1f5f5b',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dashboardCalloutCard: {
    backgroundColor: '#fff3e5',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  claimBusinessHint: {
    color: '#6c5443',
    fontSize: 13,
    lineHeight: 18,
  },
  claimLocationList: {
    gap: 8,
    marginTop: 6,
  },
  claimLocationButton: {
    backgroundColor: '#fffaf4',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  claimLocationButtonTitle: {
    color: '#402214',
    fontSize: 13,
    fontWeight: '700',
  },
  claimLocationButtonText: {
    color: '#5f4b3d',
    fontSize: 13,
    lineHeight: 18,
  },
  dashboardVerifiedCard: {
    backgroundColor: '#e7f6f4',
    borderColor: '#9dcfc9',
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  dashboardVerifiedTitle: {
    color: '#17413e',
    fontSize: 16,
    fontWeight: '800',
  },
  dashboardVerifiedText: {
    color: '#17413e',
    fontSize: 13,
    lineHeight: 18,
  },
  dashboardSectionCard: {
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  dashboardSectionTitle: {
    color: '#402214',
    fontSize: 16,
    fontWeight: '800',
  },
  dashboardSupportText: {
    color: '#6c5443',
    fontSize: 13,
    lineHeight: 18,
  },
  dashboardDetailRow: {
    gap: 4,
  },
  dashboardDetailLabel: {
    color: '#7a4d2f',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  dashboardDetailValue: {
    color: '#2d221a',
    fontSize: 15,
    lineHeight: 20,
  },
  dashboardFooterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  toggleChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#caa98d',
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  toggleChipActive: {
    backgroundColor: '#1f5f5b',
    borderColor: '#1f5f5b',
  },
  toggleChipText: {
    color: '#7a4d2f',
    fontSize: 13,
    fontWeight: '700',
  },
  toggleChipTextActive: {
    color: '#effffd',
  },
  profileTextarea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
});
