import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  fullScreenRoot: {
    flex: 1,
    backgroundColor: '#f7efe2',
  },
  startupImagePreloadLayer: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0,
    pointerEvents: 'none',
    zIndex: -1,
  },
  startupImagePreload: {
    height: 1,
    width: 1,
  },
  transitionClipRoot: {
    overflow: 'hidden',
  },
  onboardingTransitionRoot: {
    flex: 1,
    backgroundColor: '#f7efe2',
    overflow: 'hidden',
  },
  screenTransitionLayer: {
    flex: 1,
    backgroundColor: '#f7efe2',
  },
  screenTransitionLayerAbsolute: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#f7efe2',
  },
  incomingOnboardingOverlay: {
    shadowColor: '#2d221a',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
    elevation: 12,
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#f7efe2',
  },
  safeAreaTransparent: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  screen: {
    flex: 1,
    paddingHorizontal: 18,
    paddingVertical: 14,
    gap: 14,
  },
  screenLandscape: {
    alignSelf: 'center',
    maxWidth: 1180,
    width: '100%',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  browseHeaderCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  browseHeaderCardLandscape: {
    alignSelf: 'center',
    gap: 8,
    maxWidth: 620,
    padding: 12,
  },
  toolbarRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
  },
  toolbarRowLeading: {
    justifyContent: 'flex-start',
  },
  toolbarActionsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 4,
    justifyContent: 'flex-start',
  },
  toolbarActionsRowFill: {
    flex: 1,
  },
  toolbarActionsRowWithDashboard: {
    flex: 1,
    minWidth: 0,
  },
  toolbarRowLandscape: {
    minHeight: 36,
  },
  browseModeContentLayer: {
    flex: 1,
  },
  browseContentStage: {
    flex: 1,
    position: 'relative',
  },
  browseContentFill: {
    ...StyleSheet.absoluteFillObject,
  },
  appTitle: {
    color: '#2d221a',
    fontSize: 24,
    fontWeight: '800',
  },
  controlsTitleLandscape: {
    fontSize: 20,
  },
  mapScreen: {
    flex: 1,
  },
  mapModeContentLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  mapThemeTransitionLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  floatingDashboardButton: {
    alignItems: 'center',
    backgroundColor: '#fff8f1',
    borderColor: '#d9c1a8',
    borderRadius: 18,
    borderWidth: 1,
    bottom: 0,
    justifyContent: 'center',
    minHeight: 48,
    minWidth: 146,
    paddingHorizontal: 16,
    paddingVertical: 12,
    position: 'absolute',
    right: 0,
    shadowColor: '#2d221a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 10,
    zIndex: 30,
  },
  floatingDashboardButtonMap: {
    zIndex: 40,
  },
  floatingGuestExitButton: {
    borderRadius: 999,
    minHeight: 54,
    minWidth: 54,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  floatingMapNavActionButton: {
    borderRadius: 999,
    minHeight: 54,
    minWidth: 54,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  floatingMapNavActionArrow: {
    color: '#17110c',
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 30,
    marginTop: -1,
  },
  exitIconWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  exitIconDoor: {
    backgroundColor: '#17110c',
    borderRadius: 2,
    height: 22,
    transform: [{ skewY: '-12deg' }],
    width: 8,
  },
  exitIconFrame: {
    height: 24,
    marginLeft: 3,
    position: 'relative',
    width: 8,
  },
  exitIconFrameTop: {
    backgroundColor: '#17110c',
    height: 3,
    position: 'absolute',
    right: 0,
    top: 0,
    width: 8,
  },
  exitIconFrameSide: {
    backgroundColor: '#17110c',
    height: 18,
    position: 'absolute',
    right: 0,
    top: 3,
    width: 3,
  },
  exitIconFrameBottom: {
    backgroundColor: '#17110c',
    bottom: 0,
    height: 3,
    position: 'absolute',
    right: 0,
    width: 8,
  },
  exitIconArrowRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: 2,
  },
  exitIconArrowShaft: {
    backgroundColor: '#17110c',
    height: 4,
    width: 7,
  },
  exitIconArrowHead: {
    borderBottomColor: 'transparent',
    borderBottomWidth: 5,
    borderLeftColor: '#17110c',
    borderLeftWidth: 8,
    borderTopColor: 'transparent',
    borderTopWidth: 5,
  },
  floatingDashboardButtonText: {
    color: '#5d4637',
    fontSize: 14,
    fontWeight: '700',
  },
  bottomNavOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 70,
  },
  bottomNavShell: {
    alignItems: 'center',
    backgroundColor: '#9e5b49',
    borderTopColor: '#5a3927',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    overflow: 'hidden',
    paddingHorizontal: 2,
    paddingTop: 40,
    height: 40,
    shadowColor: '#1c130d',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    width: '100%',
  },
  bottomNavGlassHighlight: {
    backgroundColor: 'rgba(255, 248, 241, 0.08)',
    height: 1,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  bottomNavItem: {
    alignItems: 'center',
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minHeight: 32,
    zIndex: 1,
  },
  bottomNavItemIconWrap: {
    alignItems: 'center',
    borderRadius: 14,
    height: 42,
    justifyContent: 'center',
    width: 46,
  },
  bottomNavItemIconWrapActive: {
    backgroundColor: 'rgba(255, 248, 241, 0.12)',
  },
  bottomNavItemLabel: {
    color: 'rgba(255, 248, 241, 0.7)',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  bottomNavItemLabelActive: {
    color: '#fff8f1',
  },
  bottomNavMapIcon: {
    alignItems: 'center',
    height: 18,
    justifyContent: 'center',
    width: 20,
  },
  bottomNavMapPanel: {
    borderColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 1.5,
    borderWidth: 2,
    height: 13,
    position: 'absolute',
    transform: [{ rotate: '45deg' }],
    width: 13,
  },
  bottomNavMapPanelMiddle: {
    backgroundColor: 'rgba(255, 248, 241, 0.68)',
    borderWidth: 0,
    height: 6,
    transform: [{ rotate: '45deg' }],
    width: 6,
  },
  bottomNavMapPanelActive: {
    backgroundColor: '#fff8f1',
    borderColor: '#fff8f1',
  },
  bottomNavProfileIcon: {
    alignItems: 'center',
    height: 19,
    justifyContent: 'center',
    width: 20,
  },
  bottomNavProfileHead: {
    backgroundColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 999,
    height: 7,
    width: 7,
  },
  bottomNavProfileBody: {
    borderColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 999,
    borderWidth: 1.8,
    height: 9,
    marginTop: 3,
    width: 15,
  },
  bottomNavMoreIcon: {
    alignItems: 'center',
    gap: 2.5,
    height: 16,
    justifyContent: 'center',
    width: 18,
  },
  bottomNavMoreLine: {
    backgroundColor: 'rgba(255, 248, 241, 0.68)',
    borderRadius: 999,
    height: 2,
    width: 14,
  },
  bottomNavIconFillActive: {
    backgroundColor: '#fff8f1',
  },
  bottomNavIconStrokeActive: {
    backgroundColor: '#fff8f1',
    borderColor: '#fff8f1',
  },
  mapBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  mapOverlayLayer: {
    ...StyleSheet.absoluteFillObject,
    gap: 12,
    justifyContent: 'flex-start',
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 0,
  },
  mapOverlayContentLayer: {
    gap: 12,
  },
  mapTopPanel: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  mapTopPanelLandscape: {
    alignSelf: 'center',
    gap: 8,
    maxWidth: 620,
    padding: 12,
  },
  mapLoadingOverlay: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 250, 244, 0.94)',
    borderRadius: 20,
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  mapPreviewCard: {
    backgroundColor: 'rgba(255, 250, 244, 0.97)',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  mapPreviewCardLandscape: {
    alignSelf: 'center',
    gap: 10,
    maxWidth: 320,
    padding: 12,
    width: '100%',
  },
  mapResultsCard: {
    backgroundColor: 'rgba(255, 250, 244, 0.97)',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 12,
    minHeight: 0,
    padding: 16,
  },
  mapResultsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mapResultsHeaderCopy: {
    flex: 1,
    gap: 2,
  },
  mapResultsHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginLeft: 12,
  },
  mapResultsTitle: {
    color: '#2d221a',
    fontSize: 18,
    fontWeight: '800',
  },
  mapResultsMeta: {
    color: '#7b6350',
    fontSize: 12,
    fontWeight: '700',
  },
  mapResultsList: {
    gap: 10,
    paddingRight: 4,
  },
  mapResultsScroll: {
    minHeight: 0,
  },
  mapResultsMoreButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  mapResultsMoreButtonLoadingContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  mapResultsMoreButtonText: {
    color: '#1f5f5b',
    fontSize: 13,
    fontWeight: '800',
  },
  mapResultsCollapseButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 12,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  mapResultsChevronIcon: {
    height: 14,
    position: 'relative',
    width: 16,
  },
  mapResultsChevronLine: {
    backgroundColor: '#5d4637',
    borderRadius: 999,
    height: 2.5,
    position: 'absolute',
    top: 6,
    width: 8,
  },
  mapResultsChevronLineLeft: {
    left: 0.5,
    transformOrigin: 'right center',
  },
  mapResultsChevronLineRight: {
    right: 0.5,
    transformOrigin: 'left center',
  },
  mapResultsContent: {
    gap: 12,
    minHeight: 0,
    overflow: 'hidden',
  },
  mapResultRow: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  mapResultCopy: {
    flex: 1,
    gap: 4,
  },
  mapResultTitle: {
    color: '#2d221a',
    fontSize: 15,
    fontWeight: '800',
  },
  mapResultMeta: {
    color: '#725947',
    fontSize: 12,
    lineHeight: 17,
  },
  mapResultAction: {
    color: '#1f5f5b',
    fontSize: 12,
    fontWeight: '800',
  },
  mapResultEmptyText: {
    color: '#725947',
    fontSize: 13,
    lineHeight: 18,
  },
  mapPreviewHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mapPreviewCopy: {
    flex: 1,
    gap: 4,
    paddingRight: 12,
  },
  mapPreviewTitle: {
    color: '#2d221a',
    fontSize: 19,
    fontWeight: '800',
  },
  mapPreviewTitleLandscape: {
    fontSize: 16,
  },
  mapPreviewMeta: {
    color: '#6c5443',
    fontSize: 14,
    fontWeight: '600',
  },
  mapPreviewMetaLandscape: {
    fontSize: 12,
  },
  mapPreviewActions: {
    flexDirection: 'row',
    gap: 8,
  },
  mapPreviewDetails: {
    gap: 4,
    marginTop: -2,
  },
  mapPreviewDetailText: {
    color: '#725947',
    fontSize: 13,
    lineHeight: 18,
  },
  mapPreviewDetailTextLandscape: {
    fontSize: 12,
    lineHeight: 16,
  },
  mapPreviewIconButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  mapPreviewIconButtonLandscape: {
    height: 30,
    width: 30,
  },
  mapPreviewIconText: {
    color: '#402214',
    fontSize: 18,
    fontWeight: '800',
  },
  mapPreviewIconTextLandscape: {
    fontSize: 15,
  },
  mapPreviewGallery: {
    gap: 12,
  },
  mapPreviewGalleryLandscape: {
    gap: 8,
  },
  mapPreviewImage: {
    backgroundColor: '#ecdac7',
    borderRadius: 18,
    height: 180,
    width: 250,
  },
  mapPreviewImageLandscape: {
    borderRadius: 14,
    height: 110,
    width: 180,
  },
  mapPreviewEmptyState: {
    alignItems: 'center',
    backgroundColor: '#f6eee4',
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 140,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  mapPreviewEmptyStateLandscape: {
    minHeight: 92,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  mapPreviewEmptyText: {
    color: '#7d614f',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  mapPreviewEmptyTextLandscape: {
    fontSize: 12,
    lineHeight: 16,
  },
  dashboardMultilineInput: {
    minHeight: 112,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  mapAppTitle: {
    color: '#2d221a',
    fontSize: 24,
    fontWeight: '800',
  },
  mapOverlayText: {
    color: '#6c5443',
    fontSize: 13,
    lineHeight: 18,
  },
  searchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  searchRowLandscape: {
    alignItems: 'stretch',
    gap: 6,
  },
  searchInputShell: {
    alignItems: 'center',
    backgroundColor: '#f8efe3',
    borderColor: '#ead6bf',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  searchInputShellLandscape: {
    minHeight: 42,
    paddingHorizontal: 10,
  },
  searchInputShellOverlay: {
    backgroundColor: '#f8efe3',
  },
  searchInputShellCurtain: {
    minHeight: 52,
  },
  searchCurtainToggleInline: {
    alignItems: 'center',
    bottom: 4,
    height: 20,
    justifyContent: 'center',
    left: '50%',
    marginLeft: -16,
    position: 'absolute',
    width: 32,
    zIndex: 12,
  },
  searchInputIcon: {
    color: '#9a6440',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  searchInput: {
    color: '#2d221a',
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    paddingVertical: 0,
  },
  searchClearButton: {
    paddingVertical: 6,
  },
  searchClearButtonText: {
    color: '#9e5b49',
    fontSize: 13,
    fontWeight: '700',
  },
  filtersToggleButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 14,
  },
  filtersToggleButtonInline: {
    minHeight: 44,
    paddingHorizontal: 10,
  },
  filtersToggleButtonPressable: {
    borderRadius: 16,
  },
  filtersToggleButtonLandscape: {
    minHeight: 42,
    paddingHorizontal: 10,
  },
  filtersToggleButtonActive: {
    backgroundColor: '#402214',
    borderColor: '#402214',
  },
  filtersToggleText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '700',
  },
  filtersToggleTextInline: {
    fontSize: 12,
  },
  filtersToggleTextActive: {
    color: '#fff7ef',
  },
  browseStatsRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    paddingTop: 5,
    justifyContent: 'space-between',
  },
  browseStatsRowLandscape: {
    gap: 6,
  },
  browseStatsText: {
    color: '#2d221a',
    fontSize: 14,
    fontWeight: '800',
  },
  browseStatsSubtleText: {
    color: '#7b6350',
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
  },
  filtersPanel: {
    borderTopColor: '#efd8bd',
    borderTopWidth: 1,
    gap: 12,
    marginTop: 8,    
    minHeight: 0,
  },
  filtersPanelLandscape: {
    gap: 8,    
    paddingTop: 8,
  },
  filtersPanelScrollContent: {
    gap: 12,
    paddingTop: 5,
    paddingBottom: 4,
    paddingRight: 4,
  },
  browseSectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  browseSectionTitle: {
    color: '#8f6438',
    fontSize: 14,
    fontWeight: '800',
  },
  browseSectionMeta: {
    color: '#8f725d',
    fontSize: 12,
    fontWeight: '600',
  },
  browseSectionAction: {
    color: '#9e5b49',
    fontSize: 12,
    fontWeight: '700',
  },
  reloadButton: {
    alignItems: 'center',
    backgroundColor: '#9e5b49',
    borderRadius: 14,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  secondaryToolbarButton: {
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  secondaryToolbarButtonText: {
    color: '#5d4637',
    fontSize: 14,
    fontWeight: '700',
  },
  toolbarArrowButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  toolbarArrowButtonText: {
    color: '#5d4637',
    fontSize: 22,
    fontWeight: '700',
  },
  reloadButtonText: {
    color: '#f4fffe',
    fontSize: 22,
    fontWeight: '700',
  },
  mapThemeToggleButton: {
    alignItems: 'center',
    borderRadius: 14,
    justifyContent: 'center',
    height: 44,
    overflow: 'hidden',
    width: 44,
  },
  mapThemeToggleButtonFill: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    height: '100%',
    justifyContent: 'center',
    width: '100%',
  },
  mapThemeToggleButtonActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#9e5b49',
  },
  mapThemeToggleButtonText: {
    color: '#5d4637',
    fontSize: 18,
    fontWeight: '800',
  },
  mapThemeToggleButtonTextLayer: {
    position: 'absolute',
  },
  mapThemeToggleButtonTextActive: {
    color: '#f4fffe',
  },
  sectionTitle: {
    color: '#402214',
    fontSize: 18,
    fontWeight: '700',
  },
  detailSectionTitle: {
    marginTop: 22,
  },
  locationsSectionTitle: {
    paddingTop: 6,
    paddingBottom: 6,
  },
  filterRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  modeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  authPortalButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  authPortalButtonActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#9e5b49',
  },
  authPortalButtonText: {
    color: '#5d4637',
    fontSize: 15,
    fontWeight: '700',
  },
  authPortalButtonTextActive: {
    color: '#f4fffe',
  },
  modeSwitcherDock: {
    alignItems: 'flex-start',
    marginTop: 10,
  },
  modeSwitcherDockOverlay: {
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  modeSwitcherTrack: {
    backgroundColor: 'rgba(255, 250, 244, 0.96)',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    height: 44,
    overflow: 'hidden',
    padding: 4,
    position: 'relative',
  },
  modeSwitcherTrackOverlay: {
    backgroundColor: 'rgba(255, 247, 239, 0.98)',
  },
  modeLockBadge: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 116,
    paddingHorizontal: 16,
  },
  modeLockBadgeText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '800',
  },
  modeSwitcherThumb: {
    backgroundColor: '#9e5b49',
    borderRadius: 999,
    bottom: 4,
    left: 4,
    position: 'absolute',
    top: 4,
  },
  modeSwitchOption: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  modeSwitchOptionText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '700',
  },
  modeSwitchOptionTextActive: {
    color: '#f4fffe',
  },
  filterChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#cda883',
    borderRadius: 999,
    borderWidth: 1.5,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  filterChipActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#744030',
  },
  filterChipText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: '#fff7ef',
  },
  overlayChip: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 250, 244, 0.96)',
    borderColor: '#cda883',
    borderRadius: 999,
    borderWidth: 1.5,
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  overlayChipActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#744030',
  },
  overlayChipText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '600',
  },
  overlayChipTextActive: {
    color: '#fff7ef',
  },
  venueFilterRow: {
    alignItems: 'center',
    gap: 8,
    paddingRight: 16,
  },
  venueFilterChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#cda883',
    borderRadius: 999,
    borderWidth: 1.5,
    flexDirection: 'row',
    gap: 8,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  venueFilterChipActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#744030',
  },
  venueFilterBadge: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 2,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  venueFilterBadgeText: {
    color: '#fffaf4',
    fontSize: 11,
    fontWeight: '800',
  },
  mapMarker: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 2,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  mapMarkerActive: {
    borderWidth: 3,
    elevation: 4,
    shadowColor: '#1f160f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  mapMarkerText: {
    color: '#fffaf4',
    fontSize: 12,
    fontWeight: '900',
  },
  listContent: {
    gap: 12,
    paddingBottom: 142,
  },
  listContentLandscape: {
    paddingBottom: 148,
  },
  placeCardColumn: {
    gap: 12,
  },
  placeCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 22,
    borderWidth: 1,
    padding: 18,
  },
  placeCardLandscape: {
    flex: 1,
  },
  placeCity: {
    color: '#b07a3f',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  placeTitle: {
    color: '#2d221a',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 4,
  },
  placeMeta: {
    color: '#5c5043',
    fontSize: 14,
    marginTop: 4,
  },
  placeAddress: {
    color: '#7d614f',
    fontSize: 13,
    marginTop: 8,
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 40,
  },
  centerStateText: {
    color: '#6f5947',
    marginTop: 10,
  },
  detailScreenRoot: {
    flex: 1,
    backgroundColor: '#f7efe2',
  },
  detailScreenLandscape: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  detailScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 20,
  },
  detailScrollContentLandscape: {
    paddingTop: 0,
  },
  backButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  backButtonText: {
    color: '#402214',
    fontWeight: '700',
  },
  screenHeaderBar: {
    alignSelf: 'stretch',
    backgroundColor: '#9e5b49',
    borderBottomColor: '#7f4636',
    borderBottomWidth: 1,
    borderLeftWidth: 0,
    borderRadius: 0,
    borderRightWidth: 0,
    borderTopColor: '#b96d58',
    borderTopWidth: 1,
    marginHorizontal: -18,
    marginBottom: 14,
    marginTop: 0,
    minHeight: 96,
    paddingHorizontal: 18,
    paddingTop: 40,
    paddingBottom: 12,
  },
  screenHeaderBarSingle: {
    alignItems: 'flex-start',
  },
  screenHeaderBarRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  linkButtonDisabled: {
    opacity: 0.7,
  },
  detailCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 12,
    padding: 18,
    width: '100%',
  },
  detailCardLandscape: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  detailHeaderRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  detailHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  detailHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  detailCity: {
    color: '#b07a3f',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  detailTitle: {
    color: '#2d221a',
    fontSize: 26,
    fontWeight: '800',
    marginTop: 6,
  },
  detailMeta: {
    color: '#5f4b3d',
    fontSize: 14,
    marginTop: 6,
  },
  photoGalleryScroll: {
    marginTop: 10,
  },
  photoGalleryRow: {
    gap: 10,
    paddingRight: 4,
  },
  photoGalleryCard: {
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'relative',
    width: 176,
  },
  photoGalleryImage: {
    backgroundColor: '#ecdac7',
    height: 132,
    width: '100%',
  },
  photoGalleryDismissButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(64, 34, 20, 0.86)',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 8,
    top: 8,
    width: 28,
    zIndex: 1,
  },
  photoGalleryDismissButtonText: {
    color: '#fff7ef',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 14,
    textAlign: 'center',
  },
  photoGalleryMeta: {
    gap: 2,
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  photoLightboxOverlay: {
    backgroundColor: 'rgba(17, 12, 8, 0.96)',
    flex: 1,
  },
  photoLightboxHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingBottom: 10,
  },
  photoLightboxCounter: {
    color: '#fff7ef',
    fontSize: 15,
    fontWeight: '700',
  },
  photoLightboxCloseButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 247, 239, 0.14)',
    borderColor: 'rgba(255, 247, 239, 0.28)',
    borderRadius: 999,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  photoLightboxCloseButtonText: {
    color: '#fff7ef',
    fontSize: 14,
    fontWeight: '800',
  },
  photoLightboxSlide: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 18,
  },
  photoLightboxImage: {
    flex: 1,
    maxHeight: '100%',
    width: '100%',
  },
  favoriteStarButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    marginTop: 4,
    width: 48,
  },
  favoriteStarButtonActive: {
    backgroundColor: '#fff1d1',
    borderColor: '#d9a441',
  },
  favoriteStarIcon: {
    color: '#8f725d',
    fontSize: 26,
    lineHeight: 28,
    textAlign: 'center',
  },
  favoriteStarIconActive: {
    color: '#d08b00',
  },
  verifiedStatusBadge: {
    alignItems: 'center',
    backgroundColor: '#e7f7ef',
    borderColor: '#3f8f62',
    borderRadius: 999,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  verifiedStatusBadgeIcon: {
    color: '#23734a',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 26,
    textAlign: 'center',
  },
  detailAddress: {
    color: '#7c6252',
    fontSize: 14,
    marginTop: 4,
  },
  addressButton: {
    alignSelf: 'flex-start',
  },
  detailLinkText: {
    color: '#9e5b49',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
    textDecorationLine: 'underline',
  },
  detailMapCard: {
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 12,
    overflow: 'hidden',
  },
  detailMap: {
    height: 170,
    width: '100%',
  },
  detailMapCaption: {
    backgroundColor: '#fff7ef',
    borderTopColor: '#efd8bd',
    borderTopWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  detailMapCaptionText: {
    color: '#5f4b3d',
    fontSize: 13,
    fontWeight: '600',
  },
  reviewSummaryCard: {
    backgroundColor: '#fff3e5',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  reviewSummaryRating: {
    color: '#2d221a',
    fontSize: 18,
    fontWeight: '800',
  },
  reviewSummaryMeta: {
    color: '#6c5443',
    fontSize: 13,
    marginTop: 4,
  },
  reviewList: {
    gap: 12,
    marginTop: 12,
  },
  reviewCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  reviewQuote: {
    color: '#4d3a2f',
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 21,
  },
  linkButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#9e5b49',
    borderRadius: 14,
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  linkButtonText: {
    color: '#effffd',
    fontWeight: '700',
  },
  loadingButtonContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
  },
  linkButtonSecondary: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#9e5b49',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  linkButtonSecondaryText: {
    color: '#9e5b49',
    fontWeight: '700',
  },
  socialButtonsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  socialButtonCard: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minWidth: 150,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  socialButtonIconWrap: {
    alignItems: 'center',
    backgroundColor: '#f4e5d3',
    borderRadius: 999,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  socialButtonTextWrap: {
    flex: 1,
    gap: 2,
  },
  socialButtonLabel: {
    color: '#6f5647',
    fontSize: 12,
    fontWeight: '700',
  },
  socialButtonHandle: {
    color: '#2d221a',
    fontSize: 14,
    fontWeight: '800',
  },
  structuredEditorSection: {
    gap: 10,
    marginTop: 8,
  },
  structuredEditorCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#e6cfbb',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    marginTop: 8,
    padding: 12,
  },
  structuredNestedCard: {
    backgroundColor: '#fff4e8',
    borderColor: '#edd5bc',
    borderRadius: 14,
    borderWidth: 1,
    gap: 8,
    marginTop: 10,
    padding: 10,
  },
  structuredWeekdayRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  structuredDealTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  structuredWeekdayChip: {
    borderColor: '#d6b291',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  structuredWeekdayChipActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#9e5b49',
  },
  structuredWeekdayChipText: {
    color: '#9e5b49',
    fontSize: 12,
    fontWeight: '700',
  },
  structuredWeekdayChipTextActive: {
    color: '#fffaf4',
  },
  structuredTimeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  structuredTimeInput: {
    flex: 1,
  },
  structuredRemoveButton: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
  },
  structuredRemoveButtonText: {
    color: '#9e5b49',
    fontSize: 12,
    fontWeight: '700',
  },
  dealCard: {
    backgroundColor: '#fff3e5',
    borderRadius: 18,
    marginTop: 14,
    padding: 14,
  },
  dealHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  dealTitle: {
    color: '#2f241b',
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
  },
  pill: {
    backgroundColor: '#f8d8bf',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  pillText: {
    color: '#9a6a34',
    fontSize: 12,
    fontWeight: '700',
  },
  dealPrice: {
    color: '#b07a3f',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 10,
  },
  dealDescription: {
    color: '#5b4c41',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  dealTerms: {
    color: '#7a6658',
    fontSize: 13,
    marginTop: 8,
  },
  hourList: {
    gap: 10,
    marginTop: 10,
  },
  hourGroupCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd9c5',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  hourGroupDays: {
    color: '#9a6a34',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  hourRow: {
    color: '#43352c',
    fontSize: 13,
  },
  emptyStateText: {
    color: '#735e4c',
    fontSize: 14,
    lineHeight: 20,
    paddingVertical: 20,
  },
  errorBanner: {
    backgroundColor: '#ffe0d6',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  errorText: {
    color: '#8d2500',
    fontSize: 13,
    lineHeight: 18,
  },
  mapErrorBanner: {
    alignSelf: 'stretch',
  },
  splashScreen: {
    flex: 1,
    backgroundColor: '#f6ead8',
  },
  splashHeaderBar: {
    marginBottom: 0,
    minHeight: 96,
    paddingBottom: 10,
    paddingTop: 34,
    zIndex: 3,
  },
  splashHeaderBackButton: {
    minHeight: 44,
    marginTop: 8,
    marginLeft: 10,
    
    
  },
  splashHeaderCenterSlot: {
    width: 88,
  },
  splashHeaderSignInButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    marginRight: 10,
    marginTop: 8,
    minHeight: 44,
    minWidth: 96,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  splashHeaderSignInText: {
    color: '#5d4637',
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  splashBody: {
    alignItems: 'stretch',
    flex: 1,
    paddingHorizontal: 28,
    paddingBottom: 22,
  },
  splashScrollHeaderContent: {
    width: '100%',
  },
  splashScrollHeroSpacer: {
    height: 40,
  },
  splashIntroContent: {
    alignItems: 'center',
    flex: 1,
    width: '100%',
  },
  splashFloatingLogo: {
    alignItems: 'center',
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 18,
    zIndex: 5,
  },
  splashLogoImage: {
    height: 196,
    width: 196,
  },
  splashLogoRevealMask: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#f6ead8',
  },
  splashSloganBlock: {
    alignItems: 'center',
    gap: 12,
    marginBottom: 24,
    marginTop: 0,
  },
  splashSloganRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 8,
    justifyContent: 'center',
  },
  splashSloganWord: {
    color: '#2d221a',
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
  },
  splashActionGroup: {
    alignSelf: 'stretch',
    gap: 14,
    marginTop: 8,
    maxWidth: 420,
    paddingHorizontal: 4,
    width: '100%',
  },
  splashFeedSection: {
    alignSelf: 'stretch',
    flex: 1,
    marginTop: 24,
    minHeight: 220,
    width: '100%',
  },
  splashPortalButton: {
    alignItems: 'center',
    backgroundColor: '#fffaf4',
    borderColor: '#d7b48c',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 58,
    paddingHorizontal: 18,
    paddingVertical: 14,
    shadowColor: '#5b3b25',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 6,
  },
  splashPortalButtonText: {
    color: '#5d4637',
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  splashCreateAccountLink: {
    alignSelf: 'center',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  splashCreateAccountText: {
    color: '#9e5b49',
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  splashSignInOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    zIndex: 40,
  },
  splashSignInModalBackdropPressable: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(45, 34, 26, 0.58)',
  },
  splashSignInModalCardWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  splashSignInModalCard: {
    backgroundColor: '#fff8f1',
    borderColor: '#edd4b8',
    borderRadius: 28,
    borderWidth: 1,
    gap: 14,
    maxWidth: 360,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 18,
    width: '100%',
  },
  splashSignInModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 34,
  },
  splashSignInModalHeaderSpacer: {
    height: 32,
    width: 32,
  },
  splashSignInModalCloseButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  splashSignInModalCloseButtonText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '800',
  },
  splashSignInModalTitle: {
    color: '#402214',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  splashSignInModalText: {
    color: '#6c5443',
    fontSize: 14,
    lineHeight: 21,
  },
  splashSignInModalActions: {
    gap: 10,
    marginTop: 4,
  },
  splashSignInPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#a86550',
    borderRadius: 14,
    minHeight: 54,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  splashSignInPrimaryButtonText: {
    color: '#fffaf4',
    fontSize: 15,
    fontWeight: '800',
  },
  splashSignInSecondaryButton: {
    alignItems: 'center',
    backgroundColor: '#fff8f1',
    borderColor: '#e4c6a7',
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 54,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  splashSignInSecondaryButtonText: {
    color: '#6a4e3d',
    fontSize: 15,
    fontWeight: '700',
  },
  splashSignInTertiaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  splashSignInTertiaryButtonText: {
    color: '#9e5b49',
    fontSize: 14,
    fontWeight: '800',
    textDecorationLine: 'underline',
  },
  authScreen: {
    flex: 1,
  },
  keyboardAvoidingFill: {
    flex: 1,
  },
  authScrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 20,
  },
  authFormStack: {
    alignSelf: 'center',
    gap: 14,
    marginTop: 18,
    maxWidth: 420,
    width: '100%',
  },
  authHero: {
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 8,
    paddingHorizontal: 12,
  },
  authLinkButton: {
    alignSelf: 'center',
    marginTop: 12,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  authRecoveryRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  authRecoveryButton: {
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  authRecoveryButtonText: {
    color: '#9e5b49',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  authRecoveryPanel: {
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  authRecoveryPanelActions: {
    gap: 10,
  },
  authRecoveryDismissButton: {
    alignSelf: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  authRecoveryDismissText: {
    color: '#9e5b49',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  authLinkText: {
    color: '#9e5b49',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  profileScreen: {
    flex: 1,
  },
  profileScreenLandscape: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  profileScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 132,
  },
  createProfileScrollContent: {
    paddingBottom: 140,
  },
  dashboardScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 132,
  },
  profileCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginTop: 12,
    padding: 18,
  },
  dashboardCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginTop: 8,
    padding: 18,
  },
  dashboardShell: {
    gap: 18,
    marginTop: 8,
    paddingBottom: 12,
  },
  profileIntroText: {
    color: '#6c5443',
    fontSize: 14,
    lineHeight: 20,
  },
  profileSuccessBanner: {
    backgroundColor: '#f5ebe2',
    borderColor: '#dfc3af',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  profileSuccessText: {
    color: '#8d6042',
    fontSize: 13,
    fontWeight: '700',
  },
  profileFormSection: {
    gap: 10,
  },
  profileFieldLabel: {
    color: '#402214',
    fontSize: 13,
    fontWeight: '700',
  },
  profileInput: {
    backgroundColor: '#f8efe3',
    borderColor: '#ead6bf',
    borderRadius: 14,
    borderWidth: 1,
    color: '#2d221a',
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  passwordFieldRow: {
    justifyContent: 'center',
    position: 'relative',
  },
  passwordFieldInput: {
    paddingRight: 48,
  },
  passwordToggleButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
    minWidth: 40,
    position: 'absolute',
    right: 4,
    top: 4,
  },
  passwordEyeIcon: {
    alignItems: 'center',
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  passwordEyeOutline: {
    alignItems: 'center',
    borderColor: '#9e5b49',
    borderRadius: 999,
    borderWidth: 1.6,
    height: 12,
    justifyContent: 'center',
    width: 18,
  },
  passwordEyePupil: {
    backgroundColor: '#9e5b49',
    borderRadius: 999,
    height: 4,
    width: 4,
  },
  passwordEyeSlash: {
    backgroundColor: '#9e5b49',
    borderRadius: 999,
    height: 1.8,
    position: 'absolute',
    transform: [{ rotate: '-35deg' }],
    width: 20,
  },
  compactDropdownWrap: {
    gap: 6,
  },
  compactDropdownButton: {
    backgroundColor: '#f8efe3',
    borderColor: '#ead6bf',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  compactDropdownButtonOpen: {
    borderColor: '#9e5b49',
  },
  compactDropdownText: {
    color: '#2d221a',
    fontSize: 14,
    lineHeight: 18,
  },
  compactDropdownPlaceholder: {
    color: '#8a705d',
  },
  compactDropdownCaret: {
    color: '#6c5443',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 12,
  },
  compactDropdownMenu: {
    backgroundColor: '#fffaf4',
    borderColor: '#ead6bf',
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  compactDropdownOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  compactDropdownOptionSelected: {
    backgroundColor: '#f5ebe2',
  },
  compactDropdownOptionText: {
    color: '#2d221a',
    fontSize: 14,
    lineHeight: 18,
  },
  compactDropdownOptionTextSelected: {
    color: '#8d6042',
    fontWeight: '700',
  },
  profileSupportText: {
    color: '#7d614f',
    fontSize: 12,
    lineHeight: 18,
    marginTop: -2,
  },
  verificationCodeInput: {
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 8,
    textAlign: 'center',
  },
  verificationCountdownText: {
    color: '#8d6042',
    fontSize: 13,
    fontWeight: '700',
  },
  supportMessageInput: {
    minHeight: 144,
    paddingTop: 12,
  },
  claimResultsList: {
    gap: 12,
    marginTop: 8,
  },
  claimResultCard: {
    backgroundColor: '#fff3e5',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  linkButtonSecondaryWide: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#fff7ef',
    borderColor: '#9e5b49',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dashboardCalloutCard: {
    backgroundColor: '#fff3e5',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  claimBusinessHint: {
    color: '#6c5443',
    fontSize: 13,
    lineHeight: 18,
  },
  claimLocationList: {
    gap: 8,
    marginTop: 6,
  },
  claimLocationButton: {
    backgroundColor: '#fffaf4',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  claimLocationButtonTitle: {
    color: '#402214',
    fontSize: 13,
    fontWeight: '700',
  },
  claimLocationButtonText: {
    color: '#5f4b3d',
    fontSize: 13,
    lineHeight: 18,
  },
  dashboardVerifiedCard: {
    backgroundColor: '#f5ebe2',
    borderColor: '#dfc3af',
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  dashboardVerifiedTitle: {
    color: '#8d6042',
    fontSize: 16,
    fontWeight: '800',
  },
  dashboardVerifiedText: {
    color: '#8d6042',
    fontSize: 13,
    lineHeight: 18,
  },
  dashboardStatusBanner: {
    gap: 10,
  },
  dashboardSectionCard: {
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  dashboardSection: {
    gap: 10,
  },
  dashboardSectionTitle: {
    color: '#402214',
    fontSize: 16,
    fontWeight: '800',
  },
  dashboardSupportText: {
    color: '#6c5443',
    fontSize: 13,
    lineHeight: 18,
  },
  dashboardDetailRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'space-between',
  },
  dashboardFieldGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  dashboardFieldColumn: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 220,
  },
  dashboardDetailItem: {
    flexGrow: 1,
    flexShrink: 1,
    gap: 4,
    minWidth: 160,
  },
  dashboardFavoriteBusinessCard: {
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
  },
  dashboardFavoriteBusinessAction: {
    color: '#9e5b49',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  dashboardDetailLabel: {
    color: '#7a4d2f',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  dashboardDetailValue: {
    color: '#2d221a',
    fontSize: 15,
    lineHeight: 20,
  },
  dashboardInlineActions: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  dashboardInlineButton: {
    alignSelf: 'flex-start',
    marginTop: 0,
    minWidth: 220,
  },
  settingsItemRow: {
    alignItems: 'flex-start',
    gap: 10,
  },
  settingsItemBody: {
    gap: 8,
    width: '100%',
  },
  settingsItemActions: {
    alignItems: 'stretch',
    gap: 10,
    width: '100%',
  },
  settingsInlineButton: {
    alignSelf: 'stretch',
    marginTop: 0,
    maxWidth: '100%',
    width: '100%',
  },
  settingsSwitchCluster: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    width: '100%',
  },
  settingsSwitchLabelGroup: {
    alignItems: 'flex-start',
    gap: 2,
  },
  dashboardCodeCard: {
    backgroundColor: '#fff3e5',
    borderColor: '#efd8bd',
    borderRadius: 16,
    borderWidth: 1,
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dashboardCodeLabel: {
    color: '#7a4d2f',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  dashboardCodeValue: {
    color: '#2d221a',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  dashboardCodeActionButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  dashboardCodeActionText: {
    color: '#5d4637',
    fontSize: 13,
    fontWeight: '700',
  },
  dashboardCodeHelpText: {
    color: '#6c5443',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 10,
  },
  dashboardQrCard: {
    alignItems: 'center',
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  dashboardQrImage: {
    alignItems: 'center',
    borderRadius: 12,
    height: 180,
    justifyContent: 'center',
    width: 180,
  },
  dashboardQrMatrix: {
    alignItems: 'stretch',
    backgroundColor: '#fffaf4',
    padding: 8,
  },
  dashboardQrMatrixRow: {
    flexDirection: 'row',
  },
  dashboardQrMatrixCell: {
    backgroundColor: '#fffaf4',
  },
  dashboardQrLoadingState: {
    alignItems: 'center',
    height: 180,
    justifyContent: 'center',
    paddingHorizontal: 12,
    width: 180,
  },
  dashboardQrMeta: {
    alignItems: 'center',
    gap: 4,
  },
  dashboardQrTitle: {
    color: '#2d221a',
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  dashboardQrSubtitle: {
    color: '#6c5443',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  dashboardFooterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  dashboardHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  settingsIconButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  settingsGearIcon: {
    alignItems: 'center',
    height: 20,
    justifyContent: 'center',
    position: 'relative',
    width: 20,
  },
  settingsGearTooth: {
    backgroundColor: '#402214',
    borderRadius: 1,
    height: 4,
    position: 'absolute',
    width: 3,
  },
  settingsGearToothTop: {
    top: 0,
  },
  settingsGearToothTopRight: {
    right: 3,
    top: 2,
    transform: [{ rotate: '45deg' }],
  },
  settingsGearToothRight: {
    right: 0,
    transform: [{ rotate: '90deg' }],
  },
  settingsGearToothBottomRight: {
    bottom: 2,
    right: 3,
    transform: [{ rotate: '135deg' }],
  },
  settingsGearToothBottom: {
    bottom: 0,
  },
  settingsGearToothBottomLeft: {
    bottom: 2,
    left: 3,
    transform: [{ rotate: '45deg' }],
  },
  settingsGearToothLeft: {
    left: 0,
    transform: [{ rotate: '90deg' }],
  },
  settingsGearToothTopLeft: {
    left: 3,
    top: 2,
    transform: [{ rotate: '135deg' }],
  },
  settingsGearOuterRing: {
    alignItems: 'center',
    borderColor: '#402214',
    borderRadius: 999,
    borderWidth: 2,
    height: 14,
    justifyContent: 'center',
    width: 14,
  },
  settingsGearInnerHole: {
    backgroundColor: '#fff7ef',
    borderRadius: 999,
    borderColor: '#402214',
    borderWidth: 1.5,
    height: 5,
    width: 5,
  },
  legalSectionCard: {
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  destructiveButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: '#ffe8e1',
    borderColor: '#c85b37',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  destructiveButtonText: {
    color: '#8d2500',
    fontWeight: '700',
  },
  toggleChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff7ef',
    borderColor: '#caa98d',
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  toggleChipActive: {
    backgroundColor: '#9e5b49',
    borderColor: '#9e5b49',
  },
  toggleChipText: {
    color: '#7a4d2f',
    fontSize: 13,
    fontWeight: '700',
  },
  toggleChipTextActive: {
    color: '#effffd',
  },
  profileTextarea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  attachmentSection: {
    marginTop: 2,
  },
  attachmentPickerButton: {
    marginTop: 0,
  },
  attachmentGalleryLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    marginTop: 12,
  },
  attachmentGalleryLabel: {
    color: '#5f4b3d',
    fontSize: 13,
    fontWeight: '700',
  },
  attachmentGalleryCount: {
    color: '#7d614f',
    fontSize: 12,
    fontWeight: '700',
  },
  attachmentSupportText: {
    marginTop: 4,
  },
  attachmentList: {
    gap: 8,
    marginTop: 10,
  },
  attachmentCard: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#efd8bd',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  attachmentMeta: {
    flex: 1,
    gap: 2,
  },
  attachmentPreviewButton: {
    flex: 1,
  },
  attachmentName: {
    color: '#3b2a1f',
    fontSize: 13,
    fontWeight: '700',
  },
  attachmentDetail: {
    color: '#7d614f',
    fontSize: 12,
  },
  attachmentRemoveButton: {
    backgroundColor: '#fde7dd',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  attachmentRemoveButtonText: {
    color: '#8d2500',
    fontSize: 12,
    fontWeight: '700',
  },
  attachmentPreviewOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(45, 34, 26, 0.62)',
    flex: 1,
    justifyContent: 'center',
    padding: 16,
  },
  attachmentPreviewSheet: {
    backgroundColor: '#f7efe2',
    borderColor: '#ddc4a7',
    borderRadius: 22,
    borderWidth: 1,
    flex: 1,
    maxHeight: '92%',
    maxWidth: 920,
    overflow: 'hidden',
    width: '100%',
  },
  attachmentPreviewHeader: {
    alignItems: 'center',
    borderBottomColor: '#ead6bf',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  attachmentPreviewTitle: {
    color: '#402214',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  attachmentPreviewCloseButton: {
    backgroundColor: '#fff7ef',
    borderColor: '#caa98d',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  attachmentPreviewCloseButtonText: {
    color: '#7a4d2f',
    fontSize: 13,
    fontWeight: '700',
  },
  attachmentPreviewBody: {
    backgroundColor: '#f3e7d8',
    flex: 1,
  },
  attachmentPreviewLoadingState: {
    alignItems: 'center',
    flex: 1,
    gap: 12,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  attachmentPreviewLoadingText: {
    color: '#7d614f',
    fontSize: 13,
    textAlign: 'center',
  },
  attachmentPreviewImage: {
    flex: 1,
    width: '100%',
  },
  guestFavoriteModalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(45, 34, 26, 0.58)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  guestFavoriteModalCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#efd8bd',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    maxWidth: 420,
    padding: 22,
    width: '100%',
  },
  guestBottomNavCloseButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 999,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    marginBottom: 2,
    width: 32,
  },
  guestBottomNavCloseButtonText: {
    color: '#5d4637',
    fontSize: 14,
    fontWeight: '800',
  },
  guestFavoriteModalTitle: {
    color: '#402214',
    fontSize: 20,
    fontWeight: '800',
  },
  guestFavoriteModalText: {
    color: '#6c5443',
    fontSize: 14,
    lineHeight: 21,
  },
  guestFavoriteModalActions: {
    gap: 10,
    marginTop: 4,
  },
  guestFavoriteModalSecondaryButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  guestFavoriteModalSecondaryText: {
    color: '#5d4637',
    fontSize: 14,
    fontWeight: '700',
  },
  guestFavoriteModalPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#9e5b49',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  guestFavoriteModalPrimaryText: {
    color: '#fffaf4',
    fontSize: 14,
    fontWeight: '800',
  },
  bottomSheetBackdrop: {
    backgroundColor: 'rgba(45, 34, 26, 0.22)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  bottomSheetBackdropPressable: {
    flex: 1,
  },
  bottomSheetCard: {
    backgroundColor: '#fffaf4',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: '#ead6bf',
    gap: 10,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 34,
    shadowColor: '#2d221a',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
  },
  bottomSheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#d5c1ad',
    borderRadius: 999,
    height: 5,
    marginBottom: 6,
    width: 46,
  },
  bottomSheetTitle: {
    color: '#402214',
    fontSize: 19,
    fontWeight: '800',
    marginBottom: 4,
  },
  bottomSheetActionButton: {
    backgroundColor: 'rgba(255, 247, 239, 0.88)',
    borderColor: '#e5d0b9',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  bottomSheetActionButtonDestructive: {
    backgroundColor: '#fff1ed',
    borderColor: '#efb1a7',
    marginTop: 4,
  },
  bottomSheetActionText: {
    color: '#402214',
    fontSize: 15,
    fontWeight: '700',
  },
  bottomSheetActionTextDestructive: {
    color: '#a34a3c',
  },
  attachmentPreviewWebView: {
    backgroundColor: '#f3e7d8',
    flex: 1,
  },
  socialPreviewList: {
    gap: 8,
    marginTop: 2,
  },
  socialPreviewCard: {
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  socialPreviewCardDisabled: {
    opacity: 0.7,
  },
  socialPreviewLink: {
    color: '#3b2a1f',
    fontSize: 13,
    fontWeight: '700',
  },
  socialPreviewAction: {
    color: '#9e5b49',
    fontSize: 12,
    fontWeight: '700',
  },
  structuredEntrySection: {
    gap: 8,
  },
  structuredEntryInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  structuredEntryInput: {
    flex: 1,
  },
  structuredEntryAddButton: {
    backgroundColor: '#9e5b49',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  structuredEntryAddButtonText: {
    color: '#effffd',
    fontSize: 12,
    fontWeight: '700',
  },
  structuredEntryErrorText: {
    color: '#8d2500',
    fontSize: 12,
    fontWeight: '700',
    marginTop: -2,
  },
  structuredEntryList: {
    gap: 8,
  },
  structuredEntryCard: {
    alignItems: 'center',
    backgroundColor: '#fff7ef',
    borderColor: '#ddc4a7',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  structuredEntryText: {
    color: '#3b2a1f',
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  structuredEntryRemoveButton: {
    backgroundColor: '#fde7dd',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  structuredEntryRemoveButtonText: {
    color: '#8d2500',
    fontSize: 12,
    fontWeight: '700',
  },
  homeFeedHeaderWrap: {
    marginBottom: 14,
  },
  homeFeedHeader: {
    gap: 8,
  },
  homeFeedEyebrow: {
    color: '#b07a3f',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  homeFeedTitle: {
    color: '#241913',
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 31,
  },
  homeFeedSubtitle: {
    color: '#6a5647',
    fontSize: 14,
    lineHeight: 20,
  },
  homeFeedListContent: {
    gap: 14,
    paddingBottom: 142,
  },
  homeFeedCard: {
    backgroundColor: '#fffaf4',
    borderColor: '#ecd8c2',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    padding: 18,
    shadowColor: '#1f160f',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
  },
  homeFeedCardLandscape: {
    marginHorizontal: 28,
  },
  homeFeedCardPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.995 }],
  },
  homeFeedCardSpecial: {
    borderLeftColor: '#c65d1f',
    borderLeftWidth: 4,
  },
  homeFeedCardAnnouncement: {
    borderLeftColor: '#8b5e3c',
    borderLeftWidth: 4,
  },
  homeFeedCardEvent: {
    borderLeftColor: '#1f5f5b',
    borderLeftWidth: 4,
  },
  homeFeedCardBlog: {
    borderLeftColor: '#5f7cc6',
    borderLeftWidth: 4,
  },
  homeFeedCardSponsorAccent: {
    borderLeftColor: '#d49718',
    borderLeftWidth: 4,
  },
  homeFeedCardSponsored: {
    backgroundColor: '#fff8ea',
    borderColor: '#e9d194',
  },
  homeFeedSponsoredBand: {
    alignItems: 'center',
    backgroundColor: '#fff1bf',
    borderColor: '#e1c463',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignSelf: 'flex-start',
  },
  homeFeedSponsoredBandText: {
    color: '#6f4c00',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  homeFeedSponsoredBandMeta: {
    color: '#7c6340',
    fontSize: 12,
    fontWeight: '700',
    maxWidth: '75%',
  },
  homeFeedCardHeader: {
    marginBottom: 14,
  },
  homeFeedHeaderCopy: {
    gap: 6,
  },
  homeFeedBadgeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  homeFeedBadge: {
    backgroundColor: '#f7e4d6',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  homeFeedBadgeSponsored: {
    backgroundColor: '#f5d87a',
  },
  homeFeedBadgeText: {
    color: '#8a4018',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  homeFeedBadgeTextSponsored: {
    color: '#6f4c00',
  },
  homeFeedBusinessName: {
    color: '#34261d',
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
  },
  homeFeedMetaText: {
    color: '#7a6656',
    fontSize: 13,
    fontWeight: '600',
  },
  homeFeedHeroImage: {
    borderRadius: 18,
    height: 176,
    marginBottom: 14,
    width: '100%',
  },
  homeFeedImagePlaceholder: {
    alignItems: 'center',
    backgroundColor: '#efe4d6',
    borderRadius: 18,
    height: 120,
    justifyContent: 'center',
    marginBottom: 14,
  },
  homeFeedImagePlaceholderText: {
    color: '#765f4d',
    fontSize: 13,
    fontWeight: '700',
  },
  homeFeedCardTitle: {
    color: '#261a13',
    fontSize: 21,
    fontWeight: '900',
    lineHeight: 26,
  },
  homeFeedCardSummary: {
    color: '#56483c',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
    marginTop: 8,
  },
  homeFeedBodyPreview: {
    color: '#6d5b4d',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  homeFeedActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  homeFeedActionText: {
    color: '#c65d1f',
    fontSize: 14,
    fontWeight: '900',
  },
  homeFeedActionArrow: {
    color: '#c65d1f',
    fontSize: 18,
    fontWeight: '900',
  },
  homeFeedLoadingState: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  homeFeedLoadingText: {
    color: '#6f5947',
    marginTop: 10,
  },
  homeFeedFooterLoading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    paddingBottom: 22,
    paddingTop: 8,
  },
  homeFeedFooterText: {
    color: '#6f5947',
    fontSize: 13,
    fontWeight: '700',
  },
  homeFeedFooterSpacer: {
    height: 24,
  },
  homeFeedEmptyState: {
    alignItems: 'center',
    backgroundColor: '#fffaf4',
    borderColor: '#ecd8c2',
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  homeFeedEmptyStateWrap: {
    paddingTop: 6,
  },
  homeFeedEmptyTitle: {
    color: '#2d221a',
    fontSize: 18,
    fontWeight: '900',
  },
  homeFeedEmptyText: {
    color: '#6f5947',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
    textAlign: 'center',
  },
});
